import {
  amount,
  beat,
  choose as c,
  card,
  formula,
  numeric as n,
  type TeachingLesson,
} from "./definition.js";
export const amounts: TeachingLesson[] = [
  {
    id: "reading-chemical-formulas",
    title: "Reading a chemical formula",
    summary: "Separate subscripts inside a formula from coefficients multiplying whole units.",
    moduleId: "chem-amounts",
    sourceIds: ["chem-formula"],
    beats: [
      beat(
        "Count whole units",
        "H₂O means two H atoms and one O atom per water molecule. A coefficient multiplies the whole formula, so 3 H₂O contains six H atoms and three O atoms.",
        ["Three waters", formula("H2O", 3)],
        ["One water", formula("H2O", 1)],
      ),
      beat(
        "Multiply every element",
        "Al₂O₃ gives a two-to-three ratio of aluminium to oxygen. Two formula units contain four aluminium atoms and six oxygen atoms.",
        ["Two oxide units", formula("Al2O3", 2)],
        ["One oxide unit", formula("Al2O3", 1)],
      ),
      beat(
        "Keep a substance intact",
        "Changing a coefficient changes the amount. Changing a subscript changes the formula and may describe a different substance.",
        ["Two waters", formula("H2O", 2)],
        ["Four waters", formula("H2O", 4)],
      ),
      beat(
        "Read the invisible one",
        "NH₃ contains one nitrogen and three hydrogen atoms. A missing subscript means one. Five molecules contain five N atoms and fifteen H atoms.",
        ["Five ammonias", formula("NH3", 5)],
        ["Two ammonias", formula("NH3", 2)],
      ),
    ],
    questions: [
      n(
        "How many oxygen atoms are in 3 H₂O molecules?",
        3,
        "Each molecule has one oxygen: 3 × 1 = 3.",
        "Multiply the O subscript, which is one, by the coefficient.",
        "atoms",
      ),
      n(
        "How many oxygen atoms are represented by 2 Al₂O₃ formula units?",
        6,
        "Each unit has three O atoms: 2 × 3 = 6.",
        "Multiply the entire formula by two.",
        "atoms",
      ),
      c(
        "To double an amount of water without changing the substance, what do you change?",
        ["The coefficient before H₂O", "The subscript after H", "The element symbol O"],
        0,
        "A coefficient multiplies whole water molecules.",
        "Keep the formula of each molecule fixed.",
      ),
      n(
        "How many hydrogen atoms are in 5 NH₃ molecules?",
        15,
        "5 × 3 = 15 hydrogen atoms.",
        "Each ammonia molecule contributes three H atoms.",
        "atoms",
      ),
      n(
        "How many chlorine atoms are represented by 4 MgCl₂ formula units?",
        8,
        "Each unit contributes two Cl atoms: 4 × 2 = 8.",
        "Apply the coefficient to chlorine too.",
        "atoms",
      ),
      c(
        "What does 2 H₂ represent?",
        [
          "One molecule with four bonded H atoms",
          "Two molecules with two H atoms each",
          "Two isolated H atoms",
        ],
        1,
        "The coefficient counts molecules and the subscript counts atoms per molecule.",
        "Read the outside number separately from the inside number.",
      ),
    ],
    cards: [
      card(
        "How many oxygen atoms are in 6 CO₂ molecules?",
        12,
        "6 × 2 = 12 oxygen atoms.",
        "atoms",
      ),
      card(
        "How many atoms of all elements are in 3 CH₄ molecules?",
        15,
        "Each has 1 + 4 = 5 atoms; three have 15.",
        "atoms",
      ),
    ],
  },
  {
    id: "adding-atomic-masses",
    title: "Adding atomic masses",
    summary: "Build formula mass from atom counts and stated rounded atomic masses.",
    moduleId: "chem-amounts",
    sourceIds: ["chem-mole"],
    beats: [
      beat(
        "Weigh a formula",
        "For these estimates use H = 1 u, C = 12 u, N = 14 u and O = 16 u. Water's formula mass is 2 × 1 + 16 = 18 u.",
        ["Water", formula("H2O")],
        ["Hydrogen", formula("H2")],
      ),
      beat(
        "Count repeated atoms",
        "A CO₂ molecule contains one carbon and two oxygen atoms. Using C = 12 u and O = 16 u gives 12 + 2 × 16 = 44 u.",
        ["Carbon dioxide", formula("CO2")],
        ["Methane", formula("CH4")],
      ),
      beat(
        "Use the stated precision",
        "Rounded atomic masses are estimates for this course's arithmetic. They do not turn average atomic masses into exact integer measurements.",
        ["Ammonia", formula("NH3")],
        ["Nitrogen", formula("N2")],
      ),
      beat(
        "Count a formula unit",
        "Ionic solids also have formula masses. With Mg = 24 u and Cl = 35.5 u, MgCl₂ has formula mass 24 + 2 × 35.5 = 95 u.",
        ["Magnesium chloride", formula("MgCl2")],
        ["Sodium chloride", formula("NaCl")],
      ),
    ],
    questions: [
      n(
        "Using H = 1 u and O = 16 u, find the formula mass of H₂O in u.",
        18,
        "2 × 1 + 16 = 18 u.",
        "Add both hydrogens before adding oxygen.",
        "u",
      ),
      n(
        "Using C = 12 u and O = 16 u, find the formula mass of CO₂ in u.",
        44,
        "12 + 2 × 16 = 44 u.",
        "There are two oxygen atoms.",
        "u",
      ),
      c(
        "Why must you use the atomic masses stated in a problem?",
        [
          "All isotope masses are exact integers",
          "The stated values set the intended approximation",
          "Atomic mass depends on the size of the drawing",
        ],
        1,
        "Using the same stated precision keeps the calculation consistent.",
        "Distinguish rounded estimates from precise tabulated masses.",
      ),
      n(
        "Using Mg = 24 u and Cl = 35.5 u, find the formula mass of MgCl₂ in u.",
        95,
        "24 + 2 × 35.5 = 95 u.",
        "The subscript multiplies chlorine's mass.",
        "u",
      ),
      n(
        "Using N = 14 u and H = 1 u, find the formula mass of NH₃ in u.",
        17,
        "14 + 3 × 1 = 17 u.",
        "The missing subscript after N means one.",
        "u",
      ),
      c(
        "Which operation finds the mass of one CO₂ molecule from atomic masses?",
        [
          "Average the masses of C and O",
          "Add one C mass and twice the O mass",
          "Multiply C mass by O mass",
        ],
        1,
        "Formula mass sums the masses of the atoms present.",
        "Count each atom's contribution.",
      ),
    ],
    cards: [
      card(
        "Use Al = 27 u and O = 16 u. Find the formula mass of Al₂O₃ in u.",
        102,
        "2 × 27 + 3 × 16 = 102 u.",
        "u",
      ),
      card(
        "Use Na = 23 u and Cl = 35.5 u. Find the formula mass of NaCl in u.",
        58.5,
        "23 + 35.5 = 58.5 u.",
        "u",
      ),
    ],
  },
  {
    id: "from-moles-to-mass",
    title: "From moles to mass",
    summary: "Convert between amount and mass while identifying what one mole counts.",
    moduleId: "chem-amounts",
    sourceIds: ["chem-mole"],
    beats: [
      beat(
        "Count an enormous group",
        "A mole contains exactly 6.02214076 × 10²³ specified entities. One mole of H₂O counts water molecules; one mole of NaCl counts formula units.",
        ["Two moles of water", amount("H2O", 2)],
        ["One mole of water", amount("H2O", 1)],
      ),
      beat(
        "Use grams per mole",
        "Molar mass M converts amount n to mass m: m = nM. With M(H₂O) = 18 g/mol, two moles have mass 36 g.",
        ["Two moles of water", amount("H2O", 2)],
        ["Three moles of water", amount("H2O", 3)],
      ),
      beat(
        "Reverse the conversion",
        "To find amount from mass, divide by molar mass: n = m/M. For CO₂ at 44 g/mol, 22 g corresponds to 0.5 mol.",
        ["Half a mole of CO₂", amount("CO2", 0.5)],
        ["One mole of CO₂", amount("CO2", 1)],
      ),
      beat(
        "Count atoms within molecules",
        "One mole of NH₃ molecules contains three moles of H atoms and one mole of N atoms. The subscript ratio works for molecules and for moles.",
        ["Two moles of ammonia", amount("NH3", 2)],
        ["One mole of ammonia", amount("NH3", 1)],
      ),
    ],
    questions: [
      n(
        "Using M(H₂O) = 18 g/mol, find the mass of 2 mol of water in grams.",
        36,
        "m = nM = 2 × 18 = 36 g.",
        "Multiply the amount by grams per mole.",
        "g",
      ),
      c(
        "What does one mole of H₂O count?",
        [
          "Water molecules",
          "Only oxygen atoms separated from water",
          "Grams regardless of the substance",
        ],
        0,
        "The specified entities are water molecules.",
        "Read the formula after the amount unit.",
      ),
      n(
        "Using M(CO₂) = 44 g/mol, how many moles are in 22 g of CO₂?",
        0.5,
        "n = m/M = 22/44 = 0.5 mol.",
        "Divide mass by grams per mole.",
        "mol",
      ),
      n(
        "How many moles of H atoms are contained in 2 mol of NH₃ molecules?",
        6,
        "Each NH₃ contains three H atoms: 2 × 3 = 6 mol H atoms.",
        "Apply the subscript to the molar amount.",
        "mol",
      ),
      n(
        "Using M(CH₄) = 16 g/mol, find the mass of 3 mol of methane in grams.",
        48,
        "3 × 16 = 48 g.",
        "Use m = nM.",
        "g",
      ),
      c(
        "Equal moles of water and carbon dioxide have what in common?",
        [
          "Equal masses in grams",
          "Equal numbers of molecules",
          "Equal numbers of atoms per molecule",
        ],
        1,
        "The mole counts entities; the different molecules have different molar masses.",
        "Compare counts before comparing masses.",
      ),
    ],
    cards: [
      card(
        "Using M(NH₃) = 17 g/mol, how many moles are in 51 g of ammonia?",
        3,
        "51/17 = 3 mol.",
        "mol",
      ),
      card(
        "Using M(O₂) = 32 g/mol, find the mass of 0.75 mol of oxygen in grams.",
        24,
        "0.75 × 32 = 24 g.",
        "g",
      ),
    ],
  },
];
