import { atom, beat, choose as c, card, numeric as n, type TeachingLesson } from "./definition.js";
export const atoms: TeachingLesson[] = [
  {
    id: "what-makes-an-element",
    title: "What makes an element?",
    summary: "Use protons to identify an element and separate identity from mass and charge.",
    moduleId: "chem-particles",
    sourceIds: ["chem-atom"],
    beats: [
      beat(
        "Count the centre",
        "An element is identified by its proton count. That count is its atomic number, Z. Oxygen has eight protons even when its neutrons or electrons change.",
        ["Oxygen", atom(8, 8)],
        ["Carbon", atom(6, 6)],
      ),
      beat(
        "Keep the identity",
        "A neutron adds to the nucleus without changing the element. An electron changes charge without changing the nucleus.",
        ["Carbon-12", atom(6, 6)],
        ["Carbon-13", atom(6, 7)],
      ),
      beat(
        "Balance the charge",
        "A proton carries one positive charge and an electron one negative charge. A neutral atom has equal numbers of the two.",
        ["Neutral nitrogen", atom(7, 7)],
        ["Nitrogen ion", atom(7, 7, 10)],
      ),
      beat(
        "Read the symbol",
        "Al is the symbol for aluminium. Its atomic number is 13, so any aluminium atom has thirteen protons. The symbol does not specify its neutron count.",
        ["Aluminium-27", atom(13, 14)],
        ["Aluminium ion", atom(13, 14, 10)],
      ),
    ],
    questions: [
      n(
        "Oxygen has 8 protons, 8 neutrons and 8 electrons. What is its atomic number?",
        8,
        "Atomic number counts protons, so Z = 8.",
        "Choose the particle that identifies the element.",
        "protons",
      ),
      c(
        "The two carbon cases differ in neutron count. Why are they both carbon?",
        ["Their proton counts agree", "Their masses agree", "Their total particle counts agree"],
        0,
        "Each nucleus still contains six protons.",
        "Compare the nuclei's proton counts.",
      ),
      n(
        "A neutral nitrogen atom has 7 protons. How many electrons does it have?",
        7,
        "Seven electrons cancel the charge of seven protons.",
        "Neutral means no net electric charge.",
        "electrons",
      ),
      n(
        "Aluminium has atomic number 13. How many protons does an aluminium ion contain?",
        13,
        "Ion formation changes electrons, so its thirteen protons remain.",
        "An ion retains its element's nucleus.",
        "protons",
      ),
      c(
        "Which change makes a carbon atom an atom of a different element?",
        ["Add a neutron", "Remove an electron", "Add a proton"],
        2,
        "Changing the proton count changes the atomic number.",
        "Distinguish identity from charge and mass.",
      ),
      n(
        "A fluorine nucleus contains 9 protons and 10 neutrons. How many particles are in its nucleus?",
        19,
        "Only protons and neutrons are in the nucleus: 9 + 10 = 19.",
        "Leave electrons out of the nucleus count.",
        "particles",
      ),
    ],
    cards: [
      card(
        "An atom has 15 protons and 16 neutrons. What is its atomic number?",
        15,
        "Atomic number is the proton count: 15.",
        "protons",
      ),
      card(
        "A neutral sulfur atom contains 16 protons. How many electrons does it have?",
        16,
        "A neutral atom has equal proton and electron counts.",
        "electrons",
      ),
    ],
  },
  {
    id: "isotopes-and-mass",
    title: "Same element, different mass",
    summary: "Distinguish mass number, isotopes and the average mass of a mixture.",
    moduleId: "chem-particles",
    sourceIds: ["chem-atom"],
    beats: [
      beat(
        "Add the nucleus",
        "Mass number A counts protons plus neutrons in one nucleus. Carbon with six protons and seven neutrons is carbon-13.",
        ["Carbon-13", atom(6, 7)],
        ["Carbon-12", atom(6, 6)],
      ),
      beat(
        "Find the missing count",
        "Subtract atomic number from mass number to find neutrons: N = A − Z. Electron loss does not change mass number.",
        ["Chlorine-35", atom(17, 18)],
        ["Chlorine-37", atom(17, 20)],
      ),
      beat(
        "Compare isotopes",
        "Isotopes share a proton count but have different neutron counts. They belong to one element, though their masses differ.",
        ["Oxygen-16", atom(8, 8)],
        ["Oxygen-18", atom(8, 10)],
      ),
      beat(
        "Average a sample",
        "An average describes many atoms. For an equal mixture with approximate masses 12 u and 14 u, the average is 13 u; no atom in that mixture needs to have mass 13 u.",
        ["Carbon-12", atom(6, 6)],
        ["Carbon-14", atom(6, 8)],
      ),
    ],
    questions: [
      n(
        "A carbon nucleus has 6 protons and 7 neutrons. What is its mass number?",
        13,
        "Mass number is 6 + 7 = 13.",
        "Add the particles in the nucleus.",
        "particles",
      ),
      n(
        "Chlorine-35 has atomic number 17. How many neutrons does it have?",
        18,
        "Subtract 17 protons from mass number 35: 18 neutrons.",
        "Use N = A − Z.",
        "neutrons",
      ),
      c(
        "Oxygen-16 and oxygen-18 are isotopes. What differs?",
        ["Their proton counts", "Their neutron counts", "Their element symbols"],
        1,
        "Both have eight protons; oxygen-18 has two more neutrons.",
        "Compare mass numbers while holding atomic number fixed.",
      ),
      n(
        "A sample has equal numbers of atoms of approximate mass 12 u and 14 u. What is its average mass in u?",
        13,
        "Equal populations give (12 + 14)/2 = 13 u.",
        "Give the two masses equal weight.",
        "u",
      ),
      n(
        "An oxygen-18 ion still has 8 protons. How many neutrons does it have?",
        10,
        "Charge does not affect mass number: 18 − 8 = 10.",
        "The ion's electron count is irrelevant here.",
        "neutrons",
      ),
      c(
        "An element's average atomic mass is 10.8 u. What does this tell you?",
        [
          "Every atom has a fractional neutron",
          "Its atoms all have mass number 11",
          "Its isotope mixture has that average mass",
        ],
        2,
        "A weighted average can be non-integer even though each nucleus has whole particles.",
        "Separate a sample average from one atom's mass number.",
      ),
    ],
    cards: [
      card(
        "Neon-22 has atomic number 10. How many neutrons are in its nucleus?",
        12,
        "22 − 10 = 12 neutrons.",
        "neutrons",
      ),
      card(
        "Use approximate isotope masses 10 u and 12 u. A sample contains 25% light and 75% heavy atoms. Find its average mass in u.",
        11.5,
        "0.25 × 10 + 0.75 × 12 = 11.5 u.",
        "u",
      ),
    ],
  },
  {
    id: "ions-and-charge",
    title: "Gaining and losing electrons",
    summary: "Calculate ion charge while keeping element identity unchanged.",
    moduleId: "chem-particles",
    sourceIds: ["chem-atom"],
    beats: [
      beat(
        "One electron short",
        "Charge in units of the elementary charge is protons minus electrons. Sodium with eleven protons and ten electrons is Na⁺.",
        ["Sodium ion", atom(11, 12, 10)],
        ["Neutral sodium", atom(11, 12, 11)],
      ),
      beat(
        "Extra negative charge",
        "An oxygen atom that gains two electrons has ten electrons against eight protons. Its charge is −2, written O²⁻.",
        ["Oxide ion", atom(8, 8, 10)],
        ["Neutral oxygen", atom(8, 8, 8)],
      ),
      beat(
        "Change the electrons",
        "Removing a negative electron makes charge more positive. Ordinary chemical ion formation does not remove protons.",
        ["Neutral magnesium", atom(12, 12, 12)],
        ["Magnesium ion", atom(12, 12, 10)],
      ),
      beat(
        "Three missing negatives",
        "Aluminium commonly forms Al³⁺ by losing three electrons. Its proton count stays thirteen and its electron count becomes ten.",
        ["Aluminium ion", atom(13, 14, 10)],
        ["Neutral aluminium", atom(13, 14, 13)],
      ),
    ],
    questions: [
      n(
        "A sodium ion has 11 protons and 10 electrons. Enter its signed charge.",
        1,
        "11 − 10 = +1.",
        "Count positive charges minus negative charges.",
        "e",
      ),
      n(
        "An oxide ion has 8 protons and 10 electrons. Enter its signed charge.",
        -2,
        "8 − 10 = −2.",
        "More electrons than protons gives negative charge.",
        "e",
      ),
      c(
        "What happens when a neutral atom loses one electron?",
        [
          "It becomes positively charged",
          "It becomes negatively charged",
          "It changes its atomic number",
        ],
        0,
        "Removing a negative charge leaves a net positive charge.",
        "The nucleus stays unchanged.",
      ),
      n(
        "An aluminium ion has 13 protons and 10 electrons. Enter its signed charge.",
        3,
        "13 − 10 = +3.",
        "Subtract electrons from protons.",
        "e",
      ),
      n(
        "A fluoride ion has 9 protons and 10 electrons. Enter its signed charge.",
        -1,
        "9 − 10 = −1.",
        "One extra electron contributes one negative charge.",
        "e",
      ),
      c(
        "Mg²⁺ and a neutral magnesium atom share what?",
        ["Their electron counts", "Their proton counts", "Their net charges"],
        1,
        "Both have twelve protons; Mg²⁺ has two fewer electrons.",
        "Identity follows the nucleus.",
      ),
    ],
    cards: [
      card(
        "An ion has 7 protons and 10 electrons. Enter its signed charge.",
        -3,
        "7 − 10 = −3.",
        "e",
      ),
      card(
        "Sulfur has atomic number 16. An ion has 18 electrons. Enter its signed charge.",
        -2,
        "16 − 18 = −2.",
        "e",
      ),
    ],
  },
];
