import {
  atom,
  beat,
  choose as c,
  card,
  ionic,
  lewis,
  numeric as n,
  type TeachingLesson,
} from "./definition.js";
export const bonds: TeachingLesson[] = [
  {
    id: "outer-electrons",
    title: "The outer electrons",
    summary:
      "Read shell populations for the first eighteen elements and identify valence electrons.",
    moduleId: "chem-bonds",
    sourceIds: ["chem-shells"],
    beats: [
      beat(
        "Look outside",
        "For neutral ground-state atoms up to argon, group electrons as 2 in the first shell, then up to 8 in the second and up to 8 in the third. Oxygen's eight electrons group as 2, 6.",
        ["Oxygen", atom(8, 8)],
        ["Carbon", atom(6, 6)],
      ),
      beat(
        "Fill a shell",
        "Neon has ten electrons: two inner and eight outer. The outer electrons are called valence electrons; their arrangement helps explain chemical behaviour.",
        ["Neon", atom(10, 10)],
        ["Fluorine", atom(9, 10)],
      ),
      beat(
        "Start another shell",
        "Sodium has eleven electrons: 2, 8, 1. Its single outer electron occupies a new shell. The circles group counts; electrons do not travel along these drawn tracks.",
        ["Sodium", atom(11, 12)],
        ["Lithium", atom(3, 4)],
      ),
      beat(
        "Keep the first exception",
        "Helium's first shell is full with two electrons. A full outer shell does not always mean eight, and larger atoms require a more detailed orbital model.",
        ["Helium", atom(2, 2)],
        ["Argon", atom(18, 22)],
      ),
    ],
    questions: [
      n(
        "Neutral oxygen has 8 electrons. With 2 in its first shell, how many are in its outer shell?",
        6,
        "8 − 2 = 6 outer electrons.",
        "Remove the filled first shell from the total.",
        "electrons",
      ),
      n(
        "Neutral neon has 10 electrons. How many valence electrons does it have?",
        8,
        "Its shell counts are 2, 8.",
        "Identify the outermost occupied shell.",
        "electrons",
      ),
      c(
        "Lithium has shell counts 2, 1 and sodium has 2, 8, 1. What matches?",
        [
          "Their number of occupied shells",
          "Their number of valence electrons",
          "Their atomic numbers",
        ],
        1,
        "Each has one electron in its outermost shell.",
        "Compare the last occupied shell.",
      ),
      n(
        "How many electrons fill helium's only shell?",
        2,
        "The first shell is full with two electrons.",
        "Helium occupies the first shell only.",
        "electrons",
      ),
      n(
        "Neutral aluminium has 13 electrons arranged 2, 8, 3. How many are valence electrons?",
        3,
        "The outermost occupied shell contains three.",
        "Use the final occupied group.",
        "electrons",
      ),
      c(
        "What do the circles in this atom drawing represent?",
        [
          "Measured circular electron paths",
          "Groups of electrons by shell",
          "The surfaces of solid atoms",
        ],
        1,
        "They group electrons for counting; actual electrons occupy quantum states.",
        "Use the drawing as a model of shell populations.",
      ),
    ],
    cards: [
      card(
        "Phosphorus has ground-state shell populations 2, 8, 5. How many valence electrons does it have?",
        5,
        "The last occupied shell contains five.",
        "electrons",
      ),
      card(
        "Neutral chlorine has 17 electrons. For this small atom, group them as 2, 8, then the remainder. How many are outer electrons?",
        7,
        "17 − 2 − 8 = 7.",
        "electrons",
      ),
    ],
  },
  {
    id: "neutral-ionic-formulas",
    title: "Making a neutral formula",
    summary: "Find whole-number ion ratios that balance electric charge.",
    moduleId: "chem-bonds",
    sourceIds: ["chem-ionic", "chem-compounds"],
    beats: [
      beat(
        "Cancel the charge",
        "One Mg²⁺ needs two Cl⁻ ions to balance charge: +2 − 1 − 1 = 0. The simplest neutral ratio gives MgCl₂.",
        ["Magnesium chloride", ionic("Mg", "Cl", 1, 2)],
        ["One chloride", ionic("Mg", "Cl", 1, 1)],
      ),
      beat(
        "Meet at six",
        "Two Al³⁺ ions supply +6 and three O²⁻ ions supply −6. This gives the formula Al₂O₃. Each subscript counts ions in the simplest ratio.",
        ["Aluminium oxide", ionic("Al", "O", 2, 3)],
        ["One of each", ionic("Al", "O", 1, 1)],
      ),
      beat(
        "Think lattice",
        "An ionic crystal extends through many ions. Its formula unit gives a ratio, not a separate molecule floating inside the solid.",
        ["Sodium chloride", ionic("Na", "Cl", 1, 1)],
        ["Double the ratio", ionic("Na", "Cl", 2, 2)],
      ),
      beat(
        "Reduce the ratio",
        "Mg²⁺ and O²⁻ cancel in a one-to-one ratio, so write MgO. Two of each also balance, but Mg₂O₂ is not the simplest formula unit.",
        ["Magnesium oxide", ionic("Mg", "O", 1, 1)],
        ["Two of each", ionic("Mg", "O", 2, 2)],
      ),
    ],
    questions: [
      n(
        "How many Cl⁻ ions balance one Mg²⁺ ion?",
        2,
        "Two charges of −1 balance +2.",
        "Make the total charge zero.",
        "ions",
      ),
      n(
        "In Al₂O₃, how many Al³⁺ ions accompany three O²⁻ ions?",
        2,
        "Three oxide ions total −6; two aluminium ions total +6.",
        "Find the positive count needed to reach +6.",
        "ions",
      ),
      c(
        "What does NaCl describe in a sodium chloride crystal?",
        [
          "A separate two-atom molecule",
          "A one-to-one ion ratio",
          "Two neutral atoms with no attraction",
        ],
        1,
        "NaCl records the simplest ratio of sodium and chloride ions in a lattice.",
        "Distinguish a formula unit from a molecular structure.",
      ),
      n(
        "In the simplest formula MgO, how many oxide ions accompany one magnesium ion?",
        1,
        "+2 and −2 cancel one to one.",
        "Compare the sizes of the opposite charges.",
        "ions",
      ),
      n(
        "Calcium forms Ca²⁺. How many Cl⁻ ions are needed per calcium ion?",
        2,
        "Two chloride ions supply a total of −2.",
        "Balance charge using whole ions.",
        "ions",
      ),
      c(
        "Why does aluminium oxide use the ratio Al₂O₃?",
        [
          "It makes the total charge zero",
          "Every ion must have three neighbours",
          "Oxygen changes to a positive ion",
        ],
        0,
        "Two +3 charges balance three −2 charges.",
        "Count net charge rather than guessed neighbours.",
      ),
    ],
    cards: [
      card(
        "Na⁺ and O²⁻ form a neutral solid. How many sodium ions are needed per oxide ion?",
        2,
        "Two +1 charges balance −2.",
        "ions",
      ),
      card(
        "Al³⁺ and Cl⁻ form a neutral solid. How many chloride ions are needed per aluminium ion?",
        3,
        "Three −1 charges balance +3.",
        "ions",
      ),
    ],
  },
  {
    id: "sharing-electron-pairs",
    title: "Sharing electron pairs",
    summary:
      "Read single, double and triple bonds and distinguish shared electrons from lone pairs.",
    moduleId: "chem-bonds",
    sourceIds: ["chem-lewis", "chem-covalent"],
    beats: [
      beat(
        "Share a pair",
        "A single covalent bond represents two shared electrons. In H₂, both hydrogen atoms count that pair toward a filled first shell.",
        ["Hydrogen", lewis("H2")],
        ["Water", lewis("H2O")],
      ),
      beat(
        "Use two pairs",
        "A double bond contains two shared pairs: four electrons. In a Lewis structure, O₂ has a double bond and two lone pairs on each oxygen.",
        ["Oxygen", lewis("O2")],
        ["Hydrogen", lewis("H2")],
      ),
      beat(
        "Count shared electrons once",
        "The same bonding pair contributes to each bonded atom's shell count. It remains two electrons in the molecule; counting it for both atoms does not create four.",
        ["Water", lewis("H2O")],
        ["Ammonia", lewis("NH3")],
      ),
      beat(
        "Three lines",
        "A triple bond contains three shared pairs, or six electrons. N₂ also has one lone pair on each nitrogen. Lewis drawings show electron bookkeeping, not a complete three-dimensional shape.",
        ["Nitrogen", lewis("N2")],
        ["Methane", lewis("CH4")],
      ),
    ],
    questions: [
      n(
        "How many electrons are shared in the single bond of H₂?",
        2,
        "One bonding pair contains two electrons.",
        "Count two electrons per shared pair.",
        "electrons",
      ),
      n(
        "How many electrons are shared in the double bond of O₂?",
        4,
        "Two pairs contain four shared electrons.",
        "Each bond line represents one pair.",
        "electrons",
      ),
      c(
        "How does a shared pair contribute to the two bonded atoms?",
        [
          "Each atom counts the pair toward its shell",
          "Each atom receives two new extra electrons",
          "Only the heavier atom counts the pair",
        ],
        0,
        "A shared pair counts toward both shells while remaining one pair in the molecule.",
        "Keep shell counting separate from the total electron count.",
      ),
      n(
        "How many electrons are shared in the triple bond of N₂?",
        6,
        "Three shared pairs contain six electrons.",
        "Multiply the number of lines by two.",
        "electrons",
      ),
      n(
        "NH₃ has one lone pair on nitrogen. How many nonbonding electrons is that?",
        2,
        "A lone pair contains two electrons.",
        "A lone pair is not a bond line.",
        "electrons",
      ),
      c(
        "Methane is drawn with four bonds on a flat screen. What can you infer from this Lewis drawing?",
        [
          "Its atoms must all lie in one plane",
          "It has four single C–H bonds",
          "Its bond angles must be 90 degrees",
        ],
        1,
        "The diagram records four single bonds; it does not specify the real tetrahedral geometry.",
        "Read bond connections without treating screen angles as measurements.",
      ),
    ],
    cards: [
      card(
        "Water has two single O–H bonds. How many electrons are shared in these bonds altogether?",
        4,
        "Two pairs give four shared electrons.",
        "electrons",
      ),
      card(
        "Methane has four single C–H bonds. How many electrons are shared in its bonds altogether?",
        8,
        "Four shared pairs give eight electrons.",
        "electrons",
      ),
    ],
  },
];
