import {
  batch,
  beat,
  choose as c,
  card,
  numeric as n,
  reaction,
  type TeachingLesson,
} from "./definition.js";
export const reactionLessons: TeachingLesson[] = [
  {
    id: "balancing-reactions",
    title: "Keep every atom",
    summary: "Balance reactions by changing coefficients while preserving chemical formulas.",
    moduleId: "chem-reactions",
    sourceIds: ["chem-balance"],
    beats: [
      beat(
        "Match each element",
        "A balanced chemical equation has the same count of each element on both sides. In 2 H₂ + O₂ → 2 H₂O, four H atoms and two O atoms are conserved.",
        ["Water trial", reaction("water", [2, 2, 2])],
        ["Magnesium trial", reaction("magnesium", [2, 2, 2])],
      ),
      beat(
        "Check all the oxygen",
        "For CH₄ + 2 O₂ → CO₂ + 2 H₂O, count oxygen in both products: two atoms in CO₂ and two more in the waters.",
        ["Methane trial", reaction("methane", [1, 1, 1, 2])],
        ["Water trial", reaction("water", [1, 1, 1])],
      ),
      beat(
        "Leave formulas alone",
        "A coefficient changes the number of molecules or formula units. Changing H₂O to H₂O₂ would replace water with a different substance, not balance the same reaction.",
        ["One water unit", reaction("water", [2, 1, 1])],
        ["Two water units", reaction("water", [2, 1, 2])],
      ),
      beat(
        "Match hydrogen last",
        "N₂ + 3 H₂ → 2 NH₃ has two N atoms and six H atoms on each side. Balanced coefficients can be multiplied together, but the simplest whole-number ratio is usually used.",
        ["Ammonia trial", reaction("ammonia", [1, 1, 2])],
        ["Double reaction", reaction("ammonia", [2, 6, 4])],
      ),
    ],
    questions: [
      n(
        "Balance 2 H₂ + ? O₂ → 2 H₂O. What coefficient belongs before O₂?",
        1,
        "Two waters contain two O atoms, supplied by one O₂.",
        "Count oxygen atoms on both sides.",
        "",
      ),
      n(
        "Balance CH₄ + ? O₂ → CO₂ + 2 H₂O. What coefficient belongs before O₂?",
        2,
        "The products contain four O atoms, so two O₂ molecules are needed.",
        "Include the oxygen inside water.",
        "",
      ),
      c(
        "What may you change while balancing a fixed chemical reaction?",
        [
          "The coefficients multiplying formulas",
          "The subscripts inside the formulas",
          "The identity of an element",
        ],
        0,
        "Coefficients adjust quantities without changing substances.",
        "Preserve every substance's formula.",
      ),
      n(
        "Balance N₂ + ? H₂ → 2 NH₃. What coefficient belongs before H₂?",
        3,
        "Two NH₃ molecules contain six H atoms, supplied by three H₂.",
        "Each H₂ provides two hydrogen atoms.",
        "",
      ),
      n(
        "Balance 2 Mg + O₂ → ? MgO. What coefficient belongs before MgO?",
        2,
        "Two MgO formula units preserve both Mg atoms and both O atoms.",
        "Count each element separately.",
        "",
      ),
      c(
        "What must a balanced equation conserve?",
        [
          "The number of molecules on each side",
          "The count of each element's atoms",
          "The volume of every gas separately",
        ],
        1,
        "Atoms rearrange; the number of molecules may change.",
        "Compare element counts rather than total molecules.",
      ),
    ],
    cards: [
      card(
        "Balance ? H₂ + 3 O₂ → 6 H₂O. Find the H₂ coefficient.",
        6,
        "Six waters contain twelve H atoms, requiring six H₂.",
        "",
      ),
      card(
        "Balance 3 CH₄ + ? O₂ → 3 CO₂ + 6 H₂O. Find the O₂ coefficient.",
        6,
        "Products contain 6 + 6 = 12 O atoms, requiring six O₂.",
        "",
      ),
    ],
  },
  {
    id: "reaction-mole-ratios",
    title: "Read a reaction as a ratio",
    summary: "Use balanced coefficients to convert between reacting and produced amounts.",
    moduleId: "chem-reactions",
    sourceIds: ["chem-ratios"],
    beats: [
      beat(
        "Scale the recipe",
        "N₂ + 3 H₂ → 2 NH₃ means one mole of nitrogen requires three moles of hydrogen and can form two moles of ammonia. Scale all amounts together.",
        ["Two nitrogen batches", batch("ammonia", 2, 6)],
        ["One nitrogen batch", batch("ammonia", 1, 3)],
      ),
      beat(
        "Follow the ratio",
        "The equation 2 H₂ + O₂ → 2 H₂O gives a 1:2 ratio between oxygen and water. With enough hydrogen, each mole of O₂ can produce two moles of water.",
        ["Three oxygen batches", batch("water", 6, 3)],
        ["Two oxygen batches", batch("water", 4, 2)],
      ),
      beat(
        "Keep the units",
        "Equation coefficients give particle and mole ratios. They do not generally give mass ratios, because substances have different molar masses.",
        ["Methane ratio", reaction("methane", [1, 2, 1, 2])],
        ["Ammonia ratio", reaction("ammonia", [1, 3, 2])],
      ),
      beat(
        "Read the direction",
        "CH₄ + 2 O₂ → CO₂ + 2 H₂O needs two moles of oxygen per mole of methane. The conversion factor depends on which substance you start with and which you want.",
        ["Two methane batches", batch("methane", 2, 4)],
        ["Three methane batches", batch("methane", 3, 6)],
      ),
    ],
    questions: [
      n(
        "For N₂ + 3 H₂ → 2 NH₃, how many moles of NH₃ can 2 mol N₂ form with excess H₂?",
        4,
        "2 mol N₂ × (2 mol NH₃ / 1 mol N₂) = 4 mol.",
        "Use the ammonia-to-nitrogen coefficient ratio.",
        "mol",
      ),
      n(
        "For 2 H₂ + O₂ → 2 H₂O, how many moles of water can 3 mol O₂ form with excess H₂?",
        6,
        "The water-to-oxygen ratio is 2:1, giving 6 mol.",
        "Each mole of oxygen supports two moles of water.",
        "mol",
      ),
      c(
        "The coefficients 1:3:2 in N₂ + 3 H₂ → 2 NH₃ directly give which ratio?",
        ["Grams of the three substances", "Moles of the three substances", "Their temperatures"],
        1,
        "Coefficients count entities and amounts in moles; masses require molar masses.",
        "Keep the amount unit attached to the ratio.",
      ),
      n(
        "For CH₄ + 2 O₂ → CO₂ + 2 H₂O, how many moles of O₂ are required by 2 mol CH₄?",
        4,
        "2 × 2 = 4 mol O₂.",
        "Read oxygen required per methane consumed.",
        "mol",
      ),
      n(
        "For 2 Mg + O₂ → 2 MgO, how many moles of MgO can 4 mol Mg form with excess oxygen?",
        4,
        "The Mg-to-MgO ratio is 2:2, or 1:1.",
        "Reduce the product-to-reactant coefficient ratio.",
        "mol",
      ),
      c(
        "A stoichiometric calculation predicts 10 mol of product. When is this theoretical amount reached?",
        [
          "Whenever the drawing is balanced",
          "When the stated reaction completes without competing losses",
          "Only if all coefficients equal one",
        ],
        1,
        "The theoretical amount assumes the limiting reactant follows the stated reaction completely.",
        "Separate a theoretical calculation from actual reaction yield.",
      ),
    ],
    cards: [
      card(
        "For N₂ + 3 H₂ → 2 NH₃, find the moles of NH₃ from 6 mol H₂ with excess N₂.",
        4,
        "6 × 2/3 = 4 mol NH₃.",
        "mol",
      ),
      card(
        "For 2 H₂ + O₂ → 2 H₂O, find the moles of O₂ needed by 8 mol H₂.",
        4,
        "8 × 1/2 = 4 mol O₂.",
        "mol",
      ),
    ],
  },
  {
    id: "the-reactant-that-runs-out",
    title: "The reactant that runs out",
    summary:
      "Find theoretical products and leftovers by comparing available amounts with the reaction ratio.",
    moduleId: "chem-reactions",
    sourceIds: ["chem-yields"],
    beats: [
      beat(
        "Find the smaller batch count",
        "For 2 H₂ + O₂ → 2 H₂O, six moles of H₂ could support three batches, but one mole of O₂ supports only one. Oxygen limits the product to two moles of water.",
        ["Oxygen runs out", batch("water", 6, 1)],
        ["Hydrogen runs out", batch("water", 2, 4)],
      ),
      beat(
        "Compare after dividing",
        "For N₂ + 3 H₂ → 2 NH₃, divide each supply by its coefficient. Four moles of N₂ support four batches; three moles of H₂ support one. Hydrogen runs out first.",
        ["Hydrogen limits", batch("ammonia", 4, 3)],
        ["Nitrogen limits", batch("ammonia", 1, 9)],
      ),
      beat(
        "Keep the leftovers",
        "An excess reactant is not all consumed. In the water case with 6 mol H₂ and 1 mol O₂, forming 2 mol H₂O consumes 2 mol H₂ and leaves 4 mol H₂.",
        ["Excess hydrogen", batch("water", 6, 1)],
        ["Exact ratio", batch("water", 6, 3)],
      ),
      beat(
        "Transfer the method",
        "With 3 mol CH₄ and 4 mol O₂, CH₄ + 2 O₂ → CO₂ + 2 H₂O can proceed through two molar batches. It forms 2 mol CO₂ and 4 mol H₂O, leaving 1 mol CH₄.",
        ["Methane left over", batch("methane", 3, 4)],
        ["Oxygen left over", batch("methane", 1, 6)],
      ),
    ],
    questions: [
      n(
        "For 2 H₂ + O₂ → 2 H₂O, start with 6 mol H₂ and 1 mol O₂. What is the theoretical water yield in mol?",
        2,
        "O₂ supports one batch, producing 2 mol H₂O.",
        "Divide each available amount by its coefficient, then choose the smaller result.",
        "mol",
      ),
      n(
        "For N₂ + 3 H₂ → 2 NH₃, start with 4 mol N₂ and 3 mol H₂. Find the theoretical NH₃ yield in mol.",
        2,
        "Hydrogen supports one batch, producing 2 mol NH₃.",
        "Nitrogen alone could react farther, but hydrogen cannot.",
        "mol",
      ),
      c(
        "How do you identify a limiting reactant from given molar amounts?",
        [
          "Choose the smaller coefficient",
          "Choose the smaller amount divided by its coefficient",
          "Choose the heavier molecule",
        ],
        1,
        "Available amount divided by coefficient measures how far each supply lets the reaction proceed.",
        "Compare both supplies on the same reaction scale.",
      ),
      n(
        "For CH₄ + 2 O₂ → CO₂ + 2 H₂O, start with 3 mol CH₄ and 4 mol O₂. Find the theoretical water yield in mol.",
        4,
        "Oxygen supports two batches, each producing 2 mol water: 4 mol.",
        "Use two oxygen moles for each reaction batch.",
        "mol",
      ),
      n(
        "For 2 H₂ + O₂ → 2 H₂O, start with 6 mol H₂ and 1 mol O₂. How many moles of H₂ remain after complete reaction?",
        4,
        "One mole O₂ consumes two moles H₂, leaving 6 − 2 = 4 mol.",
        "Subtract the reacted amount from the supply.",
        "mol",
      ),
      c(
        "If reactants are supplied in the exact balanced ratio and react completely, what remains?",
        [
          "A fixed half of each reactant",
          "No excess reactant",
          "The reactant with the larger molar mass",
        ],
        1,
        "Both supplies are consumed together in the required ratio.",
        "Compare available amount divided by coefficient for both reactants.",
      ),
    ],
    cards: [
      card(
        "For 2 Mg + O₂ → 2 MgO, start with 5 mol Mg and 1 mol O₂. Find the theoretical MgO yield in mol.",
        2,
        "Oxygen supports one batch, producing 2 mol MgO.",
        "mol",
      ),
      card(
        "For N₂ + 3 H₂ → 2 NH₃, start with 2 mol N₂ and 9 mol H₂. How many moles of H₂ remain?",
        3,
        "Two mol N₂ consume six mol H₂, leaving 3 mol.",
        "mol",
      ),
    ],
  },
];
