import { chromium } from "@playwright/test";
const [url, out, w, h] = process.argv.slice(2);
const b = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const ctx = await b.newContext({ viewport: { width: Number(w||1440), height: Number(h||900) }, reducedMotion: "reduce" });
const p = await ctx.newPage();
await p.addInitScript(() => sessionStorage.setItem("discere:welcomed", "1"));
await p.goto(url); await p.waitForTimeout(2500);
await p.screenshot({ path: out });
const r = await p.locator(".home-resume").boundingBox().catch(() => null);
console.log("resume", JSON.stringify(r));
console.log(JSON.stringify(await p.evaluate(() => [...document.querySelectorAll("main > *, main section, .home-hero, .home-game")].slice(0,20).map(e => e.tagName + "." + e.className + " " + Math.round(e.getBoundingClientRect().top) + "+" + Math.round(e.getBoundingClientRect().height)))));
await b.close();
