import {
  freefall,
  motion,
  change,
  beat,
  numeric,
  choose,
  card,
  type TeachingLesson,
} from "./definition.js";
export const changeLessons: TeachingLesson[] = [
  {
    id: "changing-velocity",
    title: "Changing velocity",
    summary: "Read acceleration as a signed change in velocity per second.",
    moduleId: "phys-change",
    sourceIds: ["phys-acceleration", "phys-graphs"],
    beats: [
      beat(
        "Change per second",
        "Acceleration describes how quickly velocity changes. Going from 2 m/s to 10 m/s in 4 s gives (10 − 2)/4 = 2 m/s². With constant acceleration, equal time intervals add equal changes in velocity.",
        ["Gain velocity", change(2, 10, 4)],
        ["Gain it faster", change(2, 10, 2)],
      ),
      beat(
        "A positive acceleration can slow you",
        "Signs describe directions. A leftward cart changing from −8 m/s to −2 m/s has positive acceleration because its velocity increases. Its speed falls from 8 m/s to 2 m/s.",
        ["Left, slowing", change(-8, -2, 3)],
        ["Right, speeding up", change(2, 8, 3)],
      ),
      beat(
        "Compare velocity and acceleration",
        "When velocity and acceleration point in the same direction, speed increases. A cart already moving left speeds up under a leftward acceleration. A minus sign by itself does not mean slowing down.",
        ["Left, speeding up", change(-2, -8, 3)],
        ["Left, slowing", change(-8, -2, 3)],
      ),
      beat(
        "Constant velocity",
        "A horizontal velocity–time graph has zero slope. Its acceleration is zero, although the cart can still move. Position continues to change while a nonzero velocity stays constant.",
        ["Keep 6 m/s", change(6, 6, 4)],
        ["Change to 10 m/s", change(6, 10, 4)],
      ),
    ],
    questions: [
      numeric(
        "A cart changes velocity from 2 m/s to 10 m/s in 4 s. Find its average acceleration in m/s².",
        2,
        "Acceleration = (10 − 2)/4 = 2 m/s².",
        [
          "Find the signed change in velocity.",
          "Divide that change by the elapsed time.",
          "Subtract initial from final velocity, then divide by duration.",
        ],
        "m/s²",
      ),
      numeric(
        "Velocity changes from −8 m/s to −2 m/s over 3 s. What is the average acceleration in m/s²?",
        2,
        "The velocity change is −2 − (−8) = +6 m/s. Dividing by 3 s gives +2 m/s².",
        [
          "Subtract the initial negative velocity carefully.",
          "The velocity moves toward zero.",
          "Calculate (−2 − (−8))/3.",
        ],
        "m/s²",
      ),
      choose(
        "A cart has negative velocity and negative acceleration. What happens to its speed while those signs remain?",
        ["Its speed increases", "Its speed decreases", "Its speed must be zero"],
        0,
        "Velocity and acceleration both point left, so the magnitude of velocity increases.",
        "Compare the directions, rather than interpreting a minus sign as braking.",
      ),
      numeric(
        "A cart keeps a velocity of 6 m/s for 4 s. Find its average acceleration in m/s².",
        0,
        "There is no velocity change: (6 − 6)/4 = 0 m/s².",
        [
          "Acceleration depends on a change in velocity.",
          "Compare the initial and final velocities.",
          "Calculate (6 − 6)/4.",
        ],
        "m/s²",
      ),
      numeric(
        "A robot's velocity changes from 9 m/s to −3 m/s in 4 s. Find its average acceleration in m/s².",
        -3,
        "The change is −3 − 9 = −12 m/s. Acceleration is −12/4 = −3 m/s².",
        [
          "The final velocity points opposite to the initial velocity.",
          "Keep signs when subtracting.",
          "Divide the negative velocity change by elapsed time.",
        ],
        "m/s²",
      ),
      choose(
        "A velocity–time line crosses zero with a nonzero slope. At that instant, which description is possible?",
        [
          "Zero velocity with nonzero acceleration",
          "Zero velocity must mean zero acceleration",
          "Acceleration changes instantly to zero",
        ],
        0,
        "The graph's value is zero at the crossing, while its slope remains nonzero.",
        "Velocity is the graph's height; acceleration is its slope.",
      ),
    ],
    cards: [
      card(
        "Velocity changes from 4 m/s to 16 m/s over 6 s. Find the average acceleration in m/s².",
        2,
        "(16 − 4)/6 = 2 m/s².",
        "m/s²",
      ),
      card(
        "Velocity changes from −12 m/s to −3 m/s in 3 s. Find the average acceleration in m/s².",
        3,
        "(−3 − (−12))/3 = +3 m/s².",
        "m/s²",
      ),
    ],
  },
  {
    id: "predicting-a-motion",
    title: "Predict the next position",
    summary: "Use a constant acceleration to predict velocity and displacement.",
    moduleId: "phys-change",
    sourceIds: ["phys-kinematics", "phys-graphs"],
    beats: [
      beat(
        "Add the velocity change",
        "For constant acceleration, final velocity is initial velocity plus acceleration times elapsed time: v = u + at. Starting at 3 m/s and adding 2 m/s each second gives 11 m/s after 4 s.",
        ["Acceleration 2", motion(3, 2, 4)],
        ["Acceleration 1", motion(3, 1, 4)],
      ),
      beat(
        "The area under velocity",
        "With constant acceleration, average velocity is halfway between the initial and final velocities. Multiply that average by time to find displacement. The same result follows from displacement = ut + ½at².",
        ["Changing velocity", motion(3, 2, 4, 0, "horizontal", "velocity_graph")],
        ["Steady velocity", motion(7, 0, 4, 0, "horizontal", "velocity_graph")],
      ),
      beat(
        "Twice the time",
        "Starting from rest with constant acceleration gives displacement = ½at². Doubling the duration multiplies displacement by four. The object covers more ground each second as it picks up speed.",
        ["2 seconds", motion(0, 2, 2)],
        ["4 seconds", motion(0, 2, 4)],
      ),
      beat(
        "Predict a stop",
        "A cart starting at 12 m/s with acceleration −3 m/s² reaches zero velocity after 4 s. During that interval its average velocity is 6 m/s, so its stopping distance is 24 m. End the braking model at the stop.",
        ["Gentler braking", motion(12, -3, 4)],
        ["Stronger braking", motion(12, -6, 2)],
      ),
    ],
    questions: [
      numeric(
        "A cart starts at 3 m/s and has constant acceleration 2 m/s² for 4 s. Find its final velocity in m/s.",
        11,
        "v = 3 + 2 × 4 = 11 m/s.",
        [
          "Find the velocity added during the interval.",
          "Multiply acceleration by time, then add the initial velocity.",
          "Calculate 3 + 2 × 4.",
        ],
        "m/s",
      ),
      numeric(
        "Starting at 3 m/s, a cart accelerates at 2 m/s² for 4 s. What is its displacement in metres?",
        28,
        "Displacement = 3 × 4 + ½ × 2 × 4² = 12 + 16 = 28 m.",
        [
          "Account for both the initial motion and the added velocity.",
          "Use ut + ½at² for constant acceleration.",
          "Calculate 3 × 4 + 0.5 × 2 × 16.",
        ],
        "m",
      ),
      choose(
        "An object starts from rest with constant nonzero acceleration. Doubling the travel time multiplies its displacement by what factor?",
        ["2", "4", "8"],
        1,
        "Displacement is proportional to time squared; doubling time gives a factor of 2² = 4.",
        "Track the exponent on time in ½at².",
      ),
      numeric(
        "A cart brakes uniformly from 12 m/s to rest in 4 s. Find its stopping distance in metres.",
        24,
        "Average velocity is (12 + 0)/2 = 6 m/s. Displacement is 6 × 4 = 24 m.",
        [
          "Uniform braking makes the velocity change linearly.",
          "Average the initial and final velocities.",
          "Multiply (12 + 0)/2 by 4.",
        ],
        "m",
      ),
      numeric(
        "A robot begins at x = 5 m with velocity 2 m/s and constant acceleration 1 m/s². Find its position after 4 s, in metres.",
        21,
        "x = 5 + 2 × 4 + ½ × 1 × 4² = 21 m.",
        [
          "First find displacement, then add the initial position.",
          "Use x = x₀ + ut + ½at².",
          "Calculate 5 + 8 + 8.",
        ],
        "m",
      ),
      choose(
        "When is displacement = ut + ½at² valid for the whole interval?",
        [
          "When acceleration is constant over the interval",
          "Whenever initial velocity is zero",
          "Whenever the object moves right",
        ],
        0,
        "This expression assumes constant acceleration during the interval; direction alone is not enough.",
        "Identify the assumption used to combine the velocity changes.",
      ),
    ],
    cards: [
      card(
        "An object starts from rest with constant acceleration 3 m/s² for 4 s. Find its displacement in metres.",
        24,
        "½ × 3 × 4² = 24 m.",
        "m",
      ),
      card(
        "A cart starts at 14 m/s and accelerates at −2 m/s² for 5 s. Find its final velocity in m/s.",
        4,
        "14 − 2 × 5 = 4 m/s.",
        "m/s",
      ),
    ],
  },
  {
    id: "falling-and-rising",
    title: "Falling and rising",
    summary: "Apply constant downward acceleration to free fall and an upward throw.",
    moduleId: "phys-change",
    sourceIds: ["phys-fall", "phys-kinematics"],
    beats: [
      beat(
        "Choose upward as positive",
        "In this model, gravitational acceleration is 10 m/s² downward and air resistance is absent. With upward positive, acceleration is −10 m/s². A released ball gains downward velocity even though it starts at rest.",
        ["Release from 45 m", motion(0, -10, 3, 45, "vertical")],
        ["Release from 20 m", motion(0, -10, 2, 20, "vertical")],
      ),
      beat(
        "Height is a position",
        "A falling object's displacement is negative when upward is positive. Add that signed displacement to its initial height. From 45 m, falling for 2 s changes height by −20 m, leaving a height of 25 m.",
        ["Start at 45 m", motion(0, -10, 2, 45, "vertical")],
        ["Start at 30 m", motion(0, -10, 2, 30, "vertical")],
      ),
      beat(
        "At the top",
        "An upward throw has positive initial velocity and negative acceleration. At its highest point, velocity is momentarily zero. Gravity still acts downward, so acceleration is not zero and the ball begins to descend.",
        ["Launch at 20 m/s", motion(20, -10, 4, 0, "vertical")],
        ["Launch at 10 m/s", motion(10, -10, 2, 0, "vertical")],
      ),
      beat(
        "What the model leaves out",
        "Free fall here means gravity acts without air resistance. At the same location, objects released together from the same height share the same gravitational acceleration, regardless of mass. Shape-dependent drag would require a different model.",
        ["1 kg ball", freefall(1, 20)],
        ["5 kg ball", freefall(5, 20)],
      ),
    ],
    questions: [
      numeric(
        "A ball is released from rest. Take upward as positive and g = 10 m/s², with no air resistance. Find its velocity after 2 s, in m/s.",
        -20,
        "v = 0 + (−10) × 2 = −20 m/s.",
        [
          "Gravity points opposite to the positive direction.",
          "Use negative acceleration in v = u + at.",
          "Calculate 0 − 10 × 2.",
        ],
        "m/s",
      ),
      numeric(
        "A ball is released from height 45 m. With g = 10 m/s² and no air resistance, what is its height after 2 s, in metres?",
        25,
        "Height = 45 − ½ × 10 × 2² = 45 − 20 = 25 m.",
        [
          "Find the downward displacement from rest.",
          "Subtract ½gt² from the starting height.",
          "Calculate 45 − 0.5 × 10 × 4.",
        ],
        "m",
      ),
      numeric(
        "At the highest point of a vertical throw, find the acceleration in m/s². Take upward positive, g = 10 m/s² and no air resistance.",
        -10,
        "Gravity still gives acceleration −10 m/s² at the top; only the instantaneous velocity is zero.",
        [
          "Separate zero velocity from zero acceleration.",
          "Gravity continues acting throughout the flight.",
          "Use the downward value of g with upward positive.",
        ],
        "m/s²",
      ),
      choose(
        "Two objects of different mass are released together from the same height in the same gravitational field. Ignore air resistance. Which lands first?",
        ["The heavier object", "The lighter object", "They land together"],
        2,
        "The same initial velocity and gravitational acceleration give the same motion in this model.",
        "Check whether mass appears in the free-fall position equation.",
      ),
      numeric(
        "A ball is thrown upward at 30 m/s. With g = 10 m/s² and no air resistance, find its displacement after 2 s in metres.",
        40,
        "Displacement = 30 × 2 − ½ × 10 × 2² = 40 m upward.",
        [
          "Combine the initial upward motion with the downward acceleration.",
          "Use ut − ½gt².",
          "Calculate 60 − 20.",
        ],
        "m",
      ),
      choose(
        "While a freely thrown ball is moving upward, which direction does its acceleration point? Ignore air resistance.",
        [
          "Upward, because the ball is rising",
          "Downward, toward Earth",
          "It has no acceleration until it falls",
        ],
        1,
        "The gravitational acceleration points downward throughout the flight, including while velocity points upward.",
        "The direction of motion does not determine the direction of gravitational acceleration.",
      ),
    ],
    cards: [
      card(
        "A ball is released from rest with g = 10 m/s². With downward positive and no air resistance, find its velocity after 3 s in m/s.",
        30,
        "With downward positive, v = 0 + 10 × 3 = 30 m/s.",
        "m/s",
      ),
      card(
        "A ball is thrown upward at 16 m/s where g = 8 m/s². Ignore air resistance. How many seconds until its velocity first reaches zero?",
        2,
        "0 = 16 − 8t, so t = 2 s.",
        "s",
      ),
    ],
  },
];
