import type {
  CourseCheckDefinition,
  MechanicsModel,
} from "../../../packages/contracts/src/index.js";
import {
  trip,
  motion,
  change,
  forces,
  support,
  pair,
  friction,
  work,
  kinetic,
  lift,
  drop,
  power,
  impulse,
  collision,
} from "./definition.js";
import { physicsLessons } from "./lessons.js";
function item(
  id: string,
  lessonIndex: number,
  prompt: string,
  model: MechanicsModel,
  value: number,
  workedAnswer: string,
  unit: string,
): CourseCheckDefinition["items"][number] {
  const lesson = physicsLessons[lessonIndex]!;
  return {
    lessonId: lesson.id,
    visual: { type: "mechanics", model },
    question: {
      id: "phys-check-" + id,
      conceptIds: ["phys-" + lesson.id],
      sourceIds: lesson.sourceIds,
      prompt,
      responseType: "numeric",
      difficulty: 1,
      hints: [],
      answerAuthority: {
        kind: "numeric",
        value,
        unit,
        absoluteTolerance: 1e-6,
        relativeTolerance: 0,
        workedAnswer,
      },
    },
  };
}
const required = physicsLessons.map((l) => l.id);
export const physicsChecks: CourseCheckDefinition[] = [
  {
    id: "starting-point",
    kind: "placement",
    title: "Find your starting point",
    description:
      "Eighteen problems across motion, forces, energy and momentum. Find which ideas need attention.",
    requiredLessonIds: [],
    items: [
      item(
        "placement-displacement",
        0,
        "An object moves from x = −4 m to x = 7 m. Find its signed displacement in metres.",
        trip([
          [0, -4],
          [5, 7],
        ]),
        11,
        "Displacement = 7 − (−4) = 11 m.",
        "m",
      ),
      item(
        "placement-speed",
        1,
        "A cart travels 28 m right in 4 s without reversing. Find its average speed in m/s.",
        trip([
          [0, 0],
          [4, 28],
        ]),
        7,
        "Average speed = 28/4 = 7 m/s.",
        "m/s",
      ),
      item(
        "placement-graph",
        2,
        "A straight position-time segment runs from (0 s, 12 m) to (3 s, 3 m). Find the velocity in m/s, with right positive.",
        trip(
          [
            [0, 12],
            [3, 3],
          ],
          "position_graph",
        ),
        -3,
        "Slope = (3 − 12)/(3 − 0) = −3 m/s.",
        "m/s",
      ),
      item(
        "placement-acceleration",
        3,
        "Velocity changes uniformly from −10 to −2 m/s over 4 s. Find acceleration in m/s².",
        change(-10, -2, 4),
        2,
        "a = [−2 − (−10)]/4 = 2 m/s².",
        "m/s²",
      ),
      item(
        "placement-prediction",
        4,
        "A cart starts at x = 0 with velocity 2 m/s and constant acceleration 3 m/s². Find displacement after 4 s in metres.",
        motion(2, 3, 4),
        32,
        "Displacement = 2 × 4 + ½ × 3 × 4² = 32 m.",
        "m",
      ),
      item(
        "placement-fall",
        5,
        "A ball is released from height 80 m with g = 10 m/s² and no air resistance. Find its height after 3 s in metres.",
        motion(0, -10, 3, 80, "vertical"),
        35,
        "Height = 80 − ½ × 10 × 3² = 35 m.",
        "m",
      ),
      item(
        "placement-balance",
        6,
        "A cart has horizontal forces of 19 N right and 7 N left. Find the net force in newtons with right positive.",
        forces(4, 19, 7),
        12,
        "19 − 7 = 12 N.",
        "N",
      ),
      item(
        "placement-second-law",
        7,
        "A 5 kg cart has forces of 25 N right and 5 N left. Find acceleration in m/s² with right positive.",
        forces(5, 25, 5),
        4,
        "a = (25 − 5)/5 = 4 m/s².",
        "m/s²",
      ),
      item(
        "placement-support",
        8,
        "A 6 kg object rests on a support with g = 10 m/s². Only weight and support act. Find the upward support force in newtons.",
        support(6),
        60,
        "Zero acceleration requires N = mg = 6 × 10 = 60 N.",
        "N",
      ),
      item(
        "placement-pair",
        9,
        "A pushes a 4 kg cart B right with 12 N. This is B's only horizontal force. Find B's acceleration in m/s² with right positive.",
        pair(3, 4, 12),
        3,
        "a_B = 12/4 = 3 m/s².",
        "m/s²",
      ),
      item(
        "placement-friction",
        10,
        "A 5 kg box slides horizontally with μ_k = 0.2 and g = 10 m/s². There are no other vertical forces or vertical acceleration. Find sliding-friction magnitude in newtons.",
        friction(5, 20, 2, 0.5, 0.2),
        10,
        "f_k = μ_k mg = 0.2 × 5 × 10 = 10 N.",
        "N",
      ),
      item(
        "placement-work",
        11,
        "A constant 7 N force opposes a 4 m displacement. Find its signed work in joules.",
        work(7, 4, "against"),
        -28,
        "W = −7 × 4 = −28 J.",
        "J",
      ),
      item(
        "placement-kinetic",
        12,
        "A 3 kg object has speed 6 m/s. Find its kinetic energy in joules.",
        kinetic(3, 6),
        54,
        "K = ½ × 3 × 6² = 54 J.",
        "J",
      ),
      item(
        "placement-height",
        13,
        "A 4 kg object rises from 2 m to 7 m with g = 10 m/s². Find the gravitational potential-energy change in joules.",
        lift(4, 2, 7),
        200,
        "ΔU = 4 × 10 × (7 − 2) = 200 J.",
        "J",
      ),
      item(
        "placement-energy",
        14,
        "A 3 kg object starts from rest at height 6 m with g = 10 m/s². It reaches zero height, producing 30 J of heating with no other transfers. Find final kinetic energy in joules.",
        drop(3, 6, 30),
        150,
        "K_final = 3 × 10 × 6 − 30 = 150 J.",
        "J",
      ),
      item(
        "placement-efficiency",
        15,
        "A device takes 900 J input and supplies 630 J useful output over the same interval. Find efficiency as a percentage.",
        power(900, 630, 3),
        70,
        "100 × 630/900 = 70%.",
        "%",
      ),
      item(
        "placement-impulse",
        16,
        "A constant net force of +6 N acts on a cart for 4 s. Find its impulse in N·s.",
        impulse(4, 2, 6, 4),
        24,
        "J = 6 × 4 = 24 N·s.",
        "N·s",
      ),
      item(
        "placement-collision",
        17,
        "A 3 kg cart at +5 m/s hits a resting 2 kg cart and they stick. External impulse is negligible. Find shared final velocity in m/s.",
        collision(3, 2, 5, 0),
        3,
        "v = (3 × 5 + 2 × 0)/(3 + 2) = 3 m/s.",
        "m/s",
      ),
    ],
  },
  {
    id: "mixed-challenge",
    kind: "checkpoint",
    title: "Bring the ideas together",
    description:
      "Eighteen mixed problems. Choose the method and record your confidence; results appear after the final response.",
    requiredLessonIds: required,
    items: [
      item(
        "mixed-energy",
        14,
        "A 4 kg object starts at height 5 m with speed 3 m/s, where g = 10 m/s². On reaching zero height, 28 J has become heating with no other transfers. Find final kinetic energy in joules.",
        drop(4, 5, 28, 3),
        190,
        "K_initial = ½ × 4 × 3² = 18 J. K_final = 18 + 200 − 28 = 190 J.",
        "J",
      ),
      item(
        "mixed-graph",
        2,
        "Follow the position-time graph: x = 2 m at 0 s, 8 m at 2 s, 8 m at 4 s and −1 m at 7 s, with straight segments. Find total distance travelled in metres.",
        trip(
          [
            [0, 2],
            [2, 8],
            [4, 8],
            [7, -1],
          ],
          "position_graph",
        ),
        15,
        "Distance = |8 − 2| + |8 − 8| + |−1 − 8| = 6 + 0 + 9 = 15 m.",
        "m",
      ),
      item(
        "mixed-support",
        8,
        "A 5 kg object on a support accelerates downward at 2 m/s² where g = 10 m/s². Only weight and support act. Find the upward support force in newtons.",
        support(5, 10, -2),
        40,
        "Upward positive: N − 50 = 5 × (−2), so N = 40 N.",
        "N",
      ),
      item(
        "mixed-work",
        11,
        "A constant 35 N force acts perpendicular to an 8 m displacement. Find its work in joules.",
        work(35, 8, "perpendicular"),
        0,
        "The force component along displacement is zero, so W = 0 J.",
        "J",
      ),
      item(
        "mixed-velocity",
        1,
        "A cart starts at x = 3 m and ends at x = −15 m after 6 s. Find average velocity in m/s with right positive.",
        trip([
          [0, 3],
          [6, -15],
        ]),
        -3,
        "Average velocity = (−15 − 3)/6 = −3 m/s.",
        "m/s",
      ),
      item(
        "mixed-collision",
        17,
        "A 4 kg cart at +5 m/s and a 2 kg cart at −1 m/s collide and stick. External impulse is negligible. Find shared final velocity in m/s.",
        collision(4, 2, 5, -1),
        3,
        "v = [4 × 5 + 2 × (−1)]/6 = 18/6 = 3 m/s.",
        "m/s",
      ),
      item(
        "mixed-friction",
        10,
        "A resting 6 kg box has μ_s = 0.4 and g = 10 m/s² on a horizontal floor. An 18 N horizontal push leaves it at rest. Find static-friction magnitude in newtons.",
        friction(6, 18, 0, 0.4, 0.3),
        18,
        "The maximum is 0.4 × 6 × 10 = 24 N. Static friction adjusts to the smaller 18 N push.",
        "N",
      ),
      item(
        "mixed-prediction",
        4,
        "A robot starts at x = 2 m with velocity 4 m/s and constant acceleration 2 m/s². Find its position at 3 s in metres.",
        motion(4, 2, 3, 2),
        23,
        "x = 2 + 4 × 3 + ½ × 2 × 3² = 23 m.",
        "m",
      ),
      item(
        "mixed-height",
        13,
        "A 3 kg object descends from 9 m to 2 m with g = 10 m/s². Find the work done by gravity in joules.",
        lift(3, 9, 2),
        210,
        "Gravity's work = mg(h_initial − h_final) = 3 × 10 × 7 = 210 J.",
        "J",
      ),
      item(
        "mixed-pair",
        9,
        "B pushes a 4 kg cart A left with 24 N; A pushes B right. There are no other horizontal forces. Find A's acceleration in m/s² with right positive.",
        pair(4, 8, 24),
        -6,
        "a_A = −24/4 = −6 m/s².",
        "m/s²",
      ),
      item(
        "mixed-acceleration",
        3,
        "Velocity changes uniformly from +8 to −4 m/s in 6 s. Find acceleration in m/s².",
        change(8, -4, 6),
        -2,
        "a = (−4 − 8)/6 = −2 m/s².",
        "m/s²",
      ),
      item(
        "mixed-power",
        15,
        "A motor delivers 1,200 J useful output in 6 s. Find its average useful power in watts.",
        power(1600, 1200, 6),
        200,
        "P = 1,200/6 = 200 W.",
        "W",
      ),
      item(
        "mixed-distance",
        0,
        "A cart moves from x = −2 m to 9 m, then returns to 4 m. Find its total distance in metres.",
        trip([
          [0, -2],
          [4, 9],
          [6, 4],
        ]),
        16,
        "Distance = |9 − (−2)| + |4 − 9| = 11 + 5 = 16 m.",
        "m",
      ),
      item(
        "mixed-impulse",
        16,
        "A 5 kg cart initially has velocity +3 m/s. A constant net force of −10 N acts for 2 s. Find final velocity in m/s.",
        impulse(5, 3, -10, 2),
        -1,
        "Final momentum = 5 × 3 − 10 × 2 = −5 kg·m/s; v = −5/5 = −1 m/s.",
        "m/s",
      ),
      item(
        "mixed-fall",
        5,
        "A ball is thrown upward from height zero at 24 m/s where g = 8 m/s². Ignore air resistance. Find its height after 2 s in metres.",
        motion(24, -8, 2, 0, "vertical"),
        32,
        "h = 24 × 2 − ½ × 8 × 2² = 32 m.",
        "m",
      ),
      item(
        "mixed-second-law",
        7,
        "A 6 kg object has forces of 42 N right and 12 N left. Find acceleration in m/s² with right positive.",
        forces(6, 42, 12),
        5,
        "a = (42 − 12)/6 = 5 m/s².",
        "m/s²",
      ),
      item(
        "mixed-kinetic",
        12,
        "A 2 kg cart changes speed from 5 to 8 m/s. Find the net work done on it in joules.",
        kinetic(2, 5),
        39,
        "W_net = ½ × 2 × (8² − 5²) = 39 J.",
        "J",
      ),
      item(
        "mixed-balance",
        6,
        "A cart moving right has forces of 7 N right and 23 N left. Find net force in newtons with right positive.",
        forces(4, 7, 23, 10, 1),
        -16,
        "Net force = 7 − 23 = −16 N; its direction need not match current velocity.",
        "N",
      ),
    ],
  },
  {
    id: "later-applications",
    kind: "transfer",
    title: "Use it a week later",
    description:
      "Apply the ideas to eighteen new situations after a delay. Use the stated assumptions and keep track of signs and units.",
    requiredLessonIds: required,
    afterCheckId: "mixed-challenge",
    delayDays: 7,
    items: [
      item(
        "later-distance",
        0,
        "A delivery robot goes from x = 5 m to −4 m, then to 2 m. Find the total distance it travels in metres.",
        trip([
          [0, 5],
          [3, -4],
          [5, 2],
        ]),
        15,
        "Distance = 9 + 6 = 15 m, even though net displacement is −3 m.",
        "m",
      ),
      item(
        "later-speed",
        1,
        "A shuttle travels 45 m in its first 3 s and another 15 m in the next 3 s, without reversing. Find average speed over the whole trip in m/s.",
        trip([
          [0, 0],
          [3, 45],
          [6, 60],
        ]),
        10,
        "Total distance 60 m divided by total time 6 s gives 10 m/s.",
        "m/s",
      ),
      item(
        "later-graph",
        2,
        "A position sensor shows a straight line from x = −6 m at 0 s to x = 10 m at 4 s. Find the velocity in m/s.",
        trip(
          [
            [0, -6],
            [4, 10],
          ],
          "position_graph",
        ),
        4,
        "Velocity = [10 − (−6)]/4 = 4 m/s.",
        "m/s",
      ),
      item(
        "later-acceleration",
        3,
        "A lift's velocity changes uniformly from −3 m/s to +9 m/s over 4 s. Find acceleration in m/s² in the same coordinate direction.",
        change(-3, 9, 4),
        3,
        "a = [9 − (−3)]/4 = 3 m/s².",
        "m/s²",
      ),
      item(
        "later-braking",
        4,
        "A test cart brakes uniformly from 15 m/s to rest in 5 s. Find stopping distance in metres.",
        motion(15, -3, 5),
        37.5,
        "Average velocity = (15 + 0)/2 = 7.5 m/s; distance = 7.5 × 5 = 37.5 m.",
        "m",
      ),
      item(
        "later-fall",
        5,
        "A probe is released from rest at height 36 m where g = 4 m/s². With upward positive and no air resistance, find velocity after 3 s in m/s.",
        motion(0, -4, 3, 36, "vertical"),
        -12,
        "v = 0 − 4 × 3 = −12 m/s.",
        "m/s",
      ),
      item(
        "later-balance",
        6,
        "A small rover has a 16 N drive force right and a 9 N opposing force left. Find the horizontal net force in newtons with right positive.",
        forces(3, 16, 9),
        7,
        "Net force = 16 − 9 = 7 N.",
        "N",
      ),
      item(
        "later-second-law",
        7,
        "An 8 kg sled has horizontal forces of 80 N right and 24 N left. Find its acceleration in m/s² with right positive.",
        forces(8, 80, 24),
        7,
        "a = (80 − 24)/8 = 7 m/s².",
        "m/s²",
      ),
      item(
        "later-support",
        8,
        "A platform accelerates a 6 kg package upward at 3 m/s² where g = 9 m/s². Only support and weight act. Find support force in newtons.",
        support(6, 9, 3),
        72,
        "N = m(g + a) = 6 × (9 + 3) = 72 N.",
        "N",
      ),
      item(
        "later-pair",
        9,
        "Two freely sliding test carts push each other with forces of magnitude 18 N. Cart B has mass 9 kg and no other horizontal force. Find B's acceleration magnitude in m/s².",
        pair(3, 9, 18),
        2,
        "a_B = 18/9 = 2 m/s².",
        "m/s²",
      ),
      item(
        "later-friction",
        10,
        "An 8 kg sled slides on level ground with μ_k = 0.25 and g = 10 m/s². There is no vertical acceleration or other vertical force. Find sliding-friction magnitude in newtons.",
        friction(8, 0, 4, 0.4, 0.25, 10, 1),
        20,
        "f_k = 0.25 × 8 × 10 = 20 N.",
        "N",
      ),
      item(
        "later-work",
        11,
        "A cable exerts a constant 32 N force along a 2.5 m displacement. Find its work in joules.",
        work(32, 2.5),
        80,
        "W = 32 × 2.5 = 80 J.",
        "J",
      ),
      item(
        "later-kinetic",
        12,
        "A 0.5 kg ball travels at speed 12 m/s. Find its kinetic energy in joules.",
        kinetic(0.5, 12),
        36,
        "K = ½ × 0.5 × 12² = 36 J.",
        "J",
      ),
      item(
        "later-height",
        13,
        "A 2 kg package rises from 1 m to 6 m in a field with g = 8 m/s². Find its gravitational potential-energy change in joules.",
        lift(2, 1, 6, 8),
        80,
        "ΔU = 2 × 8 × (6 − 1) = 80 J.",
        "J",
      ),
      item(
        "later-energy",
        14,
        "A 2 kg cart starts from rest at height 6 m with g = 10 m/s². It reaches zero height, producing 20 J of heating with no other transfers. Find final speed in m/s.",
        drop(2, 6, 20),
        10,
        "Final K = 120 − 20 = 100 J; v = √(2 × 100/2) = 10 m/s.",
        "m/s",
      ),
      item(
        "later-output",
        15,
        "A device receives 2,400 J, delivers 1,800 J of useful energy and stores no net energy. Find the energy leaving through other outputs in joules.",
        power(2400, 1800, 9),
        600,
        "Other outputs = 2,400 − 1,800 = 600 J.",
        "J",
      ),
      item(
        "later-impulse",
        16,
        "A bumper exerts a constant net force of −12 N on a cart for 2 s. Find the impulse in N·s.",
        impulse(4, 6, -12, 2),
        -24,
        "J = −12 × 2 = −24 N·s.",
        "N·s",
      ),
      item(
        "later-collision",
        17,
        "A 5 kg cart at +4 m/s and a 3 kg cart at −4 m/s meet and stick. External impulse is negligible. Find shared final velocity in m/s.",
        collision(5, 3, 4, -4),
        1,
        "v = [5 × 4 + 3 × (−4)]/(5 + 3) = 8/8 = 1 m/s.",
        "m/s",
      ),
    ],
  },
];
