import {
  kinetic,
  lift,
  drop,
  beat,
  numeric,
  choose,
  card,
  type TeachingLesson,
} from "./definition.js";
export const energyLessons: TeachingLesson[] = [
  {
    id: "energy-of-motion",
    title: "Energy of motion",
    summary: "Use kinetic energy and net work to connect force with a change in speed.",
    moduleId: "phys-energy",
    sourceIds: ["phys-kinetic", "phys-work"],
    beats: [
      beat(
        "Energy carried by motion",
        "Kinetic energy is K = ½mv². For a 2 kg cart moving at 3 m/s, K = 9 J. The squared speed makes fast motion costly to stop: doubling speed changes energy more than doubling mass.",
        ["Speed 3 m/s", kinetic(2, 3)],
        ["Speed 6 m/s", kinetic(2, 6)],
      ),
      beat(
        "Speed is squared",
        "At fixed mass, twice the speed gives four times the kinetic energy. Compare the bars for the same cart at 3 m/s and 6 m/s. The energy grows by 2², not by 2.",
        ["Original speed", kinetic(2, 3)],
        ["Double speed", kinetic(2, 6)],
      ),
      beat(
        "Mass is a direct multiplier",
        "At fixed speed, doubling mass doubles kinetic energy. Kinetic energy is nonnegative and depends on speed; it is the same for equal speeds in opposite directions.",
        ["Mass 2 kg", kinetic(2, 4)],
        ["Mass 4 kg", kinetic(4, 4)],
      ),
      beat(
        "Net work changes kinetic energy",
        "The work-energy theorem states W_net = K_final − K_initial. Speeding a 2 kg cart from 3 m/s to 5 m/s changes its kinetic energy from 9 J to 25 J, requiring net work of 16 J.",
        ["Initial motion", kinetic(2, 3)],
        ["Final motion", kinetic(2, 5)],
      ),
    ],
    questions: [
      numeric(
        "A 2 kg cart moves at 3 m/s. Find its kinetic energy in joules.",
        9,
        "K = ½ × 2 × 3² = 9 J.",
        [
          "Kinetic energy uses speed squared.",
          "Use K = ½mv².",
          "Square the speed, multiply by mass, then take half.",
        ],
        "J",
      ),
      numeric(
        "A cart's speed doubles while its mass stays fixed. By what factor does its kinetic energy increase?",
        4,
        "The speed multiplier is squared: 2² = 4.",
        ["Keep the mass fixed.", "Compare (2v)² with v².", "Square the factor 2."],
        "",
      ),
      choose(
        "A cart's mass doubles while its speed stays fixed. What happens to its kinetic energy?",
        ["It is halved", "It doubles", "It quadruples"],
        1,
        "Mass enters K = ½mv² as a direct multiplier, so energy doubles.",
        "Separate the first power of mass from the square of speed.",
      ),
      numeric(
        "A 2 kg cart speeds up from 3 m/s to 5 m/s. Find the net work done on it in joules.",
        16,
        "W_net = ½ × 2 × (5² − 3²) = 25 − 9 = 16 J.",
        [
          "Calculate the final and initial kinetic energies.",
          "Net work equals their difference.",
          "Calculate 25 − 9.",
        ],
        "J",
      ),
      numeric(
        "A 4 kg object moves at speed 5 m/s. Find its kinetic energy in joules.",
        50,
        "K = ½ × 4 × 25 = 50 J.",
        ["Square speed before multiplying.", "Use the one-half factor.", "Calculate 0.5 × 4 × 25."],
        "J",
      ),
      choose(
        "A cart initially has 50 J of kinetic energy and comes to rest. What net work is done on it?",
        ["A gain of fifty joules", "A loss of fifty joules", "No net work"],
        1,
        "Net work is final minus initial kinetic energy: 0 − 50 = −50 J.",
        "Use the energy change, including its sign.",
      ),
    ],
    cards: [
      card(
        "A 6 kg object moves at 4 m/s. Find its kinetic energy in joules.",
        48,
        "K = ½ × 6 × 16 = 48 J.",
        "J",
      ),
      card(
        "A cart's kinetic energy rises from 18 J to 63 J. Find the net work done on it in joules.",
        45,
        "W_net = 63 − 18 = 45 J.",
        "J",
      ),
    ],
  },
  {
    id: "lifting-and-falling-energy",
    title: "Energy and height",
    summary: "Calculate gravitational potential-energy changes using a chosen height reference.",
    moduleId: "phys-energy",
    sourceIds: ["phys-potential", "phys-work"],
    beats: [
      beat(
        "A change of height",
        "Near Earth's surface, with constant g, gravitational potential-energy change is ΔU = mgΔh. Raising a 3 kg object from 1 m to 5 m where g = 10 m/s² increases this energy by 120 J.",
        ["Rise by 4 m", lift(3, 1, 5)],
        ["Rise by 2 m", lift(3, 1, 3)],
      ),
      beat(
        "Choose a reference",
        "A height reference sets where U = 0. Shifting the reference changes the heights assigned to both endpoints but leaves their difference unchanged. The same physical rise has the same potential-energy change.",
        ["Heights 1 m to 5 m", lift(3, 1, 5)],
        ["Heights 3 m to 7 m", lift(3, 3, 7)],
      ),
      beat(
        "A descent has a negative change",
        "Falling lowers gravitational potential energy. For mass 2 kg and g = 10 m/s², moving from 8 m to 3 m gives Δh = −5 m and ΔU = −100 J. The lost potential energy can become motion or heating.",
        ["Descend 5 m", lift(2, 8, 3)],
        ["Rise 5 m", lift(2, 3, 8)],
      ),
      beat(
        "Gravity does the opposite work",
        "Work done by gravity is −ΔU. When a 2 kg object descends from 8 m to 3 m with g = 10 m/s², gravity does +100 J of work. A slow lifting force instead adds energy while gravity does negative work.",
        ["Descending", lift(2, 8, 3)],
        ["Ascending", lift(2, 3, 8)],
      ),
    ],
    questions: [
      numeric(
        "A 3 kg object rises from 1 m to 5 m where g = 10 m/s². Find its gravitational potential-energy change in joules.",
        120,
        "ΔU = 3 × 10 × (5 − 1) = 120 J.",
        [
          "Use the difference between final and initial height.",
          "Multiply that difference by mg.",
          "Calculate 3 × 10 × 4.",
        ],
        "J",
      ),
      choose(
        "You shift the zero-height reference while describing the same physical rise. What happens to its gravitational potential-energy change?",
        ["It stays the same", "It doubles", "It must become zero"],
        0,
        "Both endpoint heights shift equally, leaving both Δh and ΔU unchanged.",
        "Only the height difference enters ΔU.",
      ),
      numeric(
        "A 2 kg object descends from 8 m to 3 m with g = 10 m/s². Find its signed gravitational potential-energy change in joules.",
        -100,
        "ΔU = 2 × 10 × (3 − 8) = −100 J.",
        [
          "Final height is less than initial height.",
          "Use final minus initial height.",
          "Calculate 2 × 10 × (−5).",
        ],
        "J",
      ),
      numeric(
        "A 2 kg object descends from 8 m to 3 m with g = 10 m/s². Find the work done by gravity in joules.",
        100,
        "Gravity does W = −ΔU = −(−100) = +100 J.",
        [
          "Gravity and this displacement point the same way.",
          "Gravity's work is minus the potential-energy change.",
          "Multiply the weight magnitude by the downward distance.",
        ],
        "J",
      ),
      numeric(
        "A 4 kg object rises by 1.5 m where g = 10 m/s². Find its gravitational potential-energy increase in joules.",
        60,
        "ΔU = 4 × 10 × 1.5 = 60 J.",
        [
          "The height change is already given.",
          "Multiply mass, g and height change.",
          "Calculate 4 × 10 × 1.5.",
        ],
        "J",
      ),
      choose(
        "You assign U = 0 at the floor. Does an object at the floor necessarily have zero kinetic energy?",
        [
          "Yes, all its energy must be zero",
          "No, it may still be moving",
          "Yes, because its height is zero",
        ],
        1,
        "The potential-energy reference says nothing about the object's speed or kinetic energy.",
        "Height and speed determine different forms of energy.",
      ),
    ],
    cards: [
      card(
        "A 5 kg object rises by 2 m with g = 10 m/s². Find its gravitational potential-energy change in joules.",
        100,
        "ΔU = 5 × 10 × 2 = 100 J.",
        "J",
      ),
      card(
        "A 2 kg object descends by 4 m with g = 10 m/s². Find gravity's work in joules.",
        80,
        "Gravity does positive work along the descent: 2 × 10 × 4 = 80 J.",
        "J",
      ),
    ],
  },
  {
    id: "keeping-energy-account",
    title: "Where the energy goes",
    summary: "Account for motion, height and heating during a descent.",
    moduleId: "phys-energy",
    sourceIds: ["phys-energy", "phys-kinetic", "phys-potential"],
    beats: [
      beat(
        "Follow the energy",
        "Consider the object, Earth and track together, with no energy entering or leaving. With no heating, a 2 kg object released from height 10 m at g = 10 m/s² converts 200 J of gravitational potential energy into 200 J of kinetic energy at zero height.",
        ["No heating", drop(2, 10)],
        ["40 J becomes heating", drop(2, 10, 40)],
      ),
      beat(
        "Include heating",
        "Friction can turn mechanical energy into thermal energy. If the same descent produces 40 J of heating, final kinetic energy is 200 − 40 = 160 J. The energy has changed form; it has not disappeared.",
        ["Heating 40 J", drop(2, 10, 40)],
        ["Heating 80 J", drop(2, 10, 80)],
      ),
      beat(
        "Keep the boundary in view",
        "For this closed system, kinetic plus gravitational potential plus thermal energy stays constant. Mechanical energy alone, K + U, decreases when heating increases. This model assigns heating progressively along the descent; its slider represents progress, not physical time.",
        ["No heating", drop(2, 10)],
        ["100 J becomes heating", drop(2, 10, 100)],
      ),
      beat(
        "Recover the speed",
        "Kinetic energy determines speed through v = √(2K/m). After a 2 kg object loses 200 J of potential energy and 100 J becomes heating, its final kinetic energy is 100 J. Its speed is √(2 × 100 / 2) = 10 m/s.",
        ["Heating 100 J", drop(2, 10, 100)],
        ["No heating", drop(2, 10)],
      ),
    ],
    questions: [
      numeric(
        "A 2 kg object starts from rest at height 10 m with g = 10 m/s². It reaches zero height with no heating or other energy transfers. Find its final kinetic energy in joules.",
        200,
        "Initial potential energy is 2 × 10 × 10 = 200 J; all becomes kinetic energy.",
        [
          "The initial kinetic energy is zero.",
          "Use the potential-energy decrease.",
          "Calculate mgh = 2 × 10 × 10.",
        ],
        "J",
      ),
      numeric(
        "A 2 kg object starts from rest at height 10 m with g = 10 m/s². At zero height, 40 J has become thermal energy and no other transfers occurred. Find its final kinetic energy in joules.",
        160,
        "Final K = 200 − 40 = 160 J.",
        [
          "Start with 200 J of potential energy.",
          "Include the stated thermal energy in the account.",
          "Subtract 40 from 200.",
        ],
        "J",
      ),
      choose(
        "A descending object loses mechanical energy through friction. The system contains the object, Earth and track, with no external energy transfers. Which sum stays constant?",
        [
          "Kinetic energy alone",
          "Kinetic plus gravitational potential plus thermal energy",
          "Gravitational potential energy alone",
        ],
        1,
        "Including the thermal energy produced by friction closes the energy account.",
        "Follow the energy into the track as well as the object.",
      ),
      numeric(
        "A 2 kg object has final kinetic energy 100 J after a descent. Find its speed in m/s.",
        10,
        "v = √(2K/m) = √(200/2) = 10 m/s.",
        ["Rearrange K = ½mv².", "First calculate v² = 2K/m.", "Take the square root of 100."],
        "m/s",
      ),
      numeric(
        "An object starts with 12 J of kinetic energy, loses 90 J of gravitational potential energy and produces 18 J of thermal energy. No other transfers occur. Find its final kinetic energy in joules.",
        84,
        "Final K = 12 + 90 − 18 = 84 J.",
        [
          "Include the energy of motion already present.",
          "Add the potential-energy decrease and subtract heating.",
          "Calculate 12 + 90 − 18.",
        ],
        "J",
      ),
      choose(
        "With friction, which statement follows for a closed object-Earth-track system?",
        [
          "Total energy is destroyed",
          "Mechanical energy can decrease while total energy stays constant",
          "Kinetic energy must stay constant",
        ],
        1,
        "Mechanical energy may become thermal energy while the total is conserved.",
        "Distinguish mechanical energy from all the energy forms inside the boundary.",
      ),
    ],
    cards: [
      card(
        "A descent releases 150 J of gravitational potential energy. Initial kinetic energy is 20 J and heating gains 35 J, with no other transfers. Find final kinetic energy in joules.",
        135,
        "K_final = 20 + 150 − 35 = 135 J.",
        "J",
      ),
      card(
        "A 4 kg cart has kinetic energy 72 J. Find its speed in m/s.",
        6,
        "v = √(2 × 72 / 4) = √36 = 6 m/s.",
        "m/s",
      ),
    ],
  },
];
