import { forces, support, beat, numeric, choose, card, type TeachingLesson } from "./definition.js";
export const forceLessons: TeachingLesson[] = [
  {
    id: "balanced-forces",
    title: "When forces balance",
    summary: "Add signed forces and distinguish balanced forces from being at rest.",
    moduleId: "phys-forces",
    sourceIds: ["phys-inertia", "phys-newton"],
    beats: [
      beat(
        "Combine the pushes",
        "Choose the object before adding forces. For right positive, a 14 N rightward force and a 6 N leftward force give a net force of +8 N. Equal arrows in opposite directions would sum to zero.",
        ["Rightward result", forces(4, 14, 6)],
        ["Balanced", forces(4, 10, 10)],
      ),
      beat(
        "Motion without a net push",
        "With zero net force, velocity stays constant. A moving cart can keep travelling while its forces balance. Newton's first law describes unchanged velocity, including the special case of remaining at rest.",
        ["Already moving", forces(4, 10, 10, 3)],
        ["Initially at rest", forces(4, 10, 10, 0)],
      ),
      beat(
        "Rest is one possibility",
        "If an object starts at rest and its forces stay balanced, it remains at rest. Balanced does not mean no forces act: an opposing pair on the same object can have a zero sum.",
        ["Two balanced forces", forces(3, 9, 9)],
        ["No horizontal forces", forces(3, 0, 0)],
      ),
      beat(
        "The larger force sets the result",
        "The net force points toward the larger opposing force. A cart moving right can have a leftward net force; the force changes its velocity rather than reporting the direction it already travels.",
        ["Push against motion", forces(4, 8, 20, 8, 1)],
        ["Push with motion", forces(4, 20, 8, 8, 1)],
      ),
    ],
    questions: [
      numeric(
        "Two horizontal forces act on a cart: 14 N right and 6 N left. With right positive, find the net force in newtons.",
        8,
        "Net force = 14 − 6 = +8 N.",
        [
          "Give opposite directions opposite signs.",
          "Add the signed forces on the same cart.",
          "Calculate 14 − 6.",
        ],
        "N",
      ),
      choose(
        "A cart is already moving right at 3 m/s. Its net force stays zero. What happens next in an inertial frame?",
        ["It immediately stops", "It continues at 3 m/s to the right", "It gains speed"],
        1,
        "Zero net force leaves the velocity unchanged.",
        "Balanced forces imply no change in velocity.",
      ),
      numeric(
        "A resting cart has 9 N rightward and 9 N leftward horizontal forces. Find its horizontal net force in newtons.",
        0,
        "9 − 9 = 0 N; the horizontal forces balance.",
        [
          "Compare the two force magnitudes.",
          "Use opposite signs for opposite directions.",
          "Calculate 9 − 9.",
        ],
        "N",
      ),
      numeric(
        "A cart moving right experiences 8 N right and 20 N left. With right positive, find the net force in newtons.",
        -12,
        "8 − 20 = −12 N. The net force is leftward even while the cart moves right.",
        [
          "Separate the velocity direction from the force sum.",
          "The leftward force enters with a minus sign.",
          "Calculate 8 − 20.",
        ],
        "N",
      ),
      numeric(
        "Forces of 7 N and 11 N act rightward on a crate; a 5 N force acts leftward. Find the net force in newtons with right positive.",
        13,
        "Net force = 7 + 11 − 5 = +13 N.",
        [
          "Group the forces pointing in the same direction.",
          "Add the two rightward forces, then subtract the leftward force.",
          "Calculate 7 + 11 − 5.",
        ],
        "N",
      ),
      choose(
        "An object moves left at constant nonzero velocity in an inertial frame. What is its net force?",
        ["Leftward", "Rightward", "Zero"],
        2,
        "Constant velocity means no acceleration, so the net force is zero.",
        "A continuing velocity does not require a continuing net push.",
      ),
    ],
    cards: [
      card(
        "A cart has forces of 5 N right and 17 N left. With right positive, find the net force in newtons.",
        -12,
        "5 − 17 = −12 N.",
        "N",
      ),
      card(
        "A cart has one 14 N leftward force. What rightward force magnitude, in newtons, balances it?",
        14,
        "An equal opposing force of 14 N makes the net force zero.",
        "N",
      ),
    ],
  },
  {
    id: "force-mass-acceleration",
    title: "Force, mass and acceleration",
    summary: "Use net force and mass to predict how velocity changes.",
    moduleId: "phys-forces",
    sourceIds: ["phys-newton"],
    beats: [
      beat(
        "Divide the net force",
        "Newton's second law connects net force, mass and acceleration: F_net = ma. A 3 kg cart with 18 N right and 6 N left has net force 12 N, so its acceleration is 12/3 = 4 m/s² rightward.",
        ["Mass 3 kg", forces(3, 18, 6)],
        ["Mass 6 kg", forces(6, 18, 6)],
      ),
      beat(
        "Change the mass",
        "The same net force gives less acceleration to a larger mass. Doubling mass halves acceleration when the force stays fixed. Mass measures resistance to a change in velocity; it does not specify the current speed.",
        ["Lighter cart", forces(2, 12)],
        ["Heavier cart", forces(4, 12)],
      ),
      beat(
        "Change the force",
        "For the same mass, acceleration changes in proportion to the net force. A 2 kg cart under 24 N accelerates at 12 m/s². Compare its motion with the same cart under 12 N.",
        ["12 N", forces(2, 12, 0, 0, 1)],
        ["24 N", forces(2, 24, 0, 0, 1)],
      ),
      beat(
        "An opposing net force",
        "The sign of acceleration follows the net force. With right positive, forces of 4 N right and 12 N left on a 4 kg cart give acceleration −2 m/s². A rightward-moving cart initially slows under this acceleration.",
        ["Force left", forces(4, 4, 12, 6, 2)],
        ["Force right", forces(4, 12, 4, 6, 2)],
      ),
    ],
    questions: [
      numeric(
        "A 3 kg cart has horizontal forces of 18 N right and 6 N left. With right positive, find its acceleration in m/s².",
        4,
        "a = (18 − 6)/3 = 4 m/s².",
        [
          "Add the forces before applying the second law.",
          "Divide the net force by mass.",
          "Calculate (18 − 6)/3.",
        ],
        "m/s²",
      ),
      choose(
        "The mass doubles while the net force stays the same. What happens to acceleration?",
        ["It doubles", "It is halved", "It stays the same"],
        1,
        "Acceleration is net force divided by mass, so twice the mass gives half the acceleration.",
        "Keep the numerator fixed in a = F_net/m.",
      ),
      numeric(
        "A 2 kg cart experiences a net force of 24 N rightward. Find its acceleration in m/s² with right positive.",
        12,
        "a = 24/2 = 12 m/s².",
        [
          "The stated force is already the net force.",
          "Use acceleration = net force divided by mass.",
          "Divide the stated net force by the cart's mass.",
        ],
        "m/s²",
      ),
      numeric(
        "A 4 kg cart moving right has forces of 4 N right and 12 N left. With right positive, find its acceleration in m/s².",
        -2,
        "a = (4 − 12)/4 = −2 m/s².",
        [
          "The velocity does not change the force sum.",
          "Subtract the leftward force and divide by mass.",
          "Calculate (4 − 12)/4.",
        ],
        "m/s²",
      ),
      numeric(
        "What net force magnitude in newtons gives a 4 kg object an acceleration magnitude of 3 m/s²?",
        12,
        "F_net = 4 × 3 = 12 N.",
        [
          "This time, the mass and acceleration are known.",
          "Multiply them to find net force.",
          "Calculate 4 × 3.",
        ],
        "N",
      ),
      choose(
        "A heavier cart and a lighter cart must have the same acceleration. Which needs the larger net force?",
        ["The heavier cart", "The lighter cart", "Both need the same net force"],
        0,
        "For a fixed acceleration, F_net = ma grows with mass.",
        "Hold acceleration fixed in the second law.",
      ),
    ],
    cards: [
      card(
        "A net horizontal force of 35 N acts on a 5 kg cart. Find its acceleration magnitude in m/s².",
        7,
        "35/5 = 7 m/s².",
        "m/s²",
      ),
      card(
        "A 6 kg object must accelerate at 2 m/s². Find the required net force magnitude in newtons.",
        12,
        "6 × 2 = 12 N.",
        "N",
      ),
    ],
  },
  {
    id: "weight-and-support",
    title: "Weight and support",
    summary: "Distinguish mass, gravitational force and the force from a support.",
    moduleId: "phys-forces",
    sourceIds: ["phys-newton", "phys-support"],
    beats: [
      beat(
        "Mass is not weight",
        "Weight is the gravitational force on an object: magnitude W = mg. Mass is measured in kilograms; weight is measured in newtons. In a field with g = 10 m/s², a 3 kg object weighs 30 N.",
        ["Mass 3 kg", support(3)],
        ["Mass 6 kg", support(6)],
      ),
      beat(
        "Change the gravitational field",
        "Moving to a different gravitational field changes weight without changing mass. The same 3 kg object weighs 30 N where g = 10 m/s² and 4.8 N where g = 1.6 m/s².",
        ["Stronger field", support(3, 10)],
        ["Weaker field", support(3, 1.6)],
      ),
      beat(
        "Resting on a support",
        "When only weight and an upward support force act, zero vertical acceleration requires them to balance. A 4 kg object at rest with g = 10 m/s² has a 40 N upward support force.",
        ["No vertical acceleration", support(4, 10, 0)],
        ["Accelerating upward", support(4, 10, 2)],
      ),
      beat(
        "A support can push harder",
        "An upward acceleration requires a net upward force. With upward positive, N − mg = ma, so N = m(g + a). A 4 kg object accelerating upward at 2 m/s² where g = 10 m/s² needs support force 48 N.",
        ["Acceleration upward", support(4, 10, 2)],
        ["Acceleration downward", support(4, 10, -2)],
      ),
    ],
    questions: [
      numeric(
        "An object has mass 3 kg where g = 10 m/s². Find the magnitude of its weight in newtons.",
        30,
        "W = mg = 3 × 10 = 30 N.",
        [
          "Weight is a force produced by gravity.",
          "Multiply mass by the stated gravitational acceleration.",
          "Calculate 3 × 10.",
        ],
        "N",
      ),
      choose(
        "A 3 kg object moves to a location with smaller gravitational acceleration. What happens to its mass?",
        ["It decreases", "It stays 3 kg", "It becomes its old weight"],
        1,
        "Changing the gravitational field changes weight; the object's mass remains 3 kg.",
        "Mass and weight measure different physical quantities.",
      ),
      numeric(
        "A 4 kg object rests on a horizontal support. Only weight and the upward support force act, with g = 10 m/s². Find the support force in newtons.",
        40,
        "With no vertical acceleration, support balances weight: N = 4 × 10 = 40 N.",
        [
          "At rest, the vertical net force is zero.",
          "The two vertical forces must have equal magnitudes.",
          "Calculate the weight 4 × 10.",
        ],
        "N",
      ),
      numeric(
        "A support accelerates a 4 kg object upward at 2 m/s². Only support and weight act, and g = 10 m/s². Find the support force in newtons.",
        48,
        "N − mg = ma, so N = 4 × (10 + 2) = 48 N.",
        [
          "The support must supply both weight balance and upward net force.",
          "Use N = m(g + a).",
          "Calculate 4 × (10 + 2).",
        ],
        "N",
      ),
      numeric(
        "A 7 kg object is in a field where g = 9.8 m/s². Find its weight magnitude in newtons.",
        68.6,
        "Weight = 7 × 9.8 = 68.6 N.",
        [
          "Use the given value of g rather than rounding it to 10.",
          "Multiply mass by gravitational acceleration.",
          "Calculate 7 × 9.8.",
        ],
        "N",
      ),
      choose(
        "An object on a support moves downward at constant velocity. Only weight and support act. How does the support force compare with weight?",
        ["It is smaller", "It is equal", "It is larger"],
        1,
        "Constant velocity gives zero acceleration, so the support and weight balance.",
        "Downward velocity does not imply downward acceleration.",
      ),
    ],
    cards: [
      card(
        "An object has mass 5 kg where g = 10 m/s². Find its weight magnitude in newtons.",
        50,
        "W = 5 × 10 = 50 N.",
        "N",
      ),
      card(
        "A 3 kg object accelerates downward at 2 m/s² while supported. Only weight and support act, with g = 10 m/s². Find the upward support force in newtons.",
        24,
        "Taking upward positive, N = 3 × (10 − 2) = 24 N.",
        "N",
      ),
    ],
  },
];
