import {
  beat,
  blackbody,
  card,
  choose,
  expansion,
  life,
  numeric,
  term,
  type TeachingLesson,
} from "./definition.js";

export const cosmosLessons: TeachingLesson[] = [
  {
    id: "star-lives",
    title: "How mass sets a star's life",
    summary: "Estimate main-sequence lifetimes from mass and predict how a star ends.",
    moduleId: "astro-cosmos",
    sourceIds: ["astro-lifetimes", "astro-massive", "astro-hr"],
    beats: [
      beat(
        "More fuel, burned much faster",
        "A star spends most of its life on the main sequence, fusing hydrogen in its core. A heavier star has more fuel, roughly in proportion to its mass M, but its core is hotter and denser, so it shines roughly as M³·⁵. Lifetime is fuel divided by burn rate, so t ∝ M/M³·⁵ = M⁻²·⁵. Scaled to the Sun's 10 billion years, a 4 M☉ star lasts 10 × 4⁻²·⁵ = 0.3125 billion years: 312.5 million.",
        ["1 M☉", life(1)],
        ["4 M☉", life(4)],
      ),
      beat(
        "Luminosity climbs steeply",
        "The rule L ∝ M³·⁵ is a fit to measured main-sequence stars, good to a factor of about two between half and twenty solar masses. A 2 M☉ star shines at 2³·⁵ = 11.3 L☉; a 10 M☉ star at about 3,200 L☉. Mass is the single number that fixes a main-sequence star's place on the H–R diagram.",
        ["2 M☉", life(2)],
        ["10 M☉", life(10)],
      ),
      beat(
        "Small stars outlast the universe",
        "Low-mass stars burn so slowly that the rule gives a 0.5 M☉ red dwarf 10 × 0.5⁻²·⁵ = 56.6 billion years, four times the present age of the universe. No red dwarf has yet left the main sequence. The OpenStax table lists 200 billion years for 0.4 M☉; the power law is an estimate, not a precise clock.",
        ["0.5 M☉ red dwarf", life(0.5)],
        ["1 M☉, the Sun", life(1)],
      ),
      beat(
        "Mass decides the ending",
        "When core hydrogen runs out, the core contracts and the outer layers swell into a giant. Following the OpenStax table of end states: stars that begin below about 10 M☉ shed their envelopes and leave white dwarfs; those of about 10 to 40 M☉ explode as supernovae and leave neutron stars; heavier ones leave black holes. The boundaries are uncertain and depend on how much mass a star loses.",
        ["1 M☉", life(1)],
        ["15 M☉", life(15)],
        ["50 M☉", life(50)],
      ),
    ],
    questions: [
      numeric(
        "Main-sequence lifetime scales as t ≈ 10 billion years × M⁻²·⁵, with M in solar masses. Find the lifetime of a 4 M☉ star in millions of years, to one decimal place.",
        312.5,
        "4⁻²·⁵ = 1/32, so t = 10 billion/32 = 0.3125 billion years = 312.5 million years.",
        [
          "Raise 4 to the power −2.5.",
          "4²·⁵ is 4² × √4.",
          "Divide 10 billion years by 4²·⁵ and convert to millions.",
        ],
        "million years",
        0.06,
      ),
      numeric(
        "Main-sequence luminosity scales roughly as L ∝ M³·⁵. How many times the Sun's luminosity does a 2 M☉ star have? Give one decimal place.",
        11.3,
        "2³·⁵ = 2³ × √2 = 8 × 1.414 = 11.3 L☉.",
        [
          "Raise the mass ratio to the power 3.5.",
          "Split 2³·⁵ into 2³ × 2⁰·⁵.",
          "Multiply 8 by √2.",
        ],
        "L☉",
        0.05,
      ),
      numeric(
        "Using t ≈ 10 billion years × M⁻²·⁵, find the main-sequence lifetime of a 0.5 M☉ red dwarf in billions of years, to one decimal place.",
        56.6,
        "0.5⁻²·⁵ = 2²·⁵ = 5.657, so t = 56.6 billion years.",
        [
          "A negative power of one half is a positive power of two.",
          "Work out 2²·⁵.",
          "Multiply by 10 billion years.",
        ],
        "billion years",
        0.05,
      ),
      term(
        "Following the OpenStax table of stellar end states, what remnant does a star of initial mass 15 M☉ leave? Answer in two words.",
        ["neutron star"],
        "A neutron star. Stars of about 10 to 40 M☉ end in a core-collapse supernova that leaves a neutron star.",
        "Its core collapses in a supernova but stops short of a black hole.",
      ),
      numeric(
        "A star spends 10 million years on the main sequence. Using t ≈ 10 billion years × M⁻²·⁵, find its mass in solar masses, to the nearest whole number.",
        16,
        "M⁻²·⁵ = 10⁷/10¹⁰ = 10⁻³, so M = 10^(3/2.5) = 10¹·² = 15.8, about 16 M☉.",
        [
          "Divide the lifetime by 10 billion years to get M⁻²·⁵.",
          "Invert to get M²·⁵.",
          "Raise 1,000 to the power 1/2.5.",
        ],
        "M☉",
        0.5,
      ),
      choose(
        "What will the Sun become after its red-giant stage?",
        ["A white dwarf", "A neutron star", "A black hole"],
        0,
        "At 1 M☉ the Sun is well below the 10 M☉ boundary. It will shed its outer layers and leave a carbon-oxygen white dwarf about the size of Earth.",
        "Compare the Sun's mass with the boundary for a supernova.",
      ),
    ],
    cards: [
      card(
        "Using t ≈ 10 billion years × M⁻²·⁵, find the main-sequence lifetime of a 9 M☉ star in millions of years, to the nearest whole number.",
        41,
        "9²·⁵ = 81 × 3 = 243, so t = 10,000 million/243 = 41 million years.",
        "million years",
        0.5,
      ),
      card(
        "Using L ∝ M³·⁵, how many times more luminous than the Sun is a 4 M☉ main-sequence star?",
        128,
        "4³·⁵ = 4³ × √4 = 64 × 2 = 128 L☉.",
        "L☉",
      ),
    ],
  },
  {
    id: "expanding-universe",
    title: "Galaxies and Hubble's law",
    summary:
      "Picture the scale of the universe and use Hubble's law to link velocity and distance.",
    moduleId: "astro-cosmos",
    sourceIds: ["astro-galaxies", "astro-expanding", "astro-doppler"],
    beats: [
      beat(
        "A universe of galaxies",
        "The Milky Way is a disc of a few hundred billion stars about 100,000 light-years across, one galaxy among billions. Distances between galaxies are measured in megaparsecs: 1 Mpc = 3.26 million light-years. The Andromeda galaxy, about 0.78 Mpc away, is seen by light that left it 0.78 × 3.26 = 2.5 million years ago.",
        ["Nearby galaxy, 10 Mpc", expansion(70, 10)],
        ["Distant galaxy, 100 Mpc", expansion(70, 100)],
      ),
      beat(
        "Velocity grows with distance",
        "Galaxy spectra are redshifted, and the redshift grows with distance. Hubble's law states it as v = H₀d. Measurements of H₀ cluster around 70 km/s per megaparsec, so a galaxy 100 Mpc away recedes at 7,000 km/s and one at 200 Mpc at 14,000 km/s.",
        ["100 Mpc", expansion(70, 100)],
        ["200 Mpc", expansion(70, 200)],
      ),
      beat(
        "Everyone sees the same",
        "Play the expansion and every spacing on the grid grows by the same factor. A galaxy twice as far gains twice the distance in the same time, so every observer, in any galaxy, sees others receding at speeds proportional to their distance. The pattern needs no centre. Reversing the law, a recession speed gives a distance: d = v/H₀.",
        ["Galaxy at 200 Mpc", expansion(70, 200)],
        ["Galaxy at 50 Mpc", expansion(70, 50)],
      ),
      beat(
        "An uncertain constant",
        "Different methods give H₀ between about 67 and 73 km/s/Mpc, a disagreement astronomers call the Hubble tension. For a galaxy 300 Mpc away the two values predict speeds of 20,100 and 21,900 km/s, a difference of 6 × 300 = 1,800 km/s. Distances inferred from velocities inherit the same uncertainty.",
        ["H₀ = 67", expansion(67, 300)],
        ["H₀ = 73", expansion(73, 300)],
      ),
    ],
    questions: [
      numeric(
        "The Andromeda galaxy is about 0.78 Mpc away, and 1 Mpc = 3.26 million light-years. How long ago, in millions of years, did the light we see from it set out? Give one decimal place.",
        2.5,
        "0.78 × 3.26 = 2.54 million light-years, so the light left about 2.5 million years ago.",
        [
          "A light-year is the distance light covers in one year.",
          "Convert megaparsecs to millions of light-years.",
          "Multiply 0.78 by 3.26.",
        ],
        "million years",
        0.06,
      ),
      numeric(
        "With H₀ = 70 km/s per Mpc, find the recession velocity of a galaxy 100 Mpc away, in km/s.",
        7000,
        "v = H₀d = 70 × 100 = 7,000 km/s.",
        ["Use Hubble's law v = H₀d.", "The units of Mpc cancel.", "Multiply 70 by 100."],
        "km/s",
      ),
      numeric(
        "A galaxy recedes at 14,000 km/s. With H₀ = 70 km/s per Mpc, how far away is it, in Mpc?",
        200,
        "d = v/H₀ = 14,000/70 = 200 Mpc.",
        ["Rearrange v = H₀d for distance.", "Divide the velocity by H₀.", "Calculate 14,000/70."],
        "Mpc",
      ),
      numeric(
        "Estimates of H₀ range from 67 to 73 km/s per Mpc. For a galaxy 300 Mpc away, by how many km/s do the two predicted velocities differ?",
        1800,
        "73 × 300 − 67 × 300 = (73 − 67) × 300 = 1,800 km/s.",
        [
          "Compute each velocity with v = H₀d, or work with the difference directly.",
          "The difference in H₀ is 73 − 67.",
          "Multiply that difference by 300 Mpc.",
        ],
        "km/s",
      ),
      numeric(
        "A galaxy's 500.0 nm line is observed at 510.0 nm. Using v = cΔλ/λ with c = 3.00 × 10⁵ km/s, and H₀ = 70 km/s per Mpc, find its distance in Mpc, to the nearest whole number.",
        86,
        "v = 3.00 × 10⁵ × 10.0/500.0 = 6,000 km/s; d = 6,000/70 = 85.7 Mpc, about 86 Mpc.",
        [
          "First turn the redshift into a velocity.",
          "Δλ/λ = 10.0/500.0.",
          "Then divide that velocity by H₀.",
        ],
        "Mpc",
        0.5,
      ),
      choose(
        "Every distant galaxy appears to recede from the Milky Way. What does this tell us about our position?",
        [
          "Nothing special: uniform expansion gives every galaxy the same view",
          "The Milky Way is at the centre of the expansion",
          "The Milky Way is the oldest galaxy",
        ],
        0,
        "In a uniform expansion all spacings grow by the same factor, so observers in any galaxy see v ∝ d. Recession in every direction does not single out a centre.",
        "Imagine standing on a different galaxy on the stretching grid.",
      ),
    ],
    cards: [
      card(
        "With H₀ = 70 km/s per Mpc, find the recession velocity of a galaxy 40 Mpc away, in km/s.",
        2800,
        "v = 70 × 40 = 2,800 km/s.",
        "km/s",
      ),
      card(
        "A galaxy recedes at 3,600 km/s. With H₀ = 72 km/s per Mpc, find its distance in Mpc.",
        50,
        "d = 3,600/72 = 50 Mpc.",
        "Mpc",
      ),
    ],
  },
  {
    id: "big-bang",
    title: "The age and afterglow of the Big Bang",
    summary:
      "Estimate the age of the universe from H₀ and read its early heat in the microwave background.",
    moduleId: "astro-cosmos",
    sourceIds: ["astro-age", "astro-cmb", "astro-spectrum"],
    beats: [
      beat(
        "Run the expansion backwards",
        "If every galaxy had always receded at its present speed, a galaxy at distance d would have set off a time d/v = d/(H₀d) = 1/H₀ ago, the same for all of them. With H₀ = 70 km/s/Mpc, 1/H₀ = 3.086 × 10¹⁹ km ÷ 70 km/s = 4.41 × 10¹⁷ s, about 14.0 billion years. Careful modelling of the changing expansion gives 13.8 billion years.",
        ["H₀ = 70", expansion(70, 100)],
        ["H₀ = 50", expansion(50, 100)],
      ),
      beat(
        "A glow from every direction",
        "In 1965 Arno Penzias and Robert Wilson found faint microwave radiation coming equally from every direction. Its spectrum is an almost perfect blackbody at 2.725 K, peaking at 2.898 × 10⁻³ / 2.725 = 1.06 × 10⁻³ m, about 1.06 mm. A cold, uniform glow filling space is what a universe that was once hot and dense should leave behind.",
        ["Today: 2.725 K", blackbody(2.725)],
        ["At release: 3,000 K", blackbody(3000)],
      ),
      beat(
        "Stretched by expansion",
        "About 380,000 years after the Big Bang the universe had cooled to about 3,000 K, cool enough for electrons to join nuclei into neutral atoms. Light then travelled freely. Since then expansion has stretched every wavelength, and a blackbody's temperature falls in the same proportion, so 3,000/2.725 = 1,100 is the stretch factor.",
        ["3,000 K", blackbody(3000)],
        ["2.725 K", blackbody(2.725)],
      ),
      beat(
        "How much the constant matters",
        "The age estimate is inversely proportional to H₀. A smaller H₀ means slower expansion and an older universe: H₀ = 50 km/s/Mpc gives 1/H₀ = 19.6 billion years. Stars older than 1/H₀ would be a contradiction, which is one reason astronomers check stellar ages against the expansion age.",
        ["H₀ = 50", expansion(50, 200)],
        ["H₀ = 70", expansion(70, 200)],
        ["H₀ = 90", expansion(90, 200)],
      ),
    ],
    questions: [
      numeric(
        "With H₀ = 70 km/s per Mpc, 1 Mpc = 3.086 × 10¹⁹ km and 1 billion years = 3.156 × 10¹⁶ s, find 1/H₀ in billions of years, to one decimal place.",
        14,
        "1/H₀ = 3.086 × 10¹⁹ km ÷ 70 km/s = 4.409 × 10¹⁷ s; ÷ 3.156 × 10¹⁶ s = 13.97, about 14.0 billion years.",
        [
          "Write H₀ as 70 km/s per 3.086 × 10¹⁹ km so the kilometres cancel.",
          "Divide 3.086 × 10¹⁹ by 70 to get seconds.",
          "Convert seconds to billions of years.",
        ],
        "billion years",
        0.06,
      ),
      numeric(
        "The cosmic microwave background is a blackbody at 2.725 K. Using λmax = 2.898 × 10⁻³ m·K / T, find its peak wavelength in millimetres, to two decimal places.",
        1.06,
        "λmax = 2.898 × 10⁻³ / 2.725 = 1.063 × 10⁻³ m = 1.06 mm.",
        [
          "Divide Wien's constant by the temperature.",
          "The result is in metres.",
          "Multiply by 1,000 to convert to millimetres.",
        ],
        "mm",
        0.006,
      ),
      numeric(
        "The cosmic background was released at about 3,000 K and is now 2.725 K. By what factor have its wavelengths been stretched since then, to the nearest whole number?",
        1101,
        "Temperature falls as wavelengths stretch, so the factor is 3,000/2.725 = 1,100.9, which is 1,101 to the nearest whole number.",
        [
          "Wien's law makes peak wavelength inversely proportional to temperature.",
          "So the stretch factor is the ratio of the two temperatures.",
          "Divide the earlier temperature by today's.",
        ],
        "",
        0.5,
      ),
      numeric(
        "Using 1/H₀ = 977.8 billion years ÷ H₀ (H₀ in km/s per Mpc), find 1/H₀ for H₀ = 50, in billions of years, to one decimal place.",
        19.6,
        "977.8/50 = 19.56, about 19.6 billion years.",
        [
          "The constant 977.8 converts the units for you.",
          "Divide it by the value of H₀.",
          "Round to one decimal place.",
        ],
        "billion years",
        0.05,
      ),
      term(
        "What kind of spectrum does the cosmic microwave background have? Answer with the one-word name for the spectrum of an ideal thermal emitter.",
        ["blackbody", "black body", "black-body", "thermal"],
        "A blackbody spectrum, the closest to perfect ever measured, at 2.725 K.",
        "It is the same kind of spectrum Wien's law describes.",
      ),
      choose(
        "Why is 1/H₀ only an approximation to the age of the universe?",
        [
          "The expansion rate has changed over time, slowed by gravity and later sped up",
          "Light from distant galaxies travelled faster than light does now",
          "Galaxies only recede from the Milky Way, so the formula ignores the rest",
        ],
        0,
        "1/H₀ assumes each galaxy kept a constant speed. Gravity slowed the early expansion and dark energy has since accelerated it; the two effects nearly cancel, so 13.8 billion years is close to 1/H₀.",
        "What does 1/H₀ assume about each galaxy's speed?",
      ),
    ],
    cards: [
      card(
        "Using 1/H₀ = 977.8 billion years ÷ H₀ (H₀ in km/s per Mpc), find 1/H₀ for H₀ = 65, in billions of years, to one decimal place.",
        15,
        "977.8/65 = 15.04, about 15.0 billion years.",
        "billion years",
        0.05,
      ),
      card(
        "A blackbody spectrum peaks at 1.0 mm. Using Wien's law with constant 2.898 × 10⁻³ m·K, find its temperature in kelvin, to two decimal places.",
        2.9,
        "T = 2.898 × 10⁻³ / 1.0 × 10⁻³ = 2.898 K, about 2.90 K.",
        "K",
        0.006,
      ),
    ],
  },
];
