import type {
  AstronomyModel,
  CourseCheckDefinition,
} from "../../../packages/contracts/src/index.js";
import {
  blackbody,
  doppler,
  expansion,
  gravity,
  hr,
  launch,
  life,
  light,
  moon,
  orbit,
  parallax,
  seasons,
  sky,
  tides,
} from "./definition.js";
import { astronomyLessons } from "./lessons.js";

function item(
  id: string,
  lessonIndex: number,
  prompt: string,
  model: AstronomyModel,
  value: number,
  workedAnswer: string,
  unit: string,
  tolerance = 1e-6,
): CourseCheckDefinition["items"][number] {
  const lesson = astronomyLessons[lessonIndex]!;
  return {
    lessonId: lesson.id,
    visual: { type: "astronomy", model },
    question: {
      id: "astro-check-" + id,
      conceptIds: ["astro-" + lesson.id],
      sourceIds: lesson.sourceIds,
      prompt,
      responseType: "numeric",
      difficulty: 1,
      hints: [],
      answerAuthority: {
        kind: "numeric",
        value,
        unit,
        absoluteTolerance: tolerance,
        relativeTolerance: 0,
        workedAnswer,
      },
    },
  };
}
const required = astronomyLessons.map((l) => l.id);

export const astronomyChecks: CourseCheckDefinition[] = [
  {
    id: "starting-point",
    kind: "placement",
    title: "Find your starting point",
    description:
      "Twelve problems from the turning sky to the age of the universe. Find which ideas need attention before you begin.",
    requiredLessonIds: [],
    items: [
      item(
        "placement-sky",
        0,
        "From latitude 40° N, a star of declination +30° crosses the meridian. Find its altitude in degrees.",
        sky(40, 30, 8),
        80,
        "Altitude = 90° − |40° − 30°| = 80°.",
        "°",
      ),
      item(
        "placement-seasons",
        1,
        "At latitude 30° N, with Earth's tilt taken as 23.4°, find the Sun's noon altitude at the June solstice, in degrees, to one decimal place.",
        seasons(30, "june-solstice"),
        83.4,
        "δ = +23.4°; altitude = 90° − |30° − 23.4°| = 83.4°.",
        "°",
        0.05,
      ),
      item(
        "placement-moon",
        2,
        "What percentage of the Moon's visible disc is lit when the Sun–Earth–Moon angle is 45°? Give one decimal place.",
        moon(3.69),
        14.6,
        "(1 − cos 45°)/2 = (1 − 0.7071)/2 = 0.146, so 14.6% of the disc.",
        "%",
        0.05,
      ),
      item(
        "placement-kepler",
        3,
        "A body orbits the Sun with semi-major axis 16 AU. Using P² = a³, find its period in years.",
        orbit(16, 0.1),
        64,
        "P² = 16³ = 4,096, so P = 64 years.",
        "years",
      ),
      item(
        "placement-gravity",
        4,
        "The distance between two bodies shrinks to a quarter of its first value. By what factor does the gravitational force between them change?",
        gravity(1, 1, 4),
        16,
        "F ∝ 1/r², so a quarter of the distance gives 4² = 16 times the force.",
        "",
      ),
      item(
        "placement-orbit",
        5,
        "The drawing shows a 9 km/s launch from 1,000 km above Earth, which stretches into an ellipse. Find the circular orbital speed at that height, where r = 7,371 km and GM = 3.986 × 10¹⁴ m³/s², in km/s, to two decimal places.",
        launch("earth", 1000, 9),
        7.35,
        "v = √(3.986 × 10¹⁴ / 7.371 × 10⁶) = 7,354 m/s, about 7.35 km/s.",
        "km/s",
        0.006,
      ),
      item(
        "placement-parallax",
        6,
        "A star's parallax is 0.2 arcseconds. Find its distance in parsecs.",
        parallax(0.2),
        5,
        "d = 1/p = 1/0.2 = 5 pc.",
        "pc",
      ),
      item(
        "placement-wien",
        7,
        "Using λmax = 2.898 × 10⁻³ m·K / T, find the peak wavelength of a 7,245 K star in nanometres, to the nearest whole number.",
        blackbody(7245),
        400,
        "2.898 × 10⁻³ / 7,245 = 4.00 × 10⁻⁷ m = 400 nm.",
        "nm",
        0.6,
      ),
      item(
        "placement-hr",
        8,
        "A star has five times the Sun's radius and the Sun's surface temperature. Find its luminosity in solar units.",
        hr(5772, 5),
        25,
        "L = 5² × 1⁴ = 25 L☉.",
        "L☉",
      ),
      item(
        "placement-life",
        9,
        "Using t ≈ 10 billion years × M⁻²·⁵, find the main-sequence lifetime of a 2 M☉ star in billions of years, to two decimal places.",
        life(2),
        1.77,
        "2²·⁵ = 5.657, so t = 10/5.657 = 1.77 billion years.",
        "billion years",
        0.006,
      ),
      item(
        "placement-hubble",
        10,
        "With H₀ = 70 km/s per Mpc, find the recession velocity of a galaxy 50 Mpc away, in km/s.",
        expansion(70, 50),
        3500,
        "v = 70 × 50 = 3,500 km/s.",
        "km/s",
      ),
      item(
        "placement-age",
        11,
        "Using 1/H₀ = 977.8 billion years ÷ H₀ (H₀ in km/s per Mpc), find 1/H₀ for H₀ = 75, in billions of years, to one decimal place.",
        expansion(75, 100),
        13,
        "977.8/75 = 13.04, about 13.0 billion years.",
        "billion years",
        0.05,
      ),
    ],
  },
  {
    id: "mixed-challenge",
    kind: "checkpoint",
    title: "Bring the ideas together",
    description:
      "Twelve mixed problems across the sky, orbits, starlight and the cosmos. Record your confidence; results appear after the final response.",
    requiredLessonIds: required,
    items: [
      item(
        "mixed-life",
        9,
        "Using t ≈ 10 billion years × M⁻²·⁵, find the main-sequence lifetime of a 10 M☉ star in millions of years, to the nearest whole number.",
        life(10),
        32,
        "10²·⁵ = 316.2, so t = 10,000 million/316.2 = 31.6, about 32 million years.",
        "million years",
        0.5,
      ),
      item(
        "mixed-escape",
        5,
        "The drawing shows a 3 km/s launch from the surface of Mars, which falls back. Mars has GM = 4.283 × 10¹³ m³/s² and radius 3,390 km. Find the escape speed from its surface in km/s, to two decimal places.",
        launch("mars", 0, 3),
        5.03,
        "v = √(2 × 4.283 × 10¹³ / 3.39 × 10⁶) = 5,027 m/s, about 5.03 km/s.",
        "km/s",
        0.006,
      ),
      item(
        "mixed-sky",
        0,
        "From latitude 60° N, what is the smallest declination, in degrees, of a star that never sets?",
        sky(60, 45, 24),
        30,
        "Circumpolar needs δ > 90° − 60° = 30°.",
        "°",
      ),
      item(
        "mixed-doppler",
        7,
        "A source recedes at 1,500 km/s. Using λ = λ₀(1 + v/c) with c = 3.00 × 10⁵ km/s, at what wavelength is its 400.00 nm line observed, in nm, to two decimal places?",
        doppler(400, 1500),
        402,
        "Δλ = 400.00 × 1,500/300,000 = 2.00 nm, so the line appears at 402.00 nm.",
        "nm",
        0.006,
      ),
      item(
        "mixed-seasons",
        1,
        "At latitude 45° S on the December solstice, with Earth's tilt taken as 23.4°, find the Sun's noon altitude in degrees, to one decimal place.",
        seasons(-45, "december-solstice"),
        68.4,
        "In December δ = −23.4°; altitude = 90° − |−45° − (−23.4°)| = 90° − 21.6° = 68.4°.",
        "°",
        0.05,
      ),
      item(
        "mixed-hubble",
        10,
        "With H₀ = 70 km/s per Mpc, find the recession velocity of a galaxy 150 Mpc away, in km/s.",
        expansion(70, 150),
        10500,
        "v = 70 × 150 = 10,500 km/s.",
        "km/s",
      ),
      item(
        "mixed-moon",
        2,
        "The Moon is 22.15 days past new moon, with a synodic month of 29.53 days. Find the Sun–Earth–Moon angle, measured in the direction of the Moon's motion from new moon, in degrees, to the nearest whole number.",
        moon(22.15),
        270,
        "360° × 22.15/29.53 = 270.0°: the third-quarter Moon.",
        "°",
        0.5,
      ),
      item(
        "mixed-gravity",
        4,
        "Jupiter has GM = 1.267 × 10¹⁷ m³/s² and mean radius 69,911 km. Find the gravitational field at that radius in m/s², to one decimal place.",
        launch("jupiter", 0, 20),
        25.9,
        "g = 1.267 × 10¹⁷ / (6.9911 × 10⁷)² = 25.9 m/s².",
        "m/s²",
        0.05,
      ),
      item(
        "mixed-kepler",
        3,
        "A comet comes within 1 AU of the Sun and reaches 5 AU at its farthest. Find its orbital period in years, to two decimal places, using P² = a³.",
        orbit(3, 2 / 3),
        5.2,
        "The long axis is 1 + 5 = 6 AU, so a = 3 AU and P = √27 = 5.196, about 5.20 years.",
        "years",
        0.006,
      ),
      item(
        "mixed-light",
        6,
        "Star A has 25 L☉ and lies 10 pc away. Star B has 1 L☉ and lies 1 pc away. Find the flux of A divided by the flux of B.",
        light(25, 10, "pc"),
        0.25,
        "F ∝ L/d²: (25/10²) ÷ (1/1²) = 0.25.",
        "",
      ),
      item(
        "mixed-hr",
        8,
        "A star has half the Sun's radius and twice its surface temperature. Find its luminosity in solar units.",
        hr(11544, 0.5),
        4,
        "L = 0.5² × 2⁴ = 0.25 × 16 = 4 L☉.",
        "L☉",
      ),
      item(
        "mixed-cmb",
        11,
        "Using λmax = 2.898 × 10⁻³ m·K / T, find the peak wavelength of a 5.45 K blackbody in millimetres, to two decimal places.",
        blackbody(5.45),
        0.53,
        "2.898 × 10⁻³ / 5.45 = 5.32 × 10⁻⁴ m = 0.53 mm.",
        "mm",
        0.006,
      ),
    ],
  },
  {
    id: "later-applications",
    kind: "transfer",
    title: "Use it a week later",
    description:
      "Twelve new situations after a delay. Use the stated constants and rounding, and keep track of units.",
    requiredLessonIds: required,
    afterCheckId: "mixed-challenge",
    delayDays: 7,
    items: [
      item(
        "later-sky",
        0,
        "From latitude 20° S, a star of declination −50° crosses the meridian. Find its altitude in degrees.",
        sky(-20, -50, 8),
        60,
        "Altitude = 90° − |−20° − (−50°)| = 90° − 30° = 60°.",
        "°",
      ),
      item(
        "later-seasons",
        1,
        "Imagine Earth's tilt were 40°. Find the Sun's noon altitude at 51.5° N at the June solstice, in degrees, to one decimal place.",
        seasons(51.5, "june-solstice", 40),
        78.5,
        "δ = +40°; altitude = 90° − |51.5° − 40°| = 78.5°.",
        "°",
        0.05,
      ),
      item(
        "later-moon",
        2,
        "What percentage of the Moon's visible disc is lit when the Sun–Earth–Moon angle is 150°? Give one decimal place.",
        moon(12.3),
        93.3,
        "(1 − cos 150°)/2 = (1 + 0.866)/2 = 0.933, so 93.3%.",
        "%",
        0.05,
      ),
      item(
        "later-kepler",
        3,
        "Mars orbits the Sun with semi-major axis 1.524 AU. Using P² = a³, find its period in years, to two decimal places.",
        orbit(1.524, 0.093),
        1.88,
        "P = 1.524^1.5 = 1.881 years.",
        "years",
        0.006,
      ),
      item(
        "later-gravity",
        4,
        "A planet has twice Earth's mass and twice Earth's radius. Its surface gravity is what multiple of Earth's?",
        gravity(2, 1, 2),
        0.5,
        "g ∝ M/R² = 2/2² = 0.5 of Earth's.",
        "",
      ),
      item(
        "later-orbit",
        5,
        "The Moon orbits 384,400 km from Earth's centre, and Earth's GM is 3.986 × 10¹⁴ m³/s². Treating the orbit as a circle, find the Moon's speed in km/s, to two decimal places.",
        tides(60.3, true),
        1.02,
        "v = √(3.986 × 10¹⁴ / 3.844 × 10⁸) = 1,018 m/s, about 1.02 km/s.",
        "km/s",
        0.006,
      ),
      item(
        "later-parallax",
        6,
        "A star's parallax is 0.065 arcseconds. Using 1 pc = 3.26 ly, find its distance in light-years, to the nearest whole number.",
        parallax(0.065),
        50,
        "d = 1/0.065 = 15.38 pc; × 3.26 = 50.2, about 50 light-years.",
        "ly",
        0.5,
      ),
      item(
        "later-wien",
        7,
        "Earth's surface averages about 288 K. Using λmax = 2.898 × 10⁻³ m·K / T, find its peak wavelength in micrometres, to one decimal place.",
        blackbody(288),
        10.1,
        "λmax = 2.898 × 10⁻³ / 288 = 1.006 × 10⁻⁵ m = 10.1 µm, in the thermal infrared.",
        "µm",
        0.05,
      ),
      item(
        "later-hr",
        8,
        "A giant has 25 times the Sun's radius and twice its surface temperature. Find its luminosity in solar units.",
        hr(11544, 25),
        10000,
        "L = 25² × 2⁴ = 625 × 16 = 10,000 L☉.",
        "L☉",
      ),
      item(
        "later-life",
        9,
        "Using t ∝ M⁻²·⁵, how many times longer does a 1 M☉ star live on the main sequence than a 3 M☉ star? Give one decimal place.",
        life(3),
        15.6,
        "Ratio = 3²·⁵ = 9 × √3 = 15.6.",
        "",
        0.05,
      ),
      item(
        "later-hubble",
        10,
        "With H₀ = 70 km/s per Mpc, by how many km/s does a galaxy 300 Mpc away recede faster than one 100 Mpc away?",
        expansion(70, 300),
        14000,
        "70 × (300 − 100) = 14,000 km/s.",
        "km/s",
      ),
      item(
        "later-cmb",
        11,
        "The background radiation is now at 2.725 K. If the universe expands so that wavelengths stretch by a further factor of 2, what will its temperature be, in kelvin, to two decimal places?",
        blackbody(2.725),
        1.36,
        "Temperature falls in proportion to the stretch: 2.725/2 = 1.3625, about 1.36 K.",
        "K",
        0.006,
      ),
    ],
  },
];
