import {
  beat,
  card,
  choose,
  gravity,
  launch,
  numeric,
  orbit,
  term,
  tides,
  type TeachingLesson,
} from "./definition.js";

export const orbitLessons: TeachingLesson[] = [
  {
    id: "kepler-laws",
    title: "Kepler's laws",
    summary: "Describe an orbit by its size and shape, and link its period to its semi-major axis.",
    moduleId: "astro-orbits",
    sourceIds: ["astro-kepler", "astro-orbits", "nasa-planets"],
    beats: [
      beat(
        "Ellipses with the Sun at a focus",
        "Kepler's first law: each planet moves on an ellipse with the Sun at one focus. The semi-major axis a is half the longest diameter, and the eccentricity e says how far the focus sits from the centre, as a fraction of a. Closest approach, perihelion, is a(1 − e); the farthest point, aphelion, is a(1 + e). For a = 2 AU and e = 0.6 those are 0.8 AU and 3.2 AU. Earth's e is 0.017, so its distance changes by about 3%.",
        ["a = 2 AU, e = 0.6", orbit(2, 0.6)],
        ["Mars: a = 1.52 AU, e = 0.093", orbit(1.52, 0.093)],
      ),
      beat(
        "Equal areas in equal times",
        "Kepler's second law: the line from Sun to planet sweeps equal areas in equal times. Near the Sun that line is short, so the planet must cover a longer arc in the same time and moves faster. The speeds at the two ends of the long axis are in the inverse ratio of the distances: for a = 2 AU and e = 0.6 the planet is 3.2/0.8 = 4 times faster at perihelion than at aphelion.",
        ["e = 0.6", orbit(2, 0.6)],
        ["e = 0, a circle", orbit(2, 0)],
      ),
      beat(
        "Bigger orbits take longer",
        "Kepler's third law: the square of the period is proportional to the cube of the semi-major axis. With P in years and a in AU around the Sun, P² = a³. An orbit with a = 4 AU has P² = 64, so P = 8 years. The period depends only on a, not on how stretched the ellipse is.",
        ["a = 1 AU", orbit(1, 0.1)],
        ["a = 4 AU", orbit(4, 0.1)],
        ["a = 9 AU", orbit(9, 0.1)],
      ),
      beat(
        "Around a heavier star",
        "Newton showed why the third law holds and what sets its constant. Around a star of M solar masses the law becomes P² = a³/M. A planet 1 AU from a 4-solar-mass star has P² = 1/4, a period of half a year: a stronger pull needs a faster orbit to keep from falling inward.",
        ["Sun-like star", orbit(1, 0.05, 1)],
        ["Star of 4 solar masses", orbit(1, 0.05, 4)],
      ),
    ],
    questions: [
      numeric(
        "An asteroid's orbit has semi-major axis 2 AU and eccentricity 0.6. How close does it come to the Sun, in AU?",
        0.8,
        "Perihelion = a(1 − e) = 2 × (1 − 0.6) = 0.8 AU.",
        [
          "The Sun sits at a focus, a × e from the centre.",
          "Perihelion distance is a(1 − e).",
          "Calculate 2 × (1 − 0.6).",
        ],
        "AU",
      ),
      numeric(
        "For the orbit with a = 2 AU and e = 0.6, the speed at perihelion divided by the speed at aphelion equals the aphelion distance divided by the perihelion distance. Find this ratio.",
        4,
        "Aphelion 3.2 AU ÷ perihelion 0.8 AU = 4. The asteroid moves four times faster at its closest point.",
        [
          "Aphelion is a(1 + e) and perihelion is a(1 − e).",
          "Work out both distances.",
          "Divide 3.2 by 0.8.",
        ],
        "",
      ),
      numeric(
        "An asteroid orbits the Sun with semi-major axis 4 AU. Using P² = a³ (P in years, a in AU), find its period in years.",
        8,
        "P² = 4³ = 64, so P = √64 = 8 years.",
        ["Cube the semi-major axis.", "That gives P².", "Take the square root of 64."],
        "years",
      ),
      numeric(
        "A planet orbits a star of 4 solar masses with a = 1 AU. Using P² = a³/M, find its period in years.",
        0.5,
        "P² = 1³/4 = 0.25, so P = 0.5 years.",
        [
          "Divide a³ by the star's mass in solar masses.",
          "1 cubed is 1.",
          "Take the square root of a quarter.",
        ],
        "years",
      ),
      numeric(
        "Jupiter's orbital period is 11.86 years. Using P² = a³, find its semi-major axis in AU, to two decimal places.",
        5.2,
        "a = P^(2/3) = 11.86^(2/3) = 5.20 AU.",
        ["Square the period to get a³.", "11.86² is about 140.7.", "Take the cube root of that."],
        "AU",
        0.006,
      ),
      term(
        "What name is given to the point of a planet's orbit closest to the Sun?",
        ["perihelion"],
        "Perihelion, from Greek peri (near) and helios (Sun). The farthest point is aphelion.",
        "It begins with the Greek prefix for 'near'.",
      ),
    ],
    cards: [
      card(
        "An asteroid has an orbital period of 27 years. Using P² = a³, find its semi-major axis in AU.",
        9,
        "a³ = 27² = 729, so a = ∛729 = 9 AU.",
        "AU",
      ),
      card(
        "An orbit has semi-major axis 5 AU and eccentricity 0.2. Find its aphelion distance in AU.",
        6,
        "Aphelion = a(1 + e) = 5 × 1.2 = 6 AU.",
        "AU",
      ),
    ],
  },
  {
    id: "newton-gravity",
    title: "Newton's gravitation",
    summary: "Use the inverse-square law of gravity to compare forces and compute surface gravity.",
    moduleId: "astro-orbits",
    sourceIds: ["astro-gravitation", "nasa-earth", "nasa-planets"],
    beats: [
      beat(
        "The inverse square",
        "Newton's law of gravitation: F = GMm/r², with G = 6.674 × 10⁻¹¹ N·m²/kg². Double the separation and the force falls to a quarter; triple it and the force falls to a ninth, 0.111 of its first value. The arrows in the drawing share one scale, so you can watch them shrink.",
        ["Separation 1", gravity(1, 1, 1)],
        ["Separation 2", gravity(1, 1, 2)],
        ["Separation 3", gravity(1, 1, 3)],
      ),
      beat(
        "Both masses count",
        "The force is proportional to the product of the masses. Doubling one mass and tripling the other multiplies the force by 2 × 3 = 6 at the same separation. A body's own mass does not let it escape the pull: twice the mass means twice the force.",
        ["Masses 1 and 1", gravity(1, 1, 2)],
        ["Masses 2 and 3", gravity(2, 3, 2)],
      ),
      beat(
        "Surface gravity from G, M and R",
        "Divide the force on a mass m by m and the field at distance r is g = GM/r². For Earth, GM = 3.986 × 10¹⁴ m³/s² and R = 6,371 km, so g = 3.986 × 10¹⁴ / (6.371 × 10⁶)² = 9.82 m/s². Every falling object gets this acceleration whatever its own mass, which is why a hammer and a feather fall together on the airless Moon.",
        ["Earth", launch("earth", 0, 3)],
        ["The Moon", launch("moon", 0, 1)],
      ),
      beat(
        "Equal and opposite",
        "The same formula gives the pull of Earth on the Moon and of the Moon on Earth: GMm/r² does not care which body you call M. The forces are equal in size and opposite in direction. Earth has 81 times the Moon's mass, so the same force gives Earth one eighty-first of the Moon's acceleration.",
        ["Equal masses", gravity(10, 10, 4)],
        ["Mass ratio 81 to 1", gravity(81, 1, 4)],
      ),
    ],
    questions: [
      numeric(
        "Two bodies are moved from separation r to 3r. By what factor does the gravitational force between them change? Give three decimal places.",
        0.111,
        "Force ∝ 1/r², so it changes by 1/3² = 1/9 = 0.111.",
        [
          "Gravity follows an inverse-square law.",
          "Square the factor by which the distance grew.",
          "Take the reciprocal of 3².",
        ],
        "",
        0.0006,
      ),
      numeric(
        "At a fixed separation, one mass is doubled and the other tripled. By what factor does the gravitational force change?",
        6,
        "F ∝ Mm, so the force changes by 2 × 3 = 6.",
        [
          "The force is proportional to the product of the masses.",
          "Each mass change multiplies the force.",
          "Multiply the two factors.",
        ],
        "",
      ),
      numeric(
        "Earth's GM is 3.986 × 10¹⁴ m³/s² and its radius is 6,371 km. Find g = GM/R² at the surface, in m/s², to two decimal places.",
        9.82,
        "g = 3.986 × 10¹⁴ / (6.371 × 10⁶)² = 3.986 × 10¹⁴ / 4.059 × 10¹³ = 9.82 m/s².",
        [
          "Convert the radius to metres first.",
          "Square 6.371 × 10⁶ m.",
          "Divide GM by that square.",
        ],
        "m/s²",
        0.006,
      ),
      numeric(
        "Earth has 81 times the Moon's mass. Find the ratio of the force Earth exerts on the Moon to the force the Moon exerts on Earth.",
        1,
        "Both forces equal GMm/r², so the ratio is exactly one: equal and opposite.",
        [
          "Write the force on each body with Newton's law.",
          "The two expressions contain the same masses and distance.",
          "Compare GMm/r² with GmM/r².",
        ],
        "",
      ),
      numeric(
        "Mars has GM = 4.283 × 10¹³ m³/s² and radius 3,390 km. Find its surface gravity in m/s², to two decimal places.",
        3.73,
        "g = 4.283 × 10¹³ / (3.39 × 10⁶)² = 4.283 × 10¹³ / 1.149 × 10¹³ = 3.73 m/s².",
        ["Use g = GM/R² with R in metres.", "Square 3.39 × 10⁶.", "Divide GM by that square."],
        "m/s²",
        0.006,
      ),
      choose(
        "Why do a hammer and a feather dropped together on the Moon land together?",
        [
          "The pull on each is proportional to its mass, so the acceleration GM/r² is the same for both",
          "The Moon's gravity does not act on light objects",
          "Heavier objects are pulled less strongly per kilogram",
        ],
        0,
        "Force GMm/r² divided by the object's mass m leaves GM/r², the same for any object at that place. With no air there is no drag to separate them.",
        "Divide the gravitational force by the falling object's own mass.",
      ),
    ],
    cards: [
      card(
        "Two masses are moved from separation r to r/2. By what factor does the gravitational force between them change?",
        4,
        "F ∝ 1/r²; halving r multiplies F by 2² = 4.",
        "",
      ),
      card(
        "Gravity at Earth's surface is 9.82 m/s². Find the field one Earth radius above the surface, in m/s², to three decimal places.",
        2.455,
        "One radius above the surface is 2R from the centre, so g falls by 2² = 4: 9.82/4 = 2.455 m/s².",
        "m/s²",
        0.0006,
      ),
    ],
  },
  {
    id: "orbits-escape-tides",
    title: "Orbits, escape and tides",
    summary: "Compute circular and escape speeds and explain tides as a difference in pull.",
    moduleId: "astro-orbits",
    sourceIds: ["astro-satellites", "astro-tides", "nasa-earth", "nasa-sun", "nasa-moon"],
    beats: [
      beat(
        "Falling around the planet",
        "An orbit is a fall that keeps missing. At distance r from the centre, a horizontal speed v = √(GM/r) curves away from a straight line exactly as fast as gravity pulls inward, so the path closes into a circle. At 400 km up, r = 6,771 km and v = 7.67 km/s. Slower, the path dips into the atmosphere and the ground; faster, it stretches into an ellipse.",
        ["5 km/s at 400 km", launch("earth", 400, 5)],
        ["7.67 km/s at 400 km", launch("earth", 400, 7.67)],
        ["9.5 km/s at 400 km", launch("earth", 400, 9.5)],
      ),
      beat(
        "Escape speed",
        "Launch fast enough and the path opens out and never returns. That escape speed is v = √(2GM/r), always √2 = 1.414 times the circular speed at the same distance. From Earth's surface it is √(2 × 3.986 × 10¹⁴ / 6.371 × 10⁶) = 11.19 km/s, ignoring air resistance.",
        ["10 km/s from the surface", launch("earth", 0, 10)],
        ["11.5 km/s from the surface", launch("earth", 0, 11.5)],
      ),
      beat(
        "Earth around the Sun",
        "The same formula works for planets around the Sun. With GM☉ = 1.327 × 10²⁰ m³/s² and r = 1 AU = 1.496 × 10¹¹ m, Earth's orbital speed is √(GM/r) = 29.8 km/s, matching NASA's measured mean of 29.78 km/s. Jupiter, 5.2 times farther out, moves √5.2 = 2.3 times more slowly.",
        ["Earth, 1 AU", orbit(1, 0.017)],
        ["Jupiter, 5.2 AU", orbit(5.2, 0.049)],
      ),
      beat(
        "Tides from a difference in pull",
        "The Moon pulls the near ocean harder than Earth's centre, and Earth's centre harder than the far ocean, so the oceans stretch into two bulges and a coast sees two high tides a day. Because it is a difference in pull, the stretch falls as the cube of distance: halve the Moon's distance and its tides grow 2³ = 8 times. The Sun's tide is 0.46 of the Moon's; aligned at new and full moon they add to make spring tides.",
        ["Moon today, Sun aligned", tides(60.3, true)],
        ["Moon today, Sun at right angles", tides(60.3, false)],
        ["Moon at half the distance", tides(30.15, true)],
      ),
    ],
    questions: [
      numeric(
        "Find the circular orbital speed 400 km above Earth, where r = 6,771 km and GM = 3.986 × 10¹⁴ m³/s², in km/s, to two decimal places.",
        7.67,
        "v = √(3.986 × 10¹⁴ / 6.771 × 10⁶) = √(5.887 × 10⁷) = 7,673 m/s = 7.67 km/s.",
        [
          "Use v = √(GM/r) with r in metres.",
          "Divide GM by 6.771 × 10⁶ m.",
          "Take the square root and convert from m/s to km/s.",
        ],
        "km/s",
        0.006,
      ),
      numeric(
        "Find the escape speed from Earth's surface, with R = 6,371 km and GM = 3.986 × 10¹⁴ m³/s², in km/s, to two decimal places.",
        11.19,
        "v = √(2 × 3.986 × 10¹⁴ / 6.371 × 10⁶) = √(1.2513 × 10⁸) = 11,186 m/s = 11.19 km/s.",
        [
          "Use v = √(2GM/r).",
          "Double GM, then divide by the radius in metres.",
          "Take the square root and convert to km/s.",
        ],
        "km/s",
        0.006,
      ),
      numeric(
        "Using v = √(GM/r) with GM☉ = 1.327 × 10²⁰ m³/s² and r = 1.496 × 10¹¹ m, find Earth's orbital speed in km/s, to one decimal place.",
        29.8,
        "v = √(1.327 × 10²⁰ / 1.496 × 10¹¹) = √(8.870 × 10⁸) = 29,783 m/s, about 29.8 km/s.",
        [
          "This is a circular-orbit speed around the Sun.",
          "Divide GM☉ by the distance in metres.",
          "Take the square root, then divide by 1,000.",
        ],
        "km/s",
        0.06,
      ),
      numeric(
        "Tidal stretching falls as the cube of distance. If the Moon were at half its present distance, by what factor would its tides grow?",
        8,
        "Tide ∝ 1/d³, so halving d multiplies the tide by 2³ = 8.",
        [
          "A tide is a difference in pull across Earth.",
          "That difference scales as one over distance cubed.",
          "Cube the factor of 2.",
        ],
        "",
      ),
      numeric(
        "The Moon has GM = 4.90 × 10¹² m³/s² and radius 1,737 km. Find the escape speed from its surface in km/s, to two decimal places.",
        2.38,
        "v = √(2 × 4.90 × 10¹² / 1.737 × 10⁶) = √(5.642 × 10⁶) = 2,375 m/s, about 2.38 km/s.",
        [
          "Escape speed is √(2GM/R).",
          "Convert the radius to metres.",
          "Compute the square root and convert to km/s.",
        ],
        "km/s",
        0.006,
      ),
      choose(
        "Why are the tides largest around new moon and full moon?",
        [
          "The Sun's and the Moon's tidal stretches line up and add",
          "The Moon is always closest to Earth at those phases",
          "Earth spins faster at those phases",
        ],
        0,
        "At new and full moon the Sun, Earth and Moon are in line, so the solar tide (0.46 of the lunar tide) adds to the Moon's: spring tides. At the quarters they partly cancel: neap tides.",
        "Think about where the Sun lies relative to the Earth–Moon line at those phases.",
      ),
    ],
    cards: [
      card(
        "Escape speed is how many times the circular orbital speed at the same distance? Give three decimal places.",
        1.414,
        "√(2GM/r) ÷ √(GM/r) = √2 = 1.414.",
        "",
        0.0006,
      ),
      card(
        "A satellite circles Earth at r = 42,164 km, where GM = 3.986 × 10¹⁴ m³/s². Find its speed in km/s, to two decimal places.",
        3.07,
        "v = √(3.986 × 10¹⁴ / 4.2164 × 10⁷) = 3,075 m/s, about 3.07 km/s. This is the geostationary orbit.",
        "km/s",
        0.006,
      ),
    ],
  },
];
