import {
  beat,
  card,
  choose,
  eclipse,
  moon,
  numeric,
  seasons,
  sky,
  term,
  type TeachingLesson,
} from "./definition.js";

export const skyLessons: TeachingLesson[] = [
  {
    id: "turning-sky",
    title: "The turning sky",
    summary:
      "Use latitude and declination to predict where a star climbs, and whether it ever sets.",
    moduleId: "astro-sky",
    sourceIds: ["astro-sky", "astro-earth-sky"],
    beats: [
      beat(
        "The pole stays put",
        "Earth spins about an axis that points at two fixed spots on the sky, the celestial poles, so every star seems to wheel around them. Seen from latitude φ, the raised pole stands exactly φ degrees above the horizon. From Amsterdam at 52° N it is 52° up; on the equator it sits on the horizon; at the North Pole it is overhead. Polaris lies within a degree of the north celestial pole, which is how sailors read their latitude from it.",
        ["Star at +70°, from 52° N", sky(52, 70, 12)],
        ["Star at +20°, from 52° N", sky(52, 20, 12)],
      ),
      beat(
        "Fifteen degrees an hour",
        "Stars complete one circle in 23 hours 56 minutes, the sidereal day. For a night's observing, 360° in 24 hours, or 15° per hour, is close enough. Six hours carries a star a quarter of the way around its daily circle, from rising in the east to crossing the meridian for a star on the celestial equator.",
        ["Six hours", sky(40, 0, 6)],
        ["Twelve hours", sky(40, 0, 12)],
      ),
      beat(
        "Stars that never set",
        "A star stays up all night when even the lowest point of its circle is above the horizon. That lowest point lies 90° − δ below the pole, and the pole stands φ above the horizon, so the star never sets when δ > 90° − φ. From 52° N every star north of declination +38° is circumpolar; from 10° N only stars beyond +80° qualify.",
        ["+70° from 52° N", sky(52, 70, 24)],
        ["+30° from 52° N", sky(52, 30, 24)],
        ["+70° from 10° N", sky(10, 70, 24)],
      ),
      beat(
        "Highest on the meridian",
        "Each star climbs highest as it crosses the meridian, the north–south line through the zenith. Its altitude then is 90° − |φ − δ|. A star at +20° seen from 52° N culminates 58° above the southern horizon. Southern latitudes and declinations take negative signs, and the same rule works unchanged.",
        ["+20° from 52° N", sky(52, 20, 8)],
        ["−60° from 34° S", sky(-34, -60, 8)],
      ),
    ],
    questions: [
      numeric(
        "From latitude 52° N, what is the altitude of the north celestial pole, in degrees?",
        52,
        "The raised celestial pole stands at an altitude equal to the latitude: 52°.",
        [
          "The pole's altitude is tied to where you stand on Earth.",
          "At the equator the pole is on the horizon; at the North Pole it is overhead.",
          "Altitude of the pole equals the observer's latitude.",
        ],
        "°",
      ),
      numeric(
        "The sky turns at about 15° per hour. Through what angle, in degrees, does a star move around its daily circle in 6 hours?",
        90,
        "15° per hour × 6 h = 90°, a quarter of a full circle.",
        [
          "The rate is constant through the night.",
          "Multiply the rate by the time.",
          "Calculate 15 × 6.",
        ],
        "°",
      ),
      numeric(
        "From latitude 52° N, a star is circumpolar when its declination exceeds 90° − φ. What is that smallest declination, in degrees?",
        38,
        "δ > 90° − 52° = 38°. Stars north of +38° never set from 52° N.",
        [
          "The lowest point of the star's circle must stay above the horizon.",
          "The lowest point lies 90° − δ below a pole that is φ high.",
          "Subtract the latitude from 90°.",
        ],
        "°",
      ),
      numeric(
        "A star of declination +20° crosses the meridian as seen from latitude 52° N. What is its altitude then, in degrees?",
        58,
        "Altitude = 90° − |52° − 20°| = 58°, due south.",
        [
          "The highest altitude comes on the meridian.",
          "Use 90° − |φ − δ|.",
          "Find the difference between latitude and declination, then subtract it from 90°.",
        ],
        "°",
      ),
      numeric(
        "Seen from latitude 30° N, a star of declination −10° crosses the meridian. Find its altitude in degrees.",
        50,
        "Altitude = 90° − |30° − (−10°)| = 90° − 40° = 50°.",
        [
          "A southern declination enters with a minus sign.",
          "The difference φ − δ is 30 − (−10).",
          "Subtract that difference from 90°.",
        ],
        "°",
      ),
      term(
        "What single word names a star that never sets as seen from a given latitude?",
        ["circumpolar"],
        "Circumpolar: its whole daily circle stays above the horizon around the celestial pole.",
        "The star's circle stays around the pole without dipping below the horizon.",
      ),
    ],
    cards: [
      card(
        "From latitude 41° N, how many degrees above the horizon is the north celestial pole?",
        41,
        "The pole's altitude equals the latitude: 41°.",
        "°",
      ),
      card(
        "At 15° per hour, how many hours does the sky take to turn through 135°?",
        9,
        "135° ÷ 15° per hour = 9 hours.",
        "h",
      ),
    ],
  },
  {
    id: "seasons",
    title: "Why the seasons change",
    summary: "Explain the seasons from Earth's tilt and calculate the noon height of the Sun.",
    moduleId: "astro-sky",
    sourceIds: ["astro-seasons", "nasa-earth"],
    beats: [
      beat(
        "A tilted axis that keeps its direction",
        "Earth's axis is tilted 23.4° from upright to its orbit and keeps pointing the same way in space. Around 21 June the northern hemisphere leans towards the Sun and the Sun's declination reaches +23.4°; around 21 December it reaches −23.4°. The noon Sun stands at 90° − |φ − δ|. In London, at 51.5° N, that is 90 − 28.1 = 61.9° in June.",
        ["London in June", seasons(51.5, "june-solstice")],
        ["London in December", seasons(51.5, "december-solstice")],
      ),
      beat(
        "Low sunlight spreads thin",
        "In December the London noon Sun climbs only 90 − 74.9 = 15.1°. A beam arriving at altitude h covers 1/sin h times the ground it would cover from overhead: 3.8 times at 15.1° against 1.13 times at 61.9°. Days are shorter too, about 7.6 hours of daylight in December against 16.4 hours in June, so the ground gains far less energy.",
        ["December noon", seasons(51.5, "december-solstice")],
        ["June noon", seasons(51.5, "june-solstice")],
      ),
      beat(
        "Equinoxes",
        "At the March and September equinoxes the Sun sits on the celestial equator, declination 0°. Day and night are then close to 12 hours everywhere, and the noon Sun stands at 90° − φ. From 40° N that is 50°; from the equator the Sun passes straight overhead.",
        ["March, 40° N", seasons(40, "march-equinox")],
        ["March, equator", seasons(0, "march-equinox")],
      ),
      beat(
        "If the tilt changed",
        "With no tilt, the Sun's declination would stay at 0° and London's noon Sun would sit at 38.5° all year: no seasons from geometry. A 40° tilt would swing it between 78.5° and −1.5°, below the horizon at midwinter noon. Distance plays little part: Earth is closest to the Sun in early January, and its distance varies by only about 3%.",
        ["Tilt 23.4°", seasons(51.5, "june-solstice", 23.4)],
        ["Tilt 0°", seasons(51.5, "june-solstice", 0)],
        ["Tilt 40°", seasons(51.5, "december-solstice", 40)],
      ),
    ],
    questions: [
      numeric(
        "London lies at 51.5° N. Taking Earth's tilt as 23.4°, find the Sun's noon altitude at the June solstice, in degrees, to one decimal place.",
        61.9,
        "At the June solstice δ = +23.4°. Altitude = 90° − |51.5° − 23.4°| = 90° − 28.1° = 61.9°.",
        [
          "At the June solstice the Sun's declination equals the tilt, north of the equator.",
          "Use 90° − |φ − δ|.",
          "Find 51.5 − 23.4 first, then subtract it from 90.",
        ],
        "°",
        0.05,
      ),
      numeric(
        "Find the Sun's noon altitude in London (51.5° N) at the December solstice, with a tilt of 23.4°, to one decimal place.",
        15.1,
        "At the December solstice δ = −23.4°. Altitude = 90° − |51.5° + 23.4°| = 90° − 74.9° = 15.1°.",
        [
          "In December the Sun's declination is south of the equator, so it is negative.",
          "φ − δ becomes 51.5 − (−23.4).",
          "Subtract that sum from 90°.",
        ],
        "°",
        0.05,
      ),
      numeric(
        "At an equinox the Sun's declination is 0°. Find the noon altitude of the Sun from latitude 40° N, in degrees.",
        50,
        "Altitude = 90° − |40° − 0°| = 50°.",
        ["Set δ to zero.", "The rule reduces to 90° − φ.", "Subtract the latitude from 90°."],
        "°",
      ),
      numeric(
        "Imagine Earth had no axial tilt. What would the Sun's noon altitude be in London (51.5° N) on every date, in degrees, to one decimal place?",
        38.5,
        "With no tilt δ = 0° all year, so the noon altitude is always 90° − 51.5° = 38.5°.",
        [
          "Without tilt the Sun never leaves the celestial equator.",
          "Its declination is zero on every date.",
          "Subtract the latitude from 90°.",
        ],
        "°",
        0.05,
      ),
      numeric(
        "At what northern latitude, in degrees, is the noon Sun directly overhead at the June solstice, taking Earth's tilt as 23.4°? Give one decimal place.",
        23.4,
        "Overhead means altitude 90°, so |φ − δ| = 0 and φ = δ = 23.4° N, the Tropic of Cancer.",
        [
          "Directly overhead means an altitude of 90°.",
          "Set 90° − |φ − δ| equal to 90°.",
          "The latitude must match the Sun's declination on that date.",
        ],
        "°",
        0.05,
      ),
      choose(
        "Earth is closest to the Sun in early January. Why is it winter in the northern hemisphere then?",
        [
          "The northern hemisphere tilts away from the Sun, so sunlight arrives low and days are short",
          "The Sun gives out less energy in January",
          "Earth's orbit carries it farthest from the Sun in January",
        ],
        0,
        "Seasons follow the tilt. In January the north leans away from the Sun: a low noon Sun spreads its energy thinly over short days, while the 3% change in distance matters little.",
        "Compare the two hemispheres: they have opposite seasons at the same distance from the Sun.",
      ),
    ],
    cards: [
      card(
        "At latitude 35° N, with Earth's tilt taken as 23.4°, find the Sun's noon altitude at the December solstice, in degrees, to one decimal place.",
        31.6,
        "δ = −23.4°, so altitude = 90° − |35° + 23.4°| = 31.6°.",
        "°",
        0.05,
      ),
      card(
        "At latitude 60° N on an equinox, what is the Sun's noon altitude in degrees?",
        30,
        "δ = 0°, so the noon altitude is 90° − 60° = 30°.",
        "°",
      ),
    ],
  },
  {
    id: "moon-and-eclipses",
    title: "Phases and eclipses",
    summary:
      "Relate the Moon's phase to the Sun–Earth–Moon angle and explain when eclipses happen.",
    moduleId: "astro-sky",
    sourceIds: ["astro-moon", "astro-eclipses", "nasa-moon"],
    beats: [
      beat(
        "Always half lit",
        "Sunlight always lights one half of the Moon. The phase records how much of that lit half faces Earth. If θ is the angle between Sun and Moon as seen from Earth, the lit fraction of the disc is (1 − cos θ)/2: zero at new moon, one half at θ = 90°, and the whole disc at full moon, when θ = 180°.",
        ["First quarter", moon(7.38)],
        ["Crescent", moon(3)],
      ),
      beat(
        "A 29.5-day cycle",
        "From one new moon to the next takes 29.53 days, the synodic month. In that time the Moon gains a full 360° on the Sun, about 12.2° a day, so it rises roughly 50 minutes later each night. First quarter comes 7.38 days after new moon and stands highest around sunset; full moon rises as the Sun sets.",
        ["New moon", moon(0)],
        ["Full moon", moon(14.77)],
        ["Waning gibbous", moon(19)],
      ),
      beat(
        "Why not every month",
        "The Moon's orbit is tilted 5.1° to the ecliptic, the plane of Earth's orbit. Most full moons pass north or south of Earth's shadow, and most new moons cast their shadow above or below Earth. A lunar eclipse needs a full moon close to the ecliptic, within about 1° in this model, so that the Moon passes through Earth's shadow.",
        ["Full moon on the ecliptic", eclipse("full", 0.4)],
        ["Full moon 4.5° north", eclipse("full", 4.5)],
      ),
      beat(
        "The same size in the sky",
        "For small angles, angular size in radians is diameter divided by distance; multiply by 57.3 for degrees. The Moon, 3,475 km across at 384,400 km, spans 0.52°. The Sun, 400 times wider and about 390 times farther, spans 0.53°. That near match lets a new moon on the ecliptic just cover the Sun's bright disc in a total solar eclipse.",
        ["New moon on the ecliptic", eclipse("new", 0.2)],
        ["New moon 3° south", eclipse("new", -3)],
      ),
    ],
    questions: [
      numeric(
        "When the Sun–Earth–Moon angle is 90°, what percentage of the Moon's visible disc is lit?",
        50,
        "Lit fraction = (1 − cos 90°)/2 = (1 − 0)/2, half the disc.",
        [
          "Use lit fraction = (1 − cos θ)/2.",
          "The cosine of 90° is zero.",
          "Convert the fraction to a percentage.",
        ],
        "%",
      ),
      numeric(
        "The synodic month is 29.53 days. How many degrees per day does the Moon gain on the Sun? Give one decimal place.",
        12.2,
        "360° ÷ 29.53 days = 12.19°, about 12.2° per day.",
        [
          "In one synodic month the Moon gains one full turn on the Sun.",
          "A full turn is 360°.",
          "Divide 360 by the number of days.",
        ],
        "°/day",
        0.05,
      ),
      term(
        "At which phase of the Moon can a lunar eclipse happen? Answer with one word.",
        ["full"],
        "Full: Earth must sit between the Sun and the Moon so the Moon can pass through Earth's shadow.",
        "Earth's shadow points directly away from the Sun.",
      ),
      numeric(
        "The Moon is 3,475 km across and 384,400 km away. Find its angular diameter in degrees, to two decimal places, using angle ≈ diameter/distance and 1 radian = 57.3°.",
        0.52,
        "3,475/384,400 = 0.00904 rad; × 57.3 = 0.518°, which rounds to 0.52°.",
        [
          "Divide the diameter by the distance to get radians.",
          "Convert radians to degrees with the factor 57.3.",
          "Round the result to two decimal places.",
        ],
        "°",
        0.006,
      ),
      numeric(
        "How many days after new moon is first quarter, taking the synodic month as 29.53 days? Give two decimal places.",
        7.38,
        "First quarter is a quarter of the cycle: 29.53 ÷ 4 = 7.3825, about 7.38 days.",
        [
          "First quarter is a Sun–Earth–Moon angle of 90°.",
          "That is one quarter of the full cycle.",
          "Divide the synodic month by 4.",
        ],
        "days",
        0.006,
      ),
      numeric(
        "What percentage of the Moon's visible disc is lit when the Sun–Earth–Moon angle is 120°?",
        75,
        "(1 − cos 120°)/2 = (1 + 0.5)/2 = 0.75 of the disc.",
        [
          "Use (1 − cos θ)/2.",
          "The cosine of 120° is −0.5.",
          "Convert the fraction to a percentage.",
        ],
        "%",
      ),
    ],
    cards: [
      card(
        "What percentage of the Moon's visible disc is lit when the Sun–Earth–Moon angle is 60°?",
        25,
        "(1 − cos 60°)/2 = (1 − 0.5)/2 = 0.25, a quarter of the disc.",
        "%",
      ),
      card(
        "The Sun is 1.39 million km across and 149.6 million km away. Find its angular diameter in degrees, to two decimal places, using 1 radian = 57.3°.",
        0.53,
        "1.39/149.6 = 0.00929 rad; × 57.3 = 0.532°, about 0.53°.",
        "°",
        0.006,
      ),
    ],
  },
];
