import {
  beat,
  blackbody,
  card,
  choose,
  doppler,
  hr,
  light,
  numeric,
  parallax,
  term,
  type TeachingLesson,
} from "./definition.js";

export const starlightLessons: TeachingLesson[] = [
  {
    id: "brightness-and-distance",
    title: "Brightness and distance",
    summary: "Apply the inverse-square law to starlight and measure distance by parallax.",
    moduleId: "astro-light",
    sourceIds: ["astro-brightness", "astro-parallax", "nasa-sun"],
    beats: [
      beat(
        "Light spreads over a sphere",
        "A star's luminosity L, its total power output, spreads over a sphere of area 4πd² at distance d. The flux F = L/(4πd²) is the power arriving on each square metre. At twice the distance the same light covers four times the area, so the flux drops to a quarter; at three times, to a ninth.",
        ["1 AU", light(1, 1)],
        ["2 AU", light(1, 2)],
        ["3 AU", light(1, 3)],
      ),
      beat(
        "Sunlight at Earth",
        "The Sun's luminosity is 3.828 × 10²⁶ W. At 1 AU, 1.496 × 10¹¹ m, that power is shared over 4π(1.496 × 10¹¹)² = 2.812 × 10²³ m², giving 1,361 W on every square metre facing the Sun above the atmosphere. Mars, at 1.52 AU, receives 1/1.52² = 0.43 of that.",
        ["Earth, 1 AU", light(1, 1)],
        ["Mars, 1.52 AU", light(1, 1.52)],
      ),
      beat(
        "Parallax measures distance",
        "As Earth swings around the Sun, a nearby star shifts against far more distant stars. Half that seasonal shift, measured from a baseline of 1 AU, is the parallax p. A star with p = 1 arcsecond is by definition 1 parsec away, 206,265 AU or 3.26 light-years, and in general d = 1/p parsecs. Proxima Centauri, with p = 0.768″, is 1.30 pc away.",
        ["Proxima Centauri, 0.768″", parallax(0.768)],
        ["A star at 0.1″", parallax(0.1)],
      ),
      beat(
        "Bright because close, or bright because powerful",
        "Apparent brightness alone cannot separate a powerful distant star from a feeble nearby one. Flux is proportional to L/d², so a star 100 times more luminous looks equally bright from √100 = 10 times farther away. Once parallax gives d, the measured flux gives the luminosity: L = 4πd²F.",
        ["100 L☉ at 1 pc", light(100, 1, "pc")],
        ["1 L☉ at 1 pc", light(1, 1, "pc")],
        ["100 L☉ at 4 pc", light(100, 4, "pc")],
      ),
    ],
    questions: [
      numeric(
        "A probe moves from 1 AU to 2 AU from the Sun. What fraction of the solar flux it received at 1 AU does it now receive?",
        0.25,
        "Flux ∝ 1/d², so it falls to 1/2² = 1/4 = 0.25 of its value at 1 AU.",
        [
          "Light spreads over a sphere of area 4πd².",
          "Doubling d multiplies that area by 2².",
          "Take the reciprocal of 2².",
        ],
        "",
      ),
      numeric(
        "The Sun's luminosity is 3.828 × 10²⁶ W. Find the flux at 1 AU = 1.496 × 10¹¹ m, in W/m², to the nearest whole number.",
        1361,
        "F = 3.828 × 10²⁶ / [4π × (1.496 × 10¹¹)²] = 3.828 × 10²⁶ / 2.812 × 10²³ = 1,361 W/m².",
        [
          "Use F = L/(4πd²).",
          "Square the distance in metres, then multiply by 4π.",
          "Divide the luminosity by that area.",
        ],
        "W/m²",
        0.6,
      ),
      numeric(
        "Proxima Centauri's parallax is 0.768 arcseconds. Find its distance in parsecs, to two decimal places.",
        1.3,
        "d = 1/p = 1/0.768 = 1.302 pc, about 1.30 pc (4.25 light-years).",
        [
          "Distance in parsecs is the reciprocal of parallax in arcseconds.",
          "Divide 1 by the parallax.",
          "Round to two decimal places.",
        ],
        "pc",
        0.006,
      ),
      numeric(
        "Star A is 100 times as luminous as star B, yet they appear equally bright. How many times farther away than B is A?",
        10,
        "Equal flux needs L/d² equal, so d grows as √L: √100 = 10 times farther.",
        [
          "Flux is proportional to L/d².",
          "Keep the flux fixed while L grows a hundredfold.",
          "Then d² must grow by the same factor; take the square root.",
        ],
        "",
      ),
      numeric(
        "A star's parallax is 0.05 arcseconds. Find its distance in light-years, to one decimal place, using 1 pc = 3.26 ly.",
        65.2,
        "d = 1/0.05 = 20 pc; 20 × 3.26 = 65.2 light-years.",
        [
          "First convert parallax to parsecs with d = 1/p.",
          "Then multiply by 3.26 light-years per parsec.",
          "Calculate (1/0.05) × 3.26.",
        ],
        "ly",
        0.06,
      ),
      term(
        "What unit of distance is defined as the distance at which a star shows a parallax of one arcsecond?",
        ["parsec", "pc"],
        "The parsec: PARallax of one arcSECond. It equals 206,265 AU or 3.26 light-years.",
        "Its name joins the first syllables of the two words that define it.",
      ),
    ],
    cards: [
      card(
        "A star's parallax is 0.25 arcseconds. Find its distance in parsecs.",
        4,
        "d = 1/p = 1/0.25 = 4 pc.",
        "pc",
      ),
      card(
        "Mars orbits 1.52 AU from the Sun. What fraction of the solar flux at Earth reaches Mars? Give two decimal places.",
        0.43,
        "Flux ∝ 1/d², so 1/1.52² = 1/2.31 = 0.43.",
        "",
        0.006,
      ),
    ],
  },
  {
    id: "colour-and-motion",
    title: "Temperature, colour and motion",
    summary:
      "Read a star's temperature from its colour and its motion from shifted spectral lines.",
    moduleId: "astro-light",
    sourceIds: ["astro-spectrum", "astro-colours", "astro-doppler", "nasa-sun"],
    beats: [
      beat(
        "Hotter glows bluer",
        "A star radiates roughly like a blackbody, whose spectrum has one peak. Wien's law places it at λmax = 2.898 × 10⁻³ m·K / T. The Sun's 5,772 K surface peaks at 502 nm, in the blue-green, but emits across the visible so it looks white. A 3,500 K star peaks in the infrared and looks orange-red; a 20,000 K star peaks in the ultraviolet and looks blue-white.",
        ["3,500 K", blackbody(3500)],
        ["5,772 K", blackbody(5772)],
        ["20,000 K", blackbody(20000)],
      ),
      beat(
        "Temperature from the peak",
        "Run Wien's law backwards to take a star's temperature from a distance: T = 2.898 × 10⁻³ m·K / λmax. A spectrum peaking at 290 nm means T = 2.898 × 10⁻³ / 2.90 × 10⁻⁷ = 9,990 K, close to 10,000 K, like Vega. Hotter objects are also far brighter per square metre: the emitted flux grows as T⁴.",
        ["Peak at 290 nm", blackbody(9993)],
        ["Peak near 966 nm", blackbody(3000)],
      ),
      beat(
        "Lines shift with motion",
        "Atoms absorb and emit at fixed wavelengths, measured in the laboratory. A source moving away stretches its waves to longer wavelengths, a redshift; one approaching shortens them, a blueshift. For speeds well below light's, v = cΔλ/λ. Hydrogen's 656.28 nm line seen at 662.84 nm shifts by 6.56 nm, so the source recedes at 3.00 × 10⁵ × 6.56/656.28 = 3,000 km/s.",
        ["Receding at 3,000 km/s", doppler(656.28, 3000)],
        ["Approaching at 3,000 km/s", doppler(656.28, -3000)],
      ),
      beat(
        "Small speeds, small shifts",
        "Stars in our galaxy move at tens to hundreds of kilometres per second, so their shifts are a fraction of a nanometre and need a good spectrograph. A star approaching at 150 km/s shifts a 500.00 nm line by 500 × 150/300,000 = 0.25 nm towards the blue. Only the motion along the line of sight shows up; sideways motion produces no first-order shift.",
        ["Approaching at 150 km/s", doppler(500, -150)],
        ["Receding at 6,000 km/s", doppler(500, 6000)],
      ),
    ],
    questions: [
      numeric(
        "Using Wien's law λmax = 2.898 × 10⁻³ m·K / T, find the peak wavelength of the Sun (T = 5,772 K) in nanometres, to the nearest whole number.",
        502,
        "λmax = 2.898 × 10⁻³ / 5,772 = 5.021 × 10⁻⁷ m = 502 nm.",
        [
          "Divide Wien's constant by the temperature.",
          "The result comes out in metres.",
          "Multiply by 10⁹ to convert metres to nanometres.",
        ],
        "nm",
        0.6,
      ),
      numeric(
        "A star's spectrum peaks at 290 nm. Find its surface temperature in kelvin, to the nearest hundred.",
        10000,
        "T = 2.898 × 10⁻³ / 2.90 × 10⁻⁷ = 9,993 K, which is 10,000 K to the nearest hundred.",
        [
          "Rearrange Wien's law for T.",
          "Write the peak wavelength in metres.",
          "Divide the constant by that wavelength, then round.",
        ],
        "K",
        50,
      ),
      numeric(
        "A hydrogen line with laboratory wavelength 656.28 nm is observed at 662.84 nm. Using v = cΔλ/λ with c = 3.00 × 10⁵ km/s, find the radial velocity in km/s, to the nearest ten (positive means receding).",
        3000,
        "Δλ = 6.56 nm; v = 3.00 × 10⁵ × 6.56/656.28 = 2,999 km/s, which is 3,000 km/s to the nearest ten, receding.",
        [
          "Find the shift: observed minus laboratory wavelength.",
          "Divide the shift by the laboratory wavelength.",
          "Multiply by the speed of light in km/s.",
        ],
        "km/s",
        5,
      ),
      numeric(
        "A star approaches at 150 km/s. Find the shift of its 500.00 nm line in nanometres, with redshift positive and blueshift negative, to three decimal places. Take c = 3.00 × 10⁵ km/s.",
        -0.25,
        "Δλ = λv/c = 500 × (−150)/300,000 = −0.250 nm, a blueshift.",
        [
          "An approaching source has a negative radial velocity.",
          "Use Δλ = λv/c.",
          "Multiply 500 by −150, then divide by 300,000.",
        ],
        "nm",
        0.0006,
      ),
      choose(
        "Betelgeuse looks orange-red and Rigel looks blue-white. What does the difference tell you?",
        [
          "Betelgeuse's surface is cooler, so its spectrum peaks at longer wavelengths",
          "Betelgeuse is moving away from us much faster than Rigel",
          "Betelgeuse is farther away, so its light has reddened on the way",
        ],
        0,
        "Colour tracks surface temperature through Wien's law: about 3,600 K for Betelgeuse against about 12,000 K for Rigel. Their radial speeds are far too small to change a colour.",
        "Which property of a glowing body sets where its spectrum peaks?",
      ),
      numeric(
        "A red dwarf has a surface temperature of 3,000 K. Find its peak wavelength in nanometres, to the nearest whole number.",
        966,
        "λmax = 2.898 × 10⁻³ / 3,000 = 9.66 × 10⁻⁷ m = 966 nm, in the near infrared.",
        ["Use λmax = 2.898 × 10⁻³ m·K / T.", "Divide by 3,000 K.", "Convert metres to nanometres."],
        "nm",
        0.6,
      ),
    ],
    cards: [
      card(
        "A star's surface temperature is 14,000 K. Using λmax = 2.898 × 10⁻³ m·K / T, find its peak wavelength in nanometres, to the nearest whole number.",
        207,
        "2.898 × 10⁻³ / 14,000 = 2.07 × 10⁻⁷ m = 207 nm, in the ultraviolet.",
        "nm",
        0.6,
      ),
      card(
        "A galaxy's 500.0 nm line is observed at 503.0 nm. Using c = 3.00 × 10⁵ km/s, find its recession speed in km/s.",
        1800,
        "v = 3.00 × 10⁵ × 3.0/500.0 = 1,800 km/s.",
        "km/s",
        0.5,
      ),
    ],
  },
  {
    id: "hr-diagram",
    title: "The H–R diagram",
    summary:
      "Relate luminosity, radius and temperature, and read a star's size from its place on the diagram.",
    moduleId: "astro-light",
    sourceIds: ["astro-hr", "astro-colours", "nasa-sun"],
    beats: [
      beat(
        "Luminosity from size and temperature",
        "Each square metre of a star's surface emits σT⁴, and the surface has area 4πR². So L = 4πR²σT⁴, or in solar units L = R²(T/5,772 K)⁴. A star of the Sun's size at twice its temperature emits 2⁴ = 16 times as much. Temperature is a powerful lever.",
        ["The Sun", hr(5772, 1)],
        ["Same size, twice as hot", hr(11544, 1)],
      ),
      beat(
        "Big and cool",
        "Plot luminosity against temperature with hot stars on the left, and the stars fall into groups. Most lie on the main sequence, the diagonal band. Up and to the right sit cool stars so luminous they must be enormous. A 3,600 K red supergiant 760 times the Sun's radius has L = 760² × (3,600/5,772)⁴ = 87,000 L☉.",
        ["Red supergiant", hr(3600, 760)],
        ["The Sun", hr(5772, 1)],
      ),
      beat(
        "Small and hot",
        "Down in the lower left lie white dwarfs: hot but dim, so they must be tiny. One of radius 0.01 R☉ (about Earth's size) at four times the Sun's temperature has L = 0.01² × 4⁴ = 0.0256 L☉. The dashed lines on the diagram mark constant radius.",
        ["White dwarf", hr(23088, 0.01)],
        ["Sirius A", hr(9940, 1.71)],
      ),
      beat(
        "Reading the diagram",
        "Two stars at the same temperature emit the same power per square metre, so a difference in luminosity must come from surface area. A star 100 times more luminous than another of equal temperature has √100 = 10 times its radius. Height on the diagram at a fixed temperature is a measure of size.",
        ["Main-sequence star at 4,300 K", hr(4300, 0.75)],
        ["Giant at 4,300 K", hr(4300, 25)],
      ),
    ],
    questions: [
      numeric(
        "A star has the Sun's radius but twice the Sun's surface temperature. How many times the Sun's luminosity does it emit?",
        16,
        "L = R²(T/T☉)⁴ = 1² × 2⁴ = 16 L☉.",
        [
          "Use L = R²(T/T☉)⁴ in solar units.",
          "The radius factor is one.",
          "Raise the temperature ratio to the fourth power.",
        ],
        "L☉",
      ),
      numeric(
        "A red supergiant has a surface temperature of 3,600 K and a radius of 760 R☉. With T☉ = 5,772 K, find its luminosity in solar units, to the nearest thousand.",
        87000,
        "L = 760² × (3,600/5,772)⁴ = 577,600 × 0.1513 = 87,400 L☉, which is 87,000 L☉ to the nearest thousand.",
        [
          "Square the radius in solar radii.",
          "Raise 3,600/5,772 to the fourth power.",
          "Multiply the two results, then round.",
        ],
        "L☉",
        500,
      ),
      numeric(
        "A white dwarf has radius 0.01 R☉ and a surface temperature four times the Sun's. Find its luminosity in solar units, to four decimal places.",
        0.0256,
        "L = 0.01² × 4⁴ = 0.0001 × 256 = 0.0256 L☉.",
        [
          "Square the radius.",
          "Raise the temperature factor to the fourth power.",
          "Multiply 0.0001 by 256.",
        ],
        "L☉",
        0.00006,
      ),
      term(
        "Two stars have the same surface temperature, but one is far more luminous. Which property of the luminous star must be larger? Answer in one word.",
        ["radius", "size", "diameter", "surface area"],
        "Its radius. Equal temperature means equal power per square metre, so more luminosity needs more surface area.",
        "Write L = 4πR²σT⁴ and hold T fixed.",
      ),
      numeric(
        "Two stars have equal temperatures; one is 100 times as luminous as the other. How many times larger is its radius?",
        10,
        "With T fixed, L ∝ R², so R grows as √100 = 10.",
        [
          "Hold T constant in L ∝ R²T⁴.",
          "Luminosity then scales as radius squared.",
          "Take the square root of the luminosity ratio.",
        ],
        "",
      ),
      numeric(
        "A star twice the Sun's radius has a luminosity of 4 L☉. Taking T☉ = 5,772 K, find its surface temperature in kelvin.",
        5772,
        "4 = 2² × (T/T☉)⁴ gives (T/T☉)⁴ = 1, so T equals the Sun's temperature: 5,772 K.",
        [
          "Write L = R²(T/T☉)⁴ and substitute R = 2.",
          "Divide both sides by R².",
          "Find what temperature ratio raised to the fourth power gives the result.",
        ],
        "K",
        1,
      ),
    ],
    cards: [
      card(
        "A star has three times the Sun's radius and the Sun's surface temperature. Find its luminosity in solar units.",
        9,
        "L = 3² × 1⁴ = 9 L☉.",
        "L☉",
      ),
      card(
        "A star has half the Sun's surface temperature and exactly the Sun's luminosity. Find its radius in solar radii.",
        4,
        "1 = R² × (1/2)⁴ = R²/16, so R² = 16 and R = 4 R☉.",
        "R☉",
      ),
    ],
  },
];
