import type {
  CourseCheckDefinition,
  GeometryShape,
} from "../../../packages/contracts/src/index.js";
import {
  angle,
  triangleAngles,
  rect,
  triangle,
  para,
  trapezoid,
  cutout,
  circle,
  similar,
  right,
  distance,
  prism,
} from "./definition.js";
import { geometryLessons } from "./lessons.js";
function item(
  id: string,
  lessonIndex: number,
  prompt: string,
  shape: GeometryShape,
  value: number,
  workedAnswer: string,
): CourseCheckDefinition["items"][number] {
  const lesson = geometryLessons[lessonIndex]!;
  return {
    lessonId: lesson.id,
    visual: { type: "geometry", shape },
    question: {
      id: "geo-check-" + id,
      conceptIds: ["geo-" + lesson.id],
      sourceIds: lesson.sourceIds,
      prompt,
      responseType: "numeric",
      difficulty: 1,
      hints: [],
      answerAuthority: {
        kind: "numeric",
        value,
        unit: "",
        absoluteTolerance: 1e-6,
        relativeTolerance: 0,
        workedAnswer,
      },
    },
  };
}
const required = geometryLessons.map((l) => l.id);
export const geometryChecks: CourseCheckDefinition[] = [
  {
    id: "starting-point",
    kind: "placement",
    title: "Find your starting point",
    description:
      "Twelve problems across angles, shapes, scale and space. Find the lessons that will help you.",
    requiredLessonIds: [],
    items: [
      item(
        "placement-turn",
        0,
        "One part of a straight angle is 143°. Find the other part in degrees.",
        angle(143),
        37,
        "A straight angle is 180°; 180 − 143 = 37°.",
      ),
      item(
        "placement-triangle",
        1,
        "A triangle has angles 52° and 71°. Find its third angle in degrees.",
        triangleAngles(52, 71),
        57,
        "180 − 52 − 71 = 57°.",
      ),
      item(
        "placement-rectangle",
        2,
        "A rectangle is 8 cm by 3 cm. Find its area in square centimetres.",
        rect(8, 3),
        24,
        "Area = 8 × 3 = 24 cm².",
      ),
      item(
        "placement-height",
        3,
        "A triangle has base 9 cm and perpendicular height 4 cm. Find its area in square centimetres.",
        triangle(9, 4, 0.6),
        18,
        "Area = 9 × 4 / 2 = 18 cm².",
      ),
      item(
        "placement-cutout",
        4,
        "A 10 m by 7 m rectangle has a 2 m by 3 m corner removed. Find the remaining area in square metres.",
        cutout(10, 7, 2, 3),
        64,
        "10 × 7 − 2 × 3 = 64 m².",
      ),
      item(
        "placement-circle",
        5,
        "A circle has radius 4 cm. Use π ≈ 3.14 to find its circumference in centimetres.",
        circle(4),
        25.12,
        "Circumference = 2 × 3.14 × 4 = 25.12 cm.",
      ),
      item(
        "placement-scale",
        6,
        "A 6 cm by 4 cm rectangle is enlarged by length scale factor 1.5. Find the new width corresponding to 6 cm.",
        similar(6, 4, 1.5),
        9,
        "The corresponding width is 6 × 1.5 = 9 cm.",
      ),
      item(
        "placement-area-scale",
        7,
        "A 2 cm by 5 cm rectangle has every length tripled. Find the enlarged area in square centimetres.",
        similar(2, 5, 3),
        90,
        "Original area 10 multiplied by 3² gives 90 cm².",
      ),
      item(
        "placement-right",
        8,
        "A right triangle has legs 12 cm and 16 cm. Find its hypotenuse in centimetres.",
        right(12, 16),
        20,
        "√(12² + 16²) = √400 = 20 cm.",
      ),
      item(
        "placement-distance",
        9,
        "Find the direct distance between (−2, 0) and (1, 4), in grid units.",
        distance(-2, 0, 1, 4),
        5,
        "The separations are 3 and 4; √(3² + 4²) = 5.",
      ),
      item(
        "placement-volume",
        10,
        "A box has inside dimensions 7 cm by 2 cm by 4 cm. Find its volume in cubic centimetres.",
        prism(7, 2, 4),
        56,
        "7 × 2 × 4 = 56 cm³.",
      ),
      item(
        "placement-surface",
        11,
        "A closed cube has side length 3 cm. Find its total surface area in square centimetres.",
        prism(3, 3, 3),
        54,
        "Six square faces give 6 × 3² = 54 cm².",
      ),
    ],
  },
  {
    id: "mixed-challenge",
    kind: "checkpoint",
    title: "Bring the ideas together",
    description:
      "Twelve mixed problems. Choose the method, record your confidence and check your reasoning at the end.",
    requiredLessonIds: required,
    items: [
      item(
        "mixed-turn",
        0,
        "A pointer has turned 212°. How many more degrees complete one full turn?",
        angle(212, 360),
        148,
        "360 − 212 = 148°.",
      ),
      item(
        "mixed-perimeter",
        2,
        "A rectangle measures 12 m by 5 m. Find its perimeter in metres.",
        rect(12, 5),
        34,
        "2 × (12 + 5) = 34 m.",
      ),
      item(
        "mixed-trapezoid",
        4,
        "A trapezoid has parallel bases 12 cm and 8 cm, with perpendicular height 3 cm. Find its area in square centimetres.",
        trapezoid(12, 8, 3),
        30,
        "(12 + 8) × 3 / 2 = 30 cm².",
      ),
      item(
        "mixed-scale",
        6,
        "A 7 cm by 4 cm rectangle is reduced by length scale factor 0.5. Find the side corresponding to 7 cm.",
        similar(7, 4, 0.5),
        3.5,
        "7 × 0.5 = 3.5 cm.",
      ),
      item(
        "mixed-right",
        8,
        "A right triangle has legs 10 m and 24 m. Find its hypotenuse in metres.",
        right(10, 24),
        26,
        "√(10² + 24²) = √676 = 26 m.",
      ),
      item(
        "mixed-volume",
        10,
        "A rectangular container has inside dimensions 9 cm by 4 cm by 2 cm. Find its volume in cubic centimetres.",
        prism(9, 4, 2),
        72,
        "9 × 4 × 2 = 72 cm³.",
      ),
      item(
        "mixed-triangle",
        1,
        "A triangle has interior angles 31° and 93°. Find its third angle in degrees.",
        triangleAngles(31, 93),
        56,
        "180 − 31 − 93 = 56°.",
      ),
      item(
        "mixed-height",
        3,
        "A parallelogram has base 9 cm and perpendicular height 4 cm. Find its area in square centimetres.",
        para(9, 4, 0.4),
        36,
        "Base times perpendicular height gives 9 × 4 = 36 cm².",
      ),
      item(
        "mixed-circle",
        5,
        "A disc has radius 2.5 cm. Use π ≈ 3.14 to find its area in square centimetres.",
        circle(2.5),
        19.625,
        "3.14 × 2.5² = 3.14 × 6.25 = 19.625 cm².",
      ),
      item(
        "mixed-area-scale",
        7,
        "A 5 cm by 4 cm rectangle has every length multiplied by 1.5. Find the new area in square centimetres.",
        similar(5, 4, 1.5),
        45,
        "Original area 20 multiplied by 1.5² gives 45 cm².",
      ),
      item(
        "mixed-distance",
        9,
        "Find the direct distance between (−4, −3) and (1, 9), in grid units.",
        distance(-4, -3, 1, 9),
        13,
        "The differences are 5 and 12; √(5² + 12²) = 13.",
      ),
      item(
        "mixed-surface",
        11,
        "A closed box is 6 cm by 4 cm by 2 cm. Find its total surface area in square centimetres.",
        prism(6, 4, 2),
        88,
        "2 × (6 × 4 + 6 × 2 + 4 × 2) = 88 cm².",
      ),
    ],
  },
  {
    id: "later-transfer",
    kind: "transfer",
    title: "Use it in a new setting",
    description:
      "Return after seven days for twelve fresh applications, from building plans to packaging.",
    requiredLessonIds: required,
    afterCheckId: "mixed-challenge",
    delayDays: 7,
    items: [
      item(
        "transfer-corner",
        0,
        "A hinged sign has turned 28° from closed. How many more degrees would make a right-angle opening?",
        angle(28, 90),
        62,
        "A right angle is 90°; 90 − 28 = 62°.",
      ),
      item(
        "transfer-frame",
        1,
        "Two interior angles of a triangular support are 46° and 79°. Find the third angle in degrees.",
        triangleAngles(46, 79),
        55,
        "180 − 46 − 79 = 55°.",
      ),
      item(
        "transfer-fence",
        2,
        "A rectangular garden is 11 m by 6 m. Find the fencing length for all four sides, in metres.",
        rect(11, 6),
        34,
        "The boundary is 2 × (11 + 6) = 34 m.",
      ),
      item(
        "transfer-sail",
        3,
        "A triangular sail has base 14 m and perpendicular height 9 m. Find its area in square metres.",
        triangle(14, 9, 0.1),
        63,
        "14 × 9 / 2 = 63 m².",
      ),
      item(
        "transfer-floor",
        4,
        "A 14 m by 9 m floor plan has a 4 m by 2 m corner cutout. Find the area needing flooring, in square metres.",
        cutout(14, 9, 4, 2),
        118,
        "14 × 9 − 4 × 2 = 118 m².",
      ),
      item(
        "transfer-trim",
        5,
        "A circular display has radius 7 cm. Use π ≈ 3.14 to find the trim length around its edge, in centimetres.",
        circle(7),
        43.96,
        "Trim follows the circumference: 2 × 3.14 × 7 = 43.96 cm.",
      ),
      item(
        "transfer-model",
        6,
        "A model part 8 cm wide and 3 cm high is enlarged by scale factor 2.5. Find its new width in centimetres.",
        similar(8, 3, 2.5),
        20,
        "8 × 2.5 = 20 cm.",
      ),
      item(
        "transfer-print",
        7,
        "A 4 cm by 3 cm image is printed with every length halved. Find the printed area in square centimetres.",
        similar(4, 3, 0.5),
        3,
        "Original area 12 multiplied by 0.5² gives 3 cm².",
      ),
      item(
        "transfer-brace",
        8,
        "A diagonal brace spans perpendicular distances of 15 cm and 20 cm. Find the brace length in centimetres.",
        right(15, 20),
        25,
        "√(15² + 20²) = √625 = 25 cm.",
      ),
      item(
        "transfer-cable",
        9,
        "A straight cable connects (−4, −3) to (8, 6) on a plan measured in metres. Find its length in metres.",
        distance(-4, -3, 8, 6),
        15,
        "The differences are 12 and 9; √(12² + 9²) = 15 m.",
      ),
      item(
        "transfer-tank",
        10,
        "A rectangular tank has inside dimensions 6 m by 5 m by 3 m. Find its capacity in cubic metres.",
        prism(6, 5, 3),
        90,
        "6 × 5 × 3 = 90 m³.",
      ),
      item(
        "transfer-wrap",
        11,
        "A closed gift box measures 8 cm by 3 cm by 2 cm. Ignoring overlap, find the paper area needed to cover it, in square centimetres.",
        prism(8, 3, 2),
        92,
        "2 × (8 × 3 + 8 × 2 + 3 × 2) = 92 cm².",
      ),
    ],
  },
];
