import { useQuery } from "@tanstack/react-query";
import { getCourseDetail, getJourneyProgress } from "./api";

const courseId = "electronics-foundations";
const lessonId = "current-in-one-loop";

export function CourseHome() {
  const course = useQuery({ queryKey: ["course", courseId], queryFn: () => getCourseDetail(courseId) });
  const progress = useQuery({ queryKey: ["journey-progress", courseId, lessonId], queryFn: () => getJourneyProgress(courseId, lessonId) });
  if (course.isLoading || progress.isLoading) return <main className="story-loading">Preparing your course…</main>;
  if (course.error || progress.error || !course.data || !progress.data) return <main className="story-loading"><h1>Discere could not load the course.</h1><p>{String(course.error ?? progress.error ?? "Missing course data")}</p></main>;
  const activeStage = progress.data.activeStageId;
  return <div className="story-app story-home-app"><aside className="story-rail" aria-label="Discere navigation"><a className="story-mark" href="/" aria-label="Discere home">D</a><nav><a className="story-rail-link active" href="/" aria-label="Courses">⌂</a><a className="story-rail-link" href="/review" aria-label="Review">▣</a><a className="story-rail-link" href={`/courses/${courseId}/lessons/${lessonId}/stages/essay`} aria-label="Saved writing">□</a></nav><button className="story-profile" type="button" aria-label="Learner profile">L</button></aside><main className="story-main"><header className="story-header"><div><a className="story-breadcrumb" href="/">Discere</a><p className="story-stage-label">Course home</p></div><div className="story-home-status">Local learner workspace</div><span /></header><section className="story-home-content"><p className="story-kicker">Course</p><h1>{course.data.course.title}</h1><p className="story-home-description">{course.data.course.description}</p><div className="story-home-actions"><a className="story-primary" href={`/courses/${courseId}/lessons/${lessonId}/stages/${activeStage}`}>Continue learning <span aria-hidden="true">→</span></a><a className="story-secondary" href="/review">Review due concepts</a></div><section className="story-lesson-list" aria-labelledby="lesson-list-title"><h2 id="lesson-list-title">Lessons</h2>{course.data.lessons.map((lesson, index) => lesson.available ? <a className="story-lesson-row" key={lesson.id} href={`/courses/${courseId}/lessons/${lesson.id}/stages/${lesson.id === lessonId ? activeStage : "explainer"}`}><span className="story-lesson-number">{index + 1}</span><span><strong>{lesson.title}</strong><small>{lesson.orientation}</small></span><span aria-hidden="true">→</span></a> : <div className="story-lesson-row unavailable" key={lesson.id}><span className="story-lesson-number">{index + 1}</span><span><strong>{lesson.title}</strong><small>Planned next lesson</small></span><span className="story-planned">Soon</span></div>)}</section></section><footer className="story-navigator"><span>One lesson at a time</span><div className="story-dots"><i className="active" /><i /><i /></div><span>Local-first learning</span></footer></main></div>;
}
