import { useQuery } from "@tanstack/react-query";
import { getReviewHome } from "./api";

export function ReviewHome() {
  const review = useQuery({ queryKey: ["review-home"], queryFn: getReviewHome });
  if (review.isLoading) return <main className="story-loading">Preparing review…</main>;
  if (review.error || !review.data) return <main className="story-loading"><h1>Review is unavailable.</h1><p>{String(review.error ?? "Missing review data")}</p></main>;
  return <div className="story-app story-home-app"><aside className="story-rail" aria-label="Discere navigation"><a className="story-mark" href="/" aria-label="Discere home">D</a><nav><a className="story-rail-link" href="/" aria-label="Courses">⌂</a><a className="story-rail-link active" href="/review" aria-label="Review">▣</a><a className="story-rail-link" href="/courses/electronics-foundations/lessons/current-in-one-loop/stages/essay" aria-label="Saved writing">□</a></nav><button className="story-profile" type="button" aria-label="Learner profile">L</button></aside><main className="story-main"><header className="story-header"><div><a className="story-breadcrumb" href="/">Discere</a><p className="story-stage-label">Review home</p></div><div className="story-home-status">Spaced retrieval</div><span /></header><section className="story-home-content"><p className="story-kicker">Return to what you learned</p><h1>Review due concepts</h1><p className="story-home-description">Recall one idea at a time. The answer stays hidden until you choose to reveal it.</p><div className="story-review-summary"><strong>{review.data.dueCount}</strong><span>due {review.data.dueCount === 1 ? "item" : "items"}<small>{review.data.estimatedMinutes ? `About ${review.data.estimatedMinutes} minutes` : "Nothing due right now"}</small></span></div><a className="story-primary" href="/courses/electronics-foundations/lessons/current-in-one-loop/stages/review">Start review <span aria-hidden="true">→</span></a></section><footer className="story-navigator"><a href="/">← Courses</a><span>One item at a time</span><a href="/courses/electronics-foundations/lessons/current-in-one-loop/stages/review">Review →</a></footer></main></div>;
}
