import type {
  CourseCheckDefinition,
  EngineeringModel,
} from "../../../packages/contracts/src/index.js";
import {
  aluminium,
  bar,
  beam,
  cantilever,
  f,
  fs,
  gears,
  kingpost,
  lever,
  point,
  pulley,
  rect,
  steel,
  triangle,
  warren,
} from "./definition.js";
import { engineeringLessons } from "./lessons.js";

function item(
  id: string,
  lessonIndex: number,
  prompt: string,
  model: EngineeringModel,
  value: number,
  workedAnswer: string,
  unit: string,
  tolerance = 1e-6,
): CourseCheckDefinition["items"][number] {
  const lesson = engineeringLessons[lessonIndex]!;
  return {
    lessonId: lesson.id,
    visual: { type: "engineering", model },
    question: {
      id: "engr-check-" + id,
      conceptIds: ["engr-" + lesson.id],
      sourceIds: lesson.sourceIds,
      prompt,
      responseType: "numeric",
      difficulty: 1,
      hints: [],
      answerAuthority: {
        kind: "numeric",
        value,
        unit,
        absoluteTolerance: tolerance,
        relativeTolerance: 0,
        workedAnswer,
      },
    },
  };
}
const required = engineeringLessons.map((l) => l.id);

export const engineeringChecks: CourseCheckDefinition[] = [
  {
    id: "starting-point",
    kind: "placement",
    title: "Find your starting point",
    description:
      "Twelve problems across forces, structures, beams and machines. Find which ideas need attention before you start.",
    requiredLessonIds: [],
    items: [
      item(
        "placement-components",
        0,
        "A 26 kN force acts along a line rising 5 m for every 12 m across. Find its vertical component in kN.",
        point("kN", fs("F", 26, 12, 5)),
        10,
        "The 5–12–13 triangle gives 26 × 5/13 = 10 kN.",
        "kN",
      ),
      item(
        "placement-moment",
        1,
        "A 60 N force acts at right angles to a lever, 0.45 m from the pivot. Find its moment in N·m.",
        bar("N", ["F", 0.45, 60, 90]),
        27,
        "M = 60 × 0.45 = 27 N·m.",
        "N·m",
      ),
      item(
        "placement-reaction",
        2,
        "An 8 m beam on end supports carries 16 kN at x = 2 m. Find the reaction at the right-hand support in kN.",
        beam(8, [0, 8], [[2, 16]]),
        4,
        "Moments about the left support: 8R = 16 × 2, so R = 4 kN.",
        "kN",
      ),
      item(
        "placement-truss",
        3,
        "A triangular truss spans 8 m with its apex 3 m high, so each sloping member is 5 m long. A 24 kN load acts at the apex. Find the size of the force in each sloping member in kN.",
        triangle(8, 3, 24),
        20,
        "At the apex: 2F × 3/5 = 24, so F = 20 kN, in compression.",
        "kN",
      ),
      item(
        "placement-stress",
        4,
        "A 30 kN axial pull acts on a bar with a 600 mm² cross-section. Find the stress in MPa.",
        steel(600, 1000, 30),
        50,
        "σ = 30,000 ÷ 600 = 50 MPa.",
        "MPa",
      ),
      item(
        "placement-safety",
        5,
        "A 400 mm² tie carries 30 kN in steel that yields at 300 MPa. Find its factor of safety against yield.",
        steel(400, 2000, 30, 300),
        4,
        "Working stress = 30,000 ÷ 400 = 75 MPa; FoS = 300 ÷ 75 = 4.",
        "",
      ),
      item(
        "placement-bending-moment",
        6,
        "A 6 m beam on end supports carries 18 kN at midspan. Find the largest bending moment in kN·m.",
        beam(6, [0, 6], [[3, 18]], [], "moment"),
        27,
        "Each reaction is 9 kN; under the load M = 9 × 3 = 27 kN·m.",
        "kN·m",
      ),
      item(
        "placement-bending-stress",
        7,
        "A solid rectangular beam 50 mm wide and 100 mm deep carries 2 kN·m. Find the largest bending stress in MPa.",
        rect(50, 100, 2),
        24,
        "I = 50 × 100³/12 = 4.17 × 10⁶ mm⁴; σ = 2 × 10⁶ × 50 ÷ I = 24 MPa.",
        "MPa",
      ),
      item(
        "placement-deflection",
        8,
        "A 1 m cantilever (E = 200 GPa, I = 1 × 10⁶ mm⁴) carries 6 kN at its tip. Find the tip deflection in mm.",
        cantilever(1, 6, 200, 1),
        10,
        "EI = 200,000 N·m²; δ = 6,000 × 1 ÷ 600,000 = 0.01 m = 10 mm.",
        "mm",
      ),
      item(
        "placement-lever",
        9,
        "A lever has an effort arm of 0.9 m and a load arm of 0.15 m. Find the effort, in N, that holds a 600 N load.",
        lever("first", 0.9, 0.15, 600),
        100,
        "Effort = 600 × 0.15 ÷ 0.9 = 100 N.",
        "N",
      ),
      item(
        "placement-gears",
        10,
        "A 24-tooth gear at 960 rpm drives a 72-tooth gear. Find the output speed in rpm.",
        gears([[24, 72]], 960, 10),
        320,
        "960 × 24 ÷ 72 = 320 rpm.",
        "rpm",
      ),
      item(
        "placement-power",
        11,
        "A hoist raises 1,500 N at 0.4 m/s through a rope system that is 75% efficient. Find the input power in W.",
        pulley(3, 1500, 2, 0.75, 0.4),
        800,
        "Useful power = 1,500 × 0.4 = 600 W; input = 600 ÷ 0.75 = 800 W.",
        "W",
      ),
    ],
  },
  {
    id: "mixed-challenge",
    kind: "checkpoint",
    title: "Bring the ideas together",
    description:
      "Twelve mixed problems from loads to machines. Choose the method and record your confidence; results appear after the final response.",
    requiredLessonIds: required,
    items: [
      item(
        "mixed-resultant",
        0,
        "Three forces act on a pin: 6 kN along +x, 3 kN along +y and 11 kN along −y. Find the magnitude of their resultant in kN.",
        point("kN", f("A", 6, 0), f("B", 3, 90), f("C", 11, 270)),
        10,
        "Rx = 6 kN, Ry = 3 − 11 = −8 kN, so R = √(36 + 64) = 10 kN.",
        "kN",
      ),
      item(
        "mixed-net-moment",
        1,
        "A bar pivots at x = 0. Two downward loads act on it: 200 N at x = −1.5 m and 150 N at x = 1 m. Find the net moment about the pivot in N·m, anticlockwise positive.",
        bar("N", ["P", -1.5, 200, 270], ["Q", 1, 150, 270]),
        150,
        "The left load gives +200 × 1.5 = +300 N·m, the right one −150 × 1 = −150 N·m; net +150 N·m.",
        "N·m",
      ),
      item(
        "mixed-overhang",
        2,
        "A 5 m beam has supports at x = 0 and x = 4 m and a 12 kN load at its free end, x = 5 m. Find the upward reaction at x = 4 m in kN.",
        beam(5, [0, 4], [[5, 12]]),
        15,
        "Moments about x = 0: 4R = 12 × 5, so R = 15 kN.",
        "kN",
      ),
      item(
        "mixed-kingpost",
        3,
        "In a king-post truss the vertical member DC rises from the middle of the bottom chord, D, to the apex C. A 9 kN load hangs from D. Find the tension in DC in kN.",
        kingpost(4, 1.5, 9, "D"),
        9,
        "At D the collinear chords have no vertical component, so DC alone carries the 9 kN up to C.",
        "kN",
      ),
      item(
        "mixed-stretch",
        4,
        "A steel bar (E = 200 GPa) 1,500 mm long with a 250 mm² section carries 20 kN. Find its stretch in mm.",
        steel(250, 1500, 20),
        0.6,
        "σ = 20,000 ÷ 250 = 80 MPa; δ = 80 ÷ 200,000 × 1,500 = 0.6 mm.",
        "mm",
      ),
      item(
        "mixed-sizing",
        5,
        "A tie must carry 45 kN with a factor of safety of 2 in steel that yields at 300 MPa. Find the minimum area in mm².",
        steel(300, 2000, 45, 300),
        300,
        "Allowable = 300 ÷ 2 = 150 MPa; A = 45,000 ÷ 150 = 300 mm².",
        "mm²",
      ),
      item(
        "mixed-cantilever-moment",
        6,
        "A 4 m cantilever carries 2 kN/m along its whole length. Find the size of the bending moment at the wall in kN·m.",
        beam(4, "cantilever", [], [[0, 4, 2]], "moment"),
        16,
        "Total load 8 kN acting 2 m from the wall: M = 8 × 2 = 16 kN·m.",
        "kN·m",
      ),
      item(
        "mixed-bending-stress",
        7,
        "A solid rectangular beam 80 mm wide and 150 mm deep carries 9 kN·m. Find the largest bending stress in MPa.",
        rect(80, 150, 9),
        30,
        "I = 80 × 150³/12 = 22.5 × 10⁶ mm⁴; σ = 9 × 10⁶ × 75 ÷ I = 30 MPa.",
        "MPa",
      ),
      item(
        "mixed-required-i",
        8,
        "A 2 m steel cantilever (E = 200 GPa) must deflect no more than 10 mm under a 6 kN tip load. Find the minimum I in units of 10⁶ mm⁴.",
        cantilever(2, 6, 200, 8),
        8,
        "I = PL³/(3Eδ) = 6,000 × 8 ÷ (3 × 200 × 10⁹ × 0.01) = 8 × 10⁻⁶ m⁴ = 8 × 10⁶ mm⁴.",
        "× 10⁶ mm⁴",
      ),
      item(
        "mixed-pulley",
        9,
        "A pulley system with 3 supporting strands is 90% efficient. Find the effort needed to raise a 1,350 N load, in N.",
        pulley(3, 1350, 1, 0.9),
        500,
        "Effort = 1,350 ÷ (3 × 0.9) = 500 N.",
        "N",
      ),
      item(
        "mixed-compound",
        10,
        "A compound train has 16 teeth driving 48, then 18 teeth driving 72 on the same shaft. The input turns at 1,500 rpm. Find the output speed in rpm.",
        gears(
          [
            [16, 48],
            [18, 72],
          ],
          1500,
          8,
        ),
        125,
        "Ratio = 3 × 4 = 12; output = 1,500 ÷ 12 = 125 rpm.",
        "rpm",
      ),
      item(
        "mixed-torque",
        11,
        "A gearbox with a 5 : 1 reduction and one 96% efficient mesh receives 12 N·m. Find the output torque in N·m.",
        gears([[12, 60]], 1000, 12, 0.96),
        57.6,
        "12 × 5 × 0.96 = 57.6 N·m.",
        "N·m",
      ),
    ],
  },
  {
    id: "later-applications",
    kind: "transfer",
    title: "Use it a week later",
    description:
      "Apply the ideas to twelve new structures and machines after a delay. State the units you are working in and check each answer for size.",
    requiredLessonIds: required,
    afterCheckId: "mixed-challenge",
    delayDays: 7,
    items: [
      item(
        "later-guy-rope",
        0,
        "A guy rope pulls on the top of a mast with 15 kN along a line that runs 9 m across for every 12 m down. Find the horizontal component in kN.",
        point("kN", fs("T", 15, 9, -12)),
        9,
        "The 9–12–15 triangle gives 15 × 9/15 = 9 kN.",
        "kN",
      ),
      item(
        "later-wrench",
        1,
        "A 90 N hand force pushes on a wrench 0.4 m from the bolt, at 30° to the handle. Find the size of the moment about the bolt in N·m.",
        bar("N", ["F", 0.4, 90, 30]),
        18,
        "M = 90 × 0.4 × sin 30° = 18 N·m.",
        "N·m",
      ),
      item(
        "later-footbridge",
        2,
        "A 12 m footbridge on end supports carries 5 kN/m along its full length and a 30 kN cart at x = 4 m. Find the left reaction in kN.",
        beam(12, [0, 12], [[4, 30]], [[0, 12, 5]]),
        50,
        "About the right support: 12R = 60 × 6 + 30 × 8 = 600, so R = 50 kN.",
        "kN",
      ),
      item(
        "later-warren",
        3,
        "A Warren truss has bottom joints A, D and B 3 m apart and top joints C and E 2 m up, so each diagonal is 2.5 m long. A 16 kN load hangs from D. Find the size of the force in the top member CE in kN.",
        warren(3, 2, 16),
        12,
        "Each reaction is 8 kN. At A: F_AC × 2/2.5 = 8, so AC = 10 kN compression. At C, CD balances AC vertically (10 kN tension) and CE = 10 × 1.5/2.5 × 2 = 12 kN compression.",
        "kN",
      ),
      item(
        "later-aluminium",
        4,
        "An aluminium rod (E = 70 GPa) 2,100 mm long works at 35 MPa. Find its stretch in mm.",
        aluminium(200, 2100, 7),
        1.05,
        "δ = 35 ÷ 70,000 × 2,100 = 1.05 mm.",
        "mm",
      ),
      item(
        "later-safety",
        5,
        "A 500 mm² bar of steel that yields at 275 MPa carries 55 kN. Find its factor of safety against yield.",
        steel(500, 2000, 55, 275),
        2.5,
        "Working stress = 55,000 ÷ 500 = 110 MPa; FoS = 275 ÷ 110 = 2.5.",
        "",
      ),
      item(
        "later-moment",
        6,
        "A 9 m beam on end supports carries 12 kN at x = 3 m. Find the bending moment under the load in kN·m.",
        beam(9, [0, 9], [[3, 12]], [], "moment"),
        24,
        "R_A = 12 × 6 ÷ 9 = 8 kN; M = 8 × 3 = 24 kN·m.",
        "kN·m",
      ),
      item(
        "later-orientation",
        7,
        "Two rectangular beams of equal area carry the same moment. One is 75 mm wide and 200 mm deep; the other is 150 mm wide and 100 mm deep. Find the ratio of the shallow beam's largest stress to the deep beam's.",
        rect(150, 100, 10),
        2,
        "For a rectangle σ = 6M/(bh²). The deep beam has bh² = 3 × 10⁶ mm³, the shallow one 1.5 × 10⁶ mm³, so its stress is twice as high.",
        "",
      ),
      item(
        "later-stiffness",
        8,
        "Two cantilevers differ only in length: 1.5 m and 3 m. Find the ratio of the longer one's tip stiffness to the shorter one's.",
        cantilever(3, 2, 200, 3),
        0.125,
        "k = 3EI/L³, so the ratio is (1.5/3)³ = 0.125.",
        "",
      ),
      item(
        "later-third-class",
        9,
        "A third-class lever has its effort 0.05 m from the fulcrum and a 40 N load 0.3 m from it. Find the effort in N.",
        lever("third", 0.05, 0.3, 40),
        240,
        "Effort = 40 × 0.3 ÷ 0.05 = 240 N, six times the load.",
        "N",
      ),
      item(
        "later-idler",
        10,
        "A 14-tooth motor pinion at 2,100 rpm drives a 42-tooth gear through a 30-tooth idler. Find the output speed in rpm.",
        gears([[14, 42]], 2100, 5, 1, 30),
        700,
        "The idler cancels: 2,100 × 14 ÷ 42 = 700 rpm.",
        "rpm",
      ),
      item(
        "later-output-power",
        11,
        "A motor supplies 20 N·m at 1,000 rpm into a single-mesh drive that is 90% efficient. Find the output power in W, to the nearest watt.",
        gears([[20, 80]], 1000, 20, 0.9),
        600 * Math.PI,
        "Input = 20 × 1,000 × 2π ÷ 60 = 2,094.4 W; output = 0.9 × 2,094.4 = 1,885 W.",
        "W",
        0.6,
      ),
    ],
  },
];
