export interface ToolDefinition { name: string; title: string; description: string; inputSchema: Record<string, unknown>; readOnly: boolean; }
const object = (properties: Record<string, unknown>, required: string[] = []): Record<string, unknown> => ({ type: "object", properties, required, additionalProperties: false });
export const toolCatalog: ToolDefinition[] = [
  { name: "discere_get_home", title: "Get learning home", description: "Return the learner's mission, XP, streak, and concept progress.", inputSchema: object({}), readOnly: true },
  { name: "discere_get_current_lesson", title: "Get current lesson", description: "Return the visible lesson, activity, visual brief, and learner question. Hidden answers are omitted.", inputSchema: object({}), readOnly: true },
  { name: "discere_submit_answer", title: "Submit answer", description: "Assess a learner response and record XP and mastery evidence.", inputSchema: object({ questionId: { type: "string" }, response: { type: "string" }, mode: { type: "string", enum: ["coach", "assisted", "direct", "exam"] }, attemptId: { type: "string", format: "uuid" } }, ["questionId", "response", "mode"]), readOnly: false },
  { name: "discere_request_hint", title: "Request one hint", description: "Return the next permitted hint and record the assistance event.", inputSchema: object({ attemptId: { type: "string", format: "uuid" } }, ["attemptId"]), readOnly: false },
  { name: "discere_start_answer_reveal", title: "Start answer reveal", description: "Start the reflection delay before a worked answer can be revealed.", inputSchema: object({ attemptId: { type: "string", format: "uuid" }, reason: { type: "string", minLength: 8, maxLength: 240 } }, ["attemptId", "reason"]), readOnly: false },
  { name: "discere_confirm_answer_reveal", title: "Confirm answer reveal", description: "Reveal the worked answer after the delay and confirmation phrase have been satisfied.", inputSchema: object({ attemptId: { type: "string", format: "uuid" }, token: { type: "string", format: "uuid" }, confirmation: { type: "string" } }, ["attemptId", "token", "confirmation"]), readOnly: false },
  { name: "discere_lint_learning_text", title: "Check learning prose", description: "Check text for prohibited generated-writing habits and answer leakage.", inputSchema: object({ text: { type: "string" }, context: { type: "string", enum: ["lesson", "question", "hint", "feedback", "assessment"] }, hiddenAnswer: { type: "string" } }, ["text", "context"]), readOnly: false },
  { name: "discere_create_image_prompt", title: "Create reviewed image brief", description: "Convert a stored visual brief into an image-generation prompt that keeps exact labels out of the pixels.", inputSchema: object({ visualBriefId: { type: "string" } }, ["visualBriefId"]), readOnly: true },
];
