import type {
  CourseCheckDefinition,
  CourseCheckVisual,
  PsychologyModel,
} from "../../../packages/contracts/src/index.js";
import {
  anchor,
  assignment,
  baseRate,
  bystander,
  correlated,
  cues,
  detection,
  effect,
  forgetting,
  pairing,
  scatter,
  schedule,
  span,
  switching,
  tally,
} from "./definition.js";
import { psychologyLessons } from "./lessons.js";

type Item = CourseCheckDefinition["items"][number];
const visualOf = (v: PsychologyModel | CourseCheckVisual): CourseCheckVisual =>
  "kind" in v ? { type: "psychology", model: v } : v;

function base(id: string, lessonIndex: number, prompt: string) {
  const lesson = psychologyLessons[lessonIndex]!;
  return {
    lesson,
    question: {
      id: "psych-check-" + id,
      conceptIds: ["psych-" + lesson.id],
      sourceIds: lesson.sourceIds,
      prompt,
      difficulty: 1,
      hints: [] as never[],
    },
  };
}

function item(
  id: string,
  lessonIndex: number,
  prompt: string,
  visual: PsychologyModel | CourseCheckVisual,
  value: number,
  workedAnswer: string,
  unit = "",
  tolerance = 1e-6,
): Item {
  const { lesson, question } = base(id, lessonIndex, prompt);
  return {
    lessonId: lesson.id,
    visual: visualOf(visual),
    question: {
      ...question,
      responseType: "numeric",
      answerAuthority: {
        kind: "numeric",
        value,
        unit,
        absoluteTolerance: tolerance,
        relativeTolerance: 0,
        workedAnswer,
      },
    },
  };
}

function pick(
  id: string,
  lessonIndex: number,
  prompt: string,
  visual: PsychologyModel | CourseCheckVisual,
  labels: string[],
  correct: number,
  reason: string,
): Item {
  const { lesson, question } = base(id, lessonIndex, prompt);
  return {
    lessonId: lesson.id,
    visual: visualOf(visual),
    question: {
      ...question,
      responseType: "short_text",
      choices: labels.map((label, i) => ({ id: String(i + 1), label })),
      answerAuthority: {
        kind: "text",
        acceptedIdeas: [labels[correct]!],
        rejectedIdeas: [],
        exampleAnswer: reason,
      },
    },
  };
}

const required = psychologyLessons.map((l) => l.id);

export const psychologyChecks: CourseCheckDefinition[] = [
  {
    id: "starting-point",
    kind: "placement",
    title: "Find your starting point",
    description:
      "Twelve problems across research methods, perception, memory and social thinking. See which ideas you already command.",
    requiredLessonIds: [],
    items: [
      item(
        "placement-shared-variance",
        0,
        "Hours of revision and exam score correlate at r = 0.5. What percentage of the variation in exam score do they share?",
        scatter(
          "Revision (hours)",
          "Exam score",
          correlated(20, 0.5, { mean: 12, sd: 4 }, { mean: 62, sd: 10 }, 101),
        ),
        25,
        "r² = 0.5² = 0.25, so 25%.",
        "%",
      ),
      item(
        "placement-self-selection",
        1,
        "Eight volunteers have prior fitness scores 10, 2, 9, 3, 8, 4, 7 and 5. The four fittest choose the new programme. How much higher is the programme group's mean fitness before it begins?",
        assignment("Prior fitness score", [10, 2, 9, 3, 8, 4, 7, 5], "self_selected"),
        5,
        "Programme mean = (10 + 9 + 8 + 7)/4 = 8.5; other mean = (2 + 3 + 4 + 5)/4 = 3.5; gap = 5.",
      ),
      item(
        "placement-cohens-d",
        2,
        "A control group has mean 70 and a treatment group mean 76, both with standard deviation 10. What is Cohen's d?",
        effect("Control", 70, 10, "Treatment", 76, 10),
        0.6,
        "d = (76 − 70)/10 = 0.6.",
      ),
      item(
        "placement-d-prime",
        3,
        "An observer's hit rate is 0.90 (z = 1.28) and false-alarm rate is 0.30 (z = −0.52). What is d′?",
        detection(1.8, 0.52),
        1.8,
        "d′ = 1.28 − (−0.52) = 1.8.",
      ),
      item(
        "placement-switching",
        4,
        "Each trial takes 500 ms and each change of task adds 100 ms. How long does the sequence ABBABA take, in milliseconds?",
        switching("ABBABA", 500, 100),
        3400,
        "ABBABA switches 4 times: 6 × 500 + 4 × 100 = 3,400 ms.",
        "ms",
      ),
      item(
        "placement-cues",
        5,
        "Cue A reads 30 with SD 1 and cue B reads 40 with SD 2. Weighting each by 1/SD², what is the combined estimate?",
        cues("Cue A", 30, 1, "Cue B", 40, 2),
        32,
        "Reliabilities 1 and 0.25 give A weight 0.8: 0.8 × 30 + 0.2 × 40 = 32.",
      ),
      item(
        "placement-chunks",
        6,
        "A reader holds 21 letters as 7 familiar three-letter words. Against a capacity of 4 chunks, how many chunks over the limit are they?",
        span("CAT DOG SUN MAP HAT BOX PEN", [1, 1, 1, 1, 1, 1, 1]),
        3,
        "7 chunks − 4 = 3 over the limit.",
        "chunks",
      ),
      item(
        "placement-forgetting",
        7,
        "Using R = 1/(1 + t/9S) with stability S = 2 days, what percentage recall is predicted 6 days after learning?",
        forgetting(2, 20),
        75,
        "t/9S = 6/18 = 1/3; R = 1/(4/3) = 0.75, or 75%.",
        "%",
      ),
      item(
        "placement-fixed-ratio",
        8,
        "On a fixed-ratio 4 schedule, a rat presses once a second for 30 seconds. How many rewards does it earn?",
        schedule("fixed_ratio", [4], 1, 30),
        7,
        "30 presses; every fourth is rewarded; 30/4 = 7 complete sets, so 7 rewards.",
        "rewards",
      ),
      item(
        "placement-false-positives",
        9,
        "1,000 people are screened for a condition that 2% have. The test gives false positives for 5% of people without the condition. How many false positives are there?",
        baseRate(1000, 0.02, 0.9, 0.05),
        49,
        "980 people do not have it; 5% of 980 = 49.",
        "people",
      ),
      item(
        "placement-anchoring",
        10,
        "Anchors of 50 and 150 produce median estimates of 80 and 110. What is the anchoring index?",
        anchor("Estimated price of a bicycle (£)", 50, 80, 150, 110, 0, 200),
        0.3,
        "(110 − 80)/(150 − 50) = 30/100 = 0.3.",
      ),
      item(
        "placement-bystanders",
        11,
        "Four bystanders each independently act with probability 0.25. What is the probability, as a percentage, that at least one acts? Give one decimal place.",
        bystander(4, 0.25),
        68.4,
        "1 − 0.75⁴ = 1 − 0.3164 = 0.6836, or 68.4%.",
        "%",
        0.051,
      ),
    ],
  },
  {
    id: "mixed-challenge",
    kind: "checkpoint",
    title: "Bring the ideas together",
    description:
      "Twelve fresh problems, one from each lesson, in mixed order of difficulty. Answers stay hidden until you finish.",
    requiredLessonIds: required,
    items: [
      item(
        "mixed-shared-variance",
        0,
        "Two personality scales correlate at r = −0.8. What percentage of variation do they share?",
        scatter(
          "Scale A score",
          "Scale B score",
          correlated(20, -0.8, { mean: 50, sd: 10 }, { mean: 50, sd: 10 }, 103),
        ),
        64,
        "r² = (−0.8)² = 0.64, so 64%.",
        "%",
      ),
      item(
        "mixed-placebo",
        1,
        "A pain treatment group improves by 14 points and a placebo group by 9 points. How many points of improvement are due to the treatment beyond the placebo response?",
        effect("Placebo", 9, 5, "Treatment", 14, 5, "points"),
        5,
        "14 − 9 = 5 points.",
        "points",
      ),
      item(
        "mixed-pooled-d",
        2,
        "Two equal-sized groups have means 30 and 39 with standard deviations 3 and 21. Using the pooled SD √[(SD₁² + SD₂²)/2], what is Cohen's d?",
        effect("Group A", 30, 3, "Group B", 39, 21),
        0.6,
        "Pooled SD = √[(9 + 441)/2] = √225 = 15; d = 9/15 = 0.6.",
      ),
      item(
        "mixed-criterion",
        3,
        "An observer has z(H) = 0.8 and z(FA) = −1.2. What is the criterion location c = −[z(H) + z(FA)]/2?",
        detection(2, 1.2),
        0.2,
        "c = −(0.8 − 1.2)/2 = 0.2, a slight bias towards saying no.",
      ),
      item(
        "mixed-blindness",
        4,
        "12 of 40 people counting passes fail to notice an unexpected person crossing the scene. What percentage missed it?",
        tally("Viewers counting passes", 12, 40, "Missed the person", "Noticed"),
        30,
        "12/40 = 0.3, or 30%.",
        "%",
      ),
      item(
        "mixed-combined-sd",
        5,
        "Two independent cues have standard deviations 9 and 12. What is the standard deviation of their reliability-weighted combination?",
        cues("Cue A", 20, 9, "Cue B", 26, 12),
        7.2,
        "1/81 + 1/144 = 225/11,664; combined SD = 108/15 = 7.2.",
      ),
      pick(
        "mixed-sketchpad",
        6,
        "You hold the layout of a room in mind while planning where to move a sofa. Which part of the working-memory model holds that layout?",
        span("sofa lamp desk door", [1, 1, 1, 1]),
        ["Visuospatial sketchpad", "Phonological loop", "Episodic buffer"],
        0,
        "Images and spatial layouts are held in the visuospatial sketchpad.",
      ),
      item(
        "mixed-review",
        7,
        "A memory with stability 6 days is reviewed, doubling stability to 12 days. Using R = 1/(1 + t/9S), what percentage recall is predicted 27 days after that review?",
        forgetting(6, 40, [6], 2),
        80,
        "9S = 108; 27/108 = 0.25; R = 1/1.25 = 0.8, or 80%.",
        "%",
      ),
      item(
        "mixed-rescorla",
        8,
        "Under ΔV = αβ(λ − V) with rate 0.2, maximum 1 and V starting at 0, what is V after three paired trials?",
        pairing(0.2, "PPP"),
        0.488,
        "0.2, then 0.2 + 0.2 × 0.8 = 0.36, then 0.36 + 0.2 × 0.64 = 0.488.",
      ),
      item(
        "mixed-positive-value",
        9,
        "500 people are tested for a condition that 10% have. The test detects 80% of cases and gives false positives for 20% of people without it. What percentage of positive results are true positives? Give one decimal place.",
        baseRate(500, 0.1, 0.8, 0.2),
        30.8,
        "50 have it, 40 test positive; 450 do not, 90 test positive; 40/130 = 30.8%.",
        "%",
        0.051,
      ),
      item(
        "mixed-doubling",
        10,
        "A rumour reaches twice as many people every hour and reaches the whole town after 10 hours. After how many hours had it reached half the town?",
        {
          type: "table",
          columns: ["Hour", "Share of town reached"],
          rows: [
            ["10", "All"],
            ["Earlier", "Half"],
          ],
        },
        9,
        "Doubling means half the final reach one hour earlier: hour 9.",
        "hours",
      ),
      item(
        "mixed-obedience",
        11,
        "In a variation of an obedience study, 18 of 40 participants continue to the end. What percentage is that?",
        tally("An obedience study variation", 18, 40, "Continued to the end", "Stopped"),
        45,
        "18/40 = 0.45, or 45%.",
        "%",
      ),
    ],
  },
  {
    id: "later-applications",
    kind: "transfer",
    title: "Use it a week later",
    description:
      "Twelve problems in new settings, available seven days after the mixed check. Spaced retrieval is the point.",
    requiredLessonIds: required,
    afterCheckId: "mixed-challenge",
    delayDays: 7,
    items: [
      pick(
        "later-churches",
        0,
        "Across towns, the number of churches correlates strongly with the number of crimes. Which explanation is most likely?",
        scatter(
          "Churches",
          "Recorded crimes",
          correlated(20, 0.85, { mean: 20, sd: 8 }, { mean: 450, sd: 150 }, 107),
        ),
        [
          "Population size drives both counts",
          "Churches cause crime",
          "Crime causes church building",
        ],
        0,
        "Bigger towns have more of both. Population is a confound.",
      ),
      item(
        "later-placebo-share",
        1,
        "A therapy group improves 20 points, a placebo group 14 points and a waiting-list group 5 points. How many points of the therapy group's advantage over the waiting list are matched by the placebo group?",
        {
          type: "table",
          columns: ["Group", "Improvement (points)"],
          rows: [
            ["Therapy", "20"],
            ["Placebo", "14"],
            ["Waiting list", "5"],
          ],
        },
        9,
        "Placebo improvement beyond the waiting list = 14 − 5 = 9 points of the 15-point advantage.",
        "points",
      ),
      item(
        "later-sample-size",
        2,
        "Using n ≈ 16/d² per group for 80% power at α = 0.05, how many participants per group does a study of an effect of d = 0.25 need?",
        effect("Control", 50, 8, "Treatment", 52, 8),
        256,
        "16/0.25² = 16/0.0625 = 256 per group.",
        "participants",
      ),
      item(
        "later-d-prime",
        3,
        "A baggage screener's hit rate has z = 0.25 and false-alarm rate has z = −1.75. What is d′?",
        detection(2, 1.75),
        2,
        "d′ = 0.25 − (−1.75) = 2.",
      ),
      item(
        "later-switching",
        4,
        "Each trial takes 400 ms and each change of task adds 200 ms. How long does AAABBBAB take, in milliseconds?",
        switching("AAABBBAB", 400, 200),
        3800,
        "AAABBBAB switches 3 times: 8 × 400 + 3 × 200 = 3,800 ms.",
        "ms",
      ),
      item(
        "later-ventriloquist",
        5,
        "Hearing places a voice 12° to the right (SD 6°); vision places the lips at 0° (SD 3°). Combining by reliability, where is the voice heard, in degrees to the right?",
        cues("Hearing", 12, 6, "Vision", 0, 3, "°"),
        2.4,
        "Reliabilities 1/36 and 1/9 give hearing weight 0.2; location = 0.2 × 12 = 2.4°.",
        "°",
      ),
      item(
        "later-chess",
        6,
        "A chess master recalls a 15-piece position as 5 chunks. On average, how many pieces are in each chunk?",
        span("Kg1 Rf1 Pf2 Pg2 Ph2 Qd1 Bc1 Nb1 Ra1 Pa2 Pb2 Pc3 Ke8 Rf8 Pf7", Array(15).fill(1)),
        3,
        "15/5 = 3 pieces a chunk.",
        "pieces",
      ),
      item(
        "later-forgetting",
        7,
        "Using R = 1/(1 + t/9S) with stability S = 3 days, what percentage recall is predicted 81 days after learning?",
        forgetting(3, 90),
        25,
        "9S = 27; 81/27 = 3; R = 1/4 = 25%.",
        "%",
      ),
      pick(
        "later-fishing",
        8,
        "An angler is rewarded with a bite for the first cast after an unpredictable wait that averages ten minutes. Which schedule is this?",
        schedule("variable_interval", [4, 16, 10, 6, 14], 2, 60),
        ["Variable interval", "Variable ratio", "Fixed interval", "Fixed ratio"],
        0,
        "Reward depends on time passing, and the time varies: a variable-interval schedule.",
      ),
      item(
        "later-cabs",
        9,
        "25% of a town's buses are red. A witness who names colours correctly 70% of the time says a bus was red. What is the probability, as a percentage, that it was red? Give two decimal places.",
        baseRate(1000, 0.25, 0.7, 0.3, "Red bus", "Witness says red"),
        43.75,
        "Per 1,000 buses: 175 red buses called red and 225 others called red; 175/400 = 43.75%.",
        "%",
        0.006,
      ),
      item(
        "later-anchoring",
        10,
        "Anchors of 5 and 25 produce median estimates of 11 and 19. What is the anchoring index?",
        anchor("Estimated number of moons of a planet", 5, 11, 25, 19, 0, 30),
        0.4,
        "(19 − 11)/(25 − 5) = 8/20 = 0.4.",
      ),
      item(
        "later-conformity",
        11,
        "In a conformity study, 36 of 120 critical answers follow the wrong majority. What percentage conformed?",
        tally("A line-judgement study", 36, 120, "Went along", "Stayed independent"),
        30,
        "36/120 = 0.3, or 30%.",
        "%",
      ),
    ],
  },
];
