import { lesson, t, num, choice, recall, p, add, scale, dot, length } from "./definition.js";
const m = "lin-vectors-module";
export const vectorLessons = [
  lesson(
    "read-vector-coordinates",
    "Read a vector",
    "Read signed coordinates and distinguish vectors from individual scalars.",
    m,
    ["lin-vectors"],
    [
      t(
        "Read the first coordinate",
        "A vector records an ordered list of coordinates. In the plane, the first coordinate measures horizontal movement and the second measures vertical movement.",
        scale([3, -2], 1),
        scale([-2, 3], 1),
        num(
          "For v = (3, −2), what is the x coordinate?",
          3,
          "The first coordinate is 3; the second is −2.",
          "Read the first entry.",
          p(scale([3, -2], 1), 0),
        ),
      ),
      t(
        "Keep the order",
        "Changing the order changes the vector. The pairs (1, 4) and (4, 1) point to different locations.",
        scale([1, 4], 1),
        scale([4, 1], 1),
        choice(
          "Are (1, 4) and (4, 1) the same vector?",
          ["Yes", "No"],
          1,
          "Corresponding coordinates differ, so these vectors are unequal.",
          "Compare the first entries, then the second entries.",
        ),
      ),
      t(
        "Find the zero vector",
        "The zero vector has every coordinate equal to zero. Its length is zero; it stays at the origin.",
        length([0, 0]),
        length([1, 0]),
        num(
          "What is the length of (0, 0)?",
          0,
          "Both coordinates are zero, so the length is zero.",
          "Square and add the coordinates.",
          p(length([0, 0])),
        ),
      ),
      t(
        "Read a coordinate direction",
        "The standard coordinate vectors are (1, 0) and (0, 1). They give one unit of movement along just one axis.",
        scale([0, 1], 1),
        scale([1, 0], 1),
        num(
          "What is the y coordinate of (0, 1)?",
          1,
          "The second coordinate is 1.",
          "The y coordinate is the second entry.",
          p(scale([0, 1], 1), 1),
        ),
      ),
    ],
    [
      num(
        "Give the x coordinate of (−5, 3).",
        -5,
        "The first coordinate is −5.",
        "Keep its minus sign.",
        p(scale([-5, 3], 1), 0),
      ),
      num(
        "Give the y coordinate of (6, −4).",
        -4,
        "The second coordinate is −4.",
        "Read the second entry.",
        p(scale([6, -4], 1), 1),
      ),
    ],
    [
      recall(
        "Give the x coordinate of (7, −2).",
        7,
        "The first entry gives x = 7.",
        p(scale([7, -2], 1), 0),
      ),
      recall(
        "Give the y coordinate of (−3, 5).",
        5,
        "The second entry gives y = 5.",
        p(scale([-3, 5], 1), 1),
      ),
    ],
  ),
  lesson(
    "add-and-scale-vectors",
    "Add and scale vectors",
    "Combine displacements, scale every coordinate and handle negative scalars.",
    m,
    ["lin-vectors", "lin-span"],
    [
      t(
        "Combine displacements",
        "Vector addition combines matching coordinates. Add horizontal movements to horizontal movements and vertical movements to vertical movements.",
        add([2, 1], [-1, 3]),
        add([2, 1], [1, -3]),
        num(
          "What is the x coordinate of (2, 1) + (−1, 3)?",
          1,
          "The x coordinate is 2 + (−1) = 1.",
          "Add the first coordinates.",
          p(add([2, 1], [-1, 3]), 0),
        ),
      ),
      t(
        "Stretch both coordinates",
        "A scalar multiplies every coordinate. Scaling by 3 triples the length and keeps the direction.",
        scale([2, -1], 3),
        scale([2, -1], 1),
        num(
          "What is the y coordinate of 3(2, −1)?",
          -3,
          "The y coordinate is 3 × (−1) = −3.",
          "Multiply the second coordinate by the scalar.",
          p(scale([2, -1], 3), 1),
        ),
      ),
      t(
        "Reverse the direction",
        "A negative scalar reverses the vector's direction. Its absolute value determines the factor by which length changes.",
        scale([2, -1], -2),
        scale([2, -1], 2),
        num(
          "What is the x coordinate of −2(2, −1)?",
          -4,
          "The first coordinate becomes −2 × 2 = −4.",
          "Apply the signed scalar to the first coordinate.",
          p(scale([2, -1], -2), 0),
        ),
      ),
      t(
        "Cancel a displacement",
        "Every vector has an additive inverse. Adding a vector to its negative produces the zero vector.",
        add([3, 2], [-3, -2]),
        add([3, 2], [-3, 2]),
        num(
          "What is the y coordinate of (3, 2) + (−3, −2)?",
          0,
          "The vertical movements add to 2 − 2 = 0.",
          "Add the second coordinates with their signs.",
          p(add([3, 2], [-3, -2]), 1),
        ),
      ),
    ],
    [
      num(
        "Let u = (2, 1) and v = (−1, 3). What is the y coordinate of 2u + v?",
        5,
        "First 2u = (4, 2); adding v gives (3, 5).",
        "Scale u before adding v.",
        p(add([4, 2], [-1, 3]), 1),
      ),
      num(
        "What is the x coordinate of (4, 1) − (1, 3)?",
        3,
        "Subtract matching entries: the first is 4 − 1 = 3.",
        "Subtraction is addition of the negative vector.",
        p(add([4, 1], [-1, -3]), 0),
      ),
    ],
    [
      recall(
        "What is the y coordinate of (1, −4) + (3, 2)?",
        -2,
        "Add the second entries: −4 + 2 = −2.",
        p(add([1, -4], [3, 2]), 1),
      ),
      recall(
        "What is the x coordinate of −3(−2, 5)?",
        6,
        "Multiply the first entry: (−3)(−2) = 6.",
        p(scale([-2, 5], -3), 0),
      ),
    ],
  ),
  lesson(
    "dot-products-and-length",
    "Dot products and length",
    "Use matching-coordinate products to measure alignment and vector length.",
    m,
    ["lin-dot"],
    [
      t(
        "Combine matching products",
        "The dot product is one scalar. Multiply corresponding entries and add the products.",
        dot([2, 1], [3, -2]),
        dot([2, 1], [-3, 2]),
        num(
          "Find (2, 1) · (3, −2).",
          4,
          "The dot product is 2 × 3 + 1 × (−2) = 4.",
          "Multiply matching coordinates, then add.",
          p(dot([2, 1], [3, -2])),
        ),
      ),
      t(
        "Measure the length",
        "The squared length of a vector equals its dot product with itself. Take the nonnegative square root to obtain the length.",
        length([3, 4]),
        length([-3, 4]),
        num(
          "Find the length of (3, 4).",
          5,
          "The squared length is 9 + 16 = 25, so the length is 5.",
          "Use the square root of the sum of squares.",
          p(length([3, 4])),
        ),
      ),
      t(
        "Square before adding",
        "A vector's dot product with itself cannot be negative. Each matching-coordinate product is a square.",
        dot([1, -2], [1, -2]),
        dot([-1, 2], [-1, 2]),
        num(
          "Find (1, −2) · (1, −2).",
          5,
          "The products are 1 and 4, which sum to 5.",
          "The square of a negative number is positive.",
          p(dot([1, -2], [1, -2])),
        ),
      ),
      t(
        "Ignore the signs in length",
        "Changing signs can change a direction while preserving its length. Squaring removes each coordinate's sign.",
        length([-6, 8]),
        length([6, -8]),
        num(
          "Find the length of (−6, 8).",
          10,
          "The sum of squares is 36 + 64 = 100, whose square root is 10.",
          "Square both coordinates before adding.",
          p(length([-6, 8])),
        ),
      ),
    ],
    [
      num(
        "Find (1, −3) · (2, 4).",
        -10,
        "Compute 1 × 2 + (−3) × 4 = 2 − 12 = −10.",
        "Retain the signs in the products.",
        p(dot([1, -3], [2, 4])),
      ),
      num(
        "Find the length of (5, 12).",
        13,
        "The sum of squares is 25 + 144 = 169, giving length 13.",
        "Take the nonnegative square root.",
        p(length([5, 12])),
      ),
    ],
    [
      recall("Find (−2, 3) · (4, 1).", -5, "The sum is −8 + 3 = −5.", p(dot([-2, 3], [4, 1]))),
      recall(
        "Find the length of (8, 15).",
        17,
        "The squared length is 64 + 225 = 289, so the length is 17.",
        p(length([8, 15])),
      ),
    ],
  ),
  lesson(
    "orthogonal-and-unit-vectors",
    "Orthogonal and unit vectors",
    "Recognise perpendicular vectors and turn a nonzero vector into a unit vector.",
    m,
    ["lin-dot", "lin-orthogonal"],
    [
      t(
        "Test perpendicular directions",
        "Two vectors are orthogonal when their dot product is zero. For nonzero plane vectors, this means their directions are perpendicular.",
        dot([1, 2], [-2, 1]),
        dot([1, 2], [2, 1]),
        num(
          "Find (1, 2) · (−2, 1).",
          0,
          "The products −2 and 2 cancel, so the vectors are orthogonal.",
          "Look for cancellation in the two products.",
          p(dot([1, 2], [-2, 1])),
        ),
      ),
      t(
        "Keep direction, set length to one",
        "Divide a nonzero vector by its length to obtain a unit vector in the same direction. For (3, 4), divide each coordinate by 5.",
        length([3, 4]),
        length([6, 8]),
        num(
          "A unit vector in the direction (3, 4) has what x coordinate?",
          0.6,
          "The length is 5, so the first unit coordinate is 3/5 = 0.6.",
          "Find the length, then divide the first entry by it.",
          { op: "normalize", v: [3, 4], index: 0 },
        ),
      ),
      t(
        "Separate two conditions",
        "Orthogonal vectors do not have to be unit vectors. An orthonormal set must satisfy both perpendicularity and length one.",
        dot([2, 0], [0, 3]),
        dot([1, 0], [0, 1]),
        choice(
          "The vectors (2, 0) and (0, 3) are:",
          ["Orthogonal, but not orthonormal", "Orthonormal", "Neither"],
          0,
          "Their dot product is zero, but their lengths are 2 and 3.",
          "Check the dot product and both lengths separately.",
        ),
      ),
      t(
        "Respect the zero exception",
        "The zero vector has no direction and cannot be normalised by dividing by its length. Division by zero is undefined.",
        length([0, 0]),
        length([0, 1]),
        choice(
          "Can (0, 0) be divided by its length to produce a unit vector?",
          ["Yes", "No"],
          1,
          "Its length is zero, so the required division is undefined.",
          "Find its length before attempting to divide.",
        ),
      ),
    ],
    [
      num(
        "Find (2, −1) · (1, 2).",
        0,
        "The products 2 and −2 add to zero.",
        "Multiply corresponding coordinates.",
        p(dot([2, -1], [1, 2])),
      ),
      num(
        "A unit vector in the direction (0, −7) has what y coordinate?",
        -1,
        "Its length is 7; the second unit coordinate is −7/7 = −1.",
        "Divide by the positive length.",
        { op: "normalize", v: [0, -7], index: 1 },
      ),
    ],
    [
      recall("Find (3, 1) · (1, −3).", 0, "The products 3 and −3 cancel.", p(dot([3, 1], [1, -3]))),
      recall(
        "A unit vector in the direction (−4, 3) has what x coordinate?",
        -0.8,
        "The length is 5, so x = −4/5 = −0.8.",
        { op: "normalize", v: [-4, 3], index: 0 },
      ),
    ],
  ),
];
