import type {
  CourseCheckDefinition,
  EconomicsModel,
} from "../../../packages/contracts/src/index.js";
import {
  costs,
  elastic,
  game,
  margin,
  market,
  monopoly,
  ppf,
  repeated,
  trade,
} from "./definition.js";
import { economicsLessons } from "./lessons.js";

function item(
  id: string,
  lessonIndex: number,
  prompt: string,
  model: EconomicsModel,
  value: number,
  workedAnswer: string,
  unit: string,
): CourseCheckDefinition["items"][number] {
  const lesson = economicsLessons[lessonIndex]!;
  return {
    lessonId: lesson.id,
    visual: { type: "economics", model },
    question: {
      id: "econ-check-" + id,
      conceptIds: ["econ-" + lesson.id],
      sourceIds: lesson.sourceIds,
      prompt,
      responseType: "numeric",
      difficulty: 1,
      hints: [],
      answerAuthority: {
        kind: "numeric",
        value,
        unit,
        absoluteTolerance: 1e-6,
        relativeTolerance: 0,
        workedAnswer,
      },
    },
  };
}
const required = economicsLessons.map((l) => l.id);

export const economicsChecks: CourseCheckDefinition[] = [
  {
    id: "starting-point",
    kind: "placement",
    title: "Find your starting point",
    description:
      "Twelve problems across choice, markets, welfare and strategy. Find which ideas need attention before you start.",
    requiredLessonIds: [],
    items: [
      item(
        "placement-frontier",
        0,
        "A bakery can make at most 80 pies or 20 cakes a day, trading one for the other at a constant rate. What is the opportunity cost of one cake, in pies?",
        ppf("Pies", "Cakes", [
          [0, 20],
          [80, 0],
        ]),
        4,
        "80 pies ÷ 20 cakes = 4 pies per cake.",
        "pies",
      ),
      item(
        "placement-advantage",
        1,
        "In an hour Kim can paint 6 walls or fix 3 doors; Lee can paint 2 walls or fix 2 doors. What is Kim's opportunity cost of fixing one door, in walls?",
        trade("Doors", "Walls", ["Kim", 3, 6], ["Lee", 2, 2]),
        2,
        "6 walls ÷ 3 doors = 2 walls per door; Lee's door costs only 1 wall.",
        "walls",
      ),
      item(
        "placement-margin",
        2,
        "Successive delivery vans bring marginal benefits of £500, £400, £300 and £200 a day. Each van costs £350 a day. How many vans should the firm run?",
        margin("Delivery", "Van", [500, 400, 300, 200], [350, 350, 350, 350]),
        2,
        "£500 and £400 exceed £350; the third van brings only £300.",
        "vans",
      ),
      item(
        "placement-equilibrium",
        3,
        "Demand is Qd = 120 − 4P and supply is Qs = 2P. Find the equilibrium price in pounds.",
        market("Lamps", [120, 4], [0, 2]),
        20,
        "120 − 4P = 2P gives P = £20.",
        "£",
      ),
      item(
        "placement-shift",
        4,
        "Demand is Qd = 120 − 4P and supply is Qs = 2P. Demand rises by 30 units at every price. Find the new equilibrium quantity.",
        market("Lamps", [120, 4], [0, 2], "equilibrium", { demandShift: 30 }),
        50,
        "150 − 4P = 2P gives P = £25 and Q = 50.",
        "units",
      ),
      item(
        "placement-elasticity",
        5,
        "The price of a lamp rises from £9 to £11 and quantity demanded falls from 55 to 45. Find the absolute midpoint elasticity of demand.",
        elastic("Lamps", [100, 5], [9, 11]),
        1,
        "%ΔQ = 10 ÷ 50 = 20%; %ΔP = 2 ÷ 10 = 20%; elasticity = 1.",
        "",
      ),
      item(
        "placement-surplus",
        6,
        "Demand is Qd = 60 − 2P and supply is Qs = 2P − 20. What is consumer surplus at equilibrium, in pounds?",
        market("Scarves", [60, 2], [-20, 2], "surplus"),
        100,
        "60 − 2P = 2P − 20 gives P = £20 and Q = 20. Demand vanishes at £30, so CS = ½ × 20 × 10 = £100.",
        "£",
      ),
      item(
        "placement-tax",
        7,
        "Demand is Qd = 120 − 4P and supply is Qs = 4P − 40. A £3 tax cuts the quantity traded from 40 to 34. What is the deadweight loss, in pounds?",
        market("Candles", [120, 4], [-40, 4], "tax", { tax: 3 }),
        9,
        "½ × 3 × (40 − 34) = £9.",
        "£",
      ),
      item(
        "placement-ceiling",
        8,
        "Demand is Qd = 80 − 2P and supply is Qs = 2P. A price ceiling of £15 is set. How large is the shortage?",
        market("Flats", [80, 2], [0, 2], "control", { control: { kind: "ceiling", price: 15 } }),
        20,
        "At £15, 50 units are demanded and 30 supplied: a shortage of 20.",
        "units",
      ),
      item(
        "placement-costs",
        9,
        "Total cost is TC = 400 + q², so MC = 2q. At what output is average total cost lowest?",
        costs(400, 0, 1),
        20,
        "MC = ATC: 2q = 400/q + q gives q² = 400, so q = 20.",
        "units",
      ),
      item(
        "placement-monopoly",
        10,
        "A monopolist faces P = 90 − Q with a constant marginal cost of £30. What price does it charge, in pounds?",
        monopoly(90, 1, 30),
        60,
        "MR = 90 − 2Q = 30 gives Q = 30, so P = 90 − 30 = £60.",
        "£",
      ),
      item(
        "placement-game",
        11,
        "Payoffs (row, column) are Top/Left (4, 4), Top/Right (1, 6), Bottom/Left (6, 1) and Bottom/Right (2, 2). What is the column player's payoff in the Nash equilibrium?",
        game(
          ["Row", "Column"],
          ["Top", "Bottom"],
          ["Left", "Right"],
          [
            [
              [4, 4],
              [1, 6],
            ],
            [
              [6, 1],
              [2, 2],
            ],
          ],
        ),
        2,
        "Bottom and Right are dominant, so the equilibrium is Bottom/Right, paying the column player 2.",
        "",
      ),
    ],
  },
  {
    id: "mixed-challenge",
    kind: "checkpoint",
    title: "Bring the ideas together",
    description:
      "Twelve fresh problems, one for every lesson. Write the equations down, solve them carefully and keep track of units.",
    requiredLessonIds: required,
    items: [
      item(
        "mixed-frontier",
        0,
        "A frontier passes through (0 grain, 60 cloth), (10, 55), (20, 45), (30, 30) and (40, 0). Between 20 and 30 units of grain, what is the opportunity cost per unit of grain, in cloth?",
        ppf("Grain", "Cloth", [
          [0, 60],
          [10, 55],
          [20, 45],
          [30, 30],
          [40, 0],
        ]),
        1.5,
        "Cloth falls from 45 to 30 while grain rises by 10: 15 ÷ 10 = 1.5.",
        "cloth",
      ),
      item(
        "mixed-advantage",
        1,
        "Per worker-year, country P makes 40 tonnes of rice or 20 tonnes of steel; country Q makes 30 tonnes of rice or 10 tonnes of steel. What is country Q's opportunity cost of a tonne of steel, in tonnes of rice?",
        trade("Steel", "Rice", ["Country P", 20, 40], ["Country Q", 10, 30]),
        3,
        "30 ÷ 10 = 3 tonnes of rice per tonne of steel, against 2 in country P.",
        "tonnes",
      ),
      item(
        "mixed-margin",
        2,
        "Extra lab tests bring marginal benefits of £60, £45, £35 and £20, with marginal costs of £15, £25, £30 and £40. What total net benefit does the best number of tests give, in pounds?",
        margin("Testing", "Test", [60, 45, 35, 20], [15, 25, 30, 40]),
        70,
        "Run three tests: (60 − 15) + (45 − 25) + (35 − 30) = £70. The fourth would lose £20.",
        "£",
      ),
      item(
        "mixed-equilibrium",
        3,
        "Demand is Qd = 200 − 5P and supply is Qs = 3P − 40. Find the equilibrium quantity.",
        market("Bikes", [200, 5], [-40, 3]),
        50,
        "200 − 5P = 3P − 40 gives P = £30, so Q = 200 − 150 = 50.",
        "units",
      ),
      item(
        "mixed-shift",
        4,
        "Demand is Qd = 200 − 5P and supply is Qs = 3P − 40. A tariff on imported parts cuts supply by 16 units at every price. Find the new equilibrium price in pounds.",
        market("Bikes", [200, 5], [-40, 3], "equilibrium", { supplyShift: -16 }),
        32,
        "200 − 5P = 3P − 56 gives 256 = 8P, so P = £32.",
        "£",
      ),
      item(
        "mixed-revenue",
        5,
        "Demand is Qd = 100 − 4P. The price rises from £5 to £10. By how many pounds does total revenue change?",
        elastic("Mugs", [100, 4], [5, 10]),
        200,
        "Quantity falls from 80 to 60; revenue rises from £400 to £600, by £200.",
        "£",
      ),
      item(
        "mixed-producer",
        6,
        "Demand is Qd = 100 − 2P and supply is Qs = 2P − 20. What is producer surplus at equilibrium, in pounds?",
        market("Boots", [100, 2], [-20, 2], "surplus"),
        400,
        "100 − 2P = 2P − 20 gives P = £30 and Q = 40. Sellers offer nothing below £10, so PS = ½ × 40 × 20 = £400.",
        "£",
      ),
      item(
        "mixed-tax",
        7,
        "Demand is Qd = 100 − 2P and supply is Qs = 2P − 20. A £4 tax is collected from sellers. What price do buyers pay, in pounds?",
        market("Boots", [100, 2], [-20, 2], "tax", { tax: 4 }),
        32,
        "100 − 2P = 2(P − 4) − 20 gives 128 = 4P, so buyers pay £32 and sellers keep £28.",
        "£",
      ),
      item(
        "mixed-externality",
        8,
        "In a fertiliser market demand is Qd = 90 − 3P and supply is Qs = 3P − 30, and each tonne causes £6 of run-off damage to others. What is the efficient quantity, in tonnes?",
        market("Fertiliser", [90, 3], [-30, 3], "externality", { externalCost: 6 }),
        21,
        "Social supply 3(P − 6) − 30 equals 90 − 3P at 138 = 6P, so P = £23 and Q = 90 − 69 = 21.",
        "tonnes",
      ),
      item(
        "mixed-profit",
        9,
        "A competitive firm has TC = 50 + 4q + q², so MC = 4 + 2q. The market price is £24. What is its profit at the best output, in pounds?",
        costs(50, 4, 1, 24),
        50,
        "24 = 4 + 2q gives q = 10. Revenue £240, cost 50 + 40 + 100 = £190, profit £50.",
        "£",
      ),
      item(
        "mixed-monopoly",
        10,
        "A monopolist faces P = 150 − 3Q with a constant marginal cost of £30. What is the deadweight loss of monopoly, in pounds?",
        monopoly(150, 3, 30),
        600,
        "MR = 150 − 6Q = 30 gives Q = 20 at £90; competition gives Q = 40. DWL = ½ × 20 × 60 = £600.",
        "£",
      ),
      item(
        "mixed-repeated",
        11,
        "Each round, mutual cooperation pays 6 each, mutual defection 2 each, and a lone defector gets 9 while the cooperator gets nothing. Tit for tat plays always-defect for 4 rounds. What is tit for tat's total?",
        repeated(
          ["tit_for_tat", "always_defect"],
          4,
          { reward: 6, temptation: 9, sucker: 0, punishment: 2 },
          ["Cooperate", "Defect"],
        ),
        6,
        "Round one: 0. Rounds two to four: 2 each. Total 0 + 3 × 2 = 6.",
        "",
      ),
    ],
  },
  {
    id: "later-applications",
    kind: "transfer",
    title: "Use it a week later",
    description:
      "Twelve new situations after a delay. State the opportunity cost, write the curves as equations and compare at the margin.",
    requiredLessonIds: required,
    afterCheckId: "mixed-challenge",
    delayDays: 7,
    items: [
      item(
        "later-frontier",
        0,
        "A city's budget can build at most 12 schools or 4 hospitals, at a constant trade-off. What is the opportunity cost of one hospital, in schools?",
        ppf("Schools", "Hospitals", [
          [0, 4],
          [12, 0],
        ]),
        3,
        "12 ÷ 4 = 3 schools per hospital.",
        "schools",
      ),
      item(
        "later-advantage",
        1,
        "Hill Farm can grow 20 tonnes of wheat or 10 tonnes of barley; Vale Farm can grow 30 tonnes of wheat or 10 tonnes of barley. What is Hill Farm's opportunity cost of a tonne of barley, in tonnes of wheat?",
        trade("Barley", "Wheat", ["Hill Farm", 10, 20], ["Vale Farm", 10, 30]),
        2,
        "20 ÷ 10 = 2 tonnes of wheat per tonne of barley, below Vale Farm's 3.",
        "tonnes",
      ),
      item(
        "later-margin",
        2,
        "A gym's extra weekly classes bring marginal benefits of £80, £70, £50 and £30. Each costs £40 to run. A £500 refit was paid last year. How many extra classes should it run?",
        margin("Classes", "Class", [80, 70, 50, 30], [40, 40, 40, 40]),
        3,
        "The refit is sunk. £80, £70 and £50 exceed £40; the fourth class brings £30.",
        "classes",
      ),
      item(
        "later-equilibrium",
        3,
        "Demand is Qd = 70 − P and supply is Qs = 4P − 30. Find the equilibrium price in pounds.",
        market("Rackets", [70, 1], [-30, 4]),
        20,
        "70 − P = 4P − 30 gives 100 = 5P, so P = £20.",
        "£",
      ),
      item(
        "later-shift",
        4,
        "Demand is Qd = 70 − P and supply is Qs = 4P − 30. Buyers expect prices to rise next month, and demand grows by 25 units at every price. Find the new equilibrium price in pounds.",
        market("Rackets", [70, 1], [-30, 4], "equilibrium", { demandShift: 25 }),
        25,
        "95 − P = 4P − 30 gives 125 = 5P, so P = £25.",
        "£",
      ),
      item(
        "later-elasticity",
        5,
        "A streaming plan's monthly price rises from £9 to £11 and subscribers fall from 1,050 to 950. Find the absolute midpoint elasticity of demand.",
        elastic("Streaming", [1500, 50], [9, 11]),
        0.5,
        "%ΔQ = 100 ÷ 1,000 = 10%; %ΔP = 2 ÷ 10 = 20%; elasticity = 0.5.",
        "",
      ),
      item(
        "later-surplus",
        6,
        "Demand is Qd = 120 − P and supply is Qs = 2P − 60. What is total surplus at equilibrium, in pounds?",
        market("Tickets", [120, 1], [-60, 2], "surplus"),
        2700,
        "120 − P = 2P − 60 gives P = £60 and Q = 60. CS = ½ × 60 × 60 = £1,800; PS = ½ × 60 × 30 = £900; total £2,700.",
        "£",
      ),
      item(
        "later-incidence",
        7,
        "Demand is Qd = 60 − P and supply is Qs = 2P − 30. A £6 tax is collected from sellers. How many pounds of the tax per unit do buyers bear?",
        market("Wine", [60, 1], [-30, 2], "tax", { tax: 6 }),
        4,
        "Without the tax P = £30. With it, 60 − P = 2(P − 6) − 30 gives P = £34, so buyers bear £4 and sellers £2.",
        "£",
      ),
      item(
        "later-floor",
        8,
        "Demand is Qd = 60 − P and supply is Qs = 2P − 30. A price floor of £35 is set. How many units go unsold?",
        market("Wine", [60, 1], [-30, 2], "control", { control: { kind: "floor", price: 35 } }),
        15,
        "At £35, 40 units are supplied and 25 demanded: 15 unsold.",
        "units",
      ),
      item(
        "later-profit",
        9,
        "A competitive firm has TC = 64 + 4q + q², so MC = 4 + 2q. The market price is £20. What is its profit at the best output, in pounds?",
        costs(64, 4, 1, 20),
        0,
        "20 = 4 + 2q gives q = 8. Revenue £160 and cost 64 + 32 + 64 = £160, so profit is nothing: the price equals the minimum of ATC.",
        "£",
      ),
      item(
        "later-monopoly",
        10,
        "A monopolist faces P = 40 − Q with a constant marginal cost of £10 and no fixed cost. What is its profit, in pounds?",
        monopoly(40, 1, 10),
        225,
        "MR = 40 − 2Q = 10 gives Q = 15 at £25. Profit = (25 − 10) × 15 = £225.",
        "£",
      ),
      item(
        "later-game",
        11,
        "Row chooses Up or Down; Column chooses Left, Centre or Right. Payoffs (row, column): Up/Left (3, 1), Up/Centre (2, 4), Up/Right (0, 2), Down/Left (1, 3), Down/Centre (4, 2), Down/Right (2, 5). What is the row player's payoff in the Nash equilibrium?",
        game(
          ["Row", "Column"],
          ["Up", "Down"],
          ["Left", "Centre", "Right"],
          [
            [
              [3, 1],
              [2, 4],
              [0, 2],
            ],
            [
              [1, 3],
              [4, 2],
              [2, 5],
            ],
          ],
        ),
        2,
        "Column's best reply to Down is Right, and Row's best reply to Right is Down, so Down/Right is the only equilibrium: Row earns 2.",
        "",
      ),
    ],
  },
];
